In [5]:
import pandas as pd
import scipy as sp
import numpy as np
from lightfm import cross_validation
from lightfm.evaluation import precision_at_k
from lightfm.evaluation import recall_at_k
from lightfm.evaluation import auc_score
from lightfm import LightFM
import matplotlib.pyplot as plt
import pickle
import collections
import seaborn as sns
import gzip
import textwrap
import os
from datetime import date
import time
import sys

**Create trait vs SNP matrix**

In [2]:
#load data
data = []
with open("/home/nasi4/proj/GWAS/UKBB_201807/results/all.UKBB.hg38.sig.phenotype.bed")as f:
    for line in f:
        data.append(line.strip().split())

#combine label elements
for row in data:
    row.append(' '.join(row[5:]))
    del row[5:-1]
    
#create dataframe
df = pd.DataFrame(data, columns = ['Chromosome', 'p1', 'p2', 'Reference SNP cluster ID', 'p-value', 'Trait'])
d = df
# df = df[df['p-value']!='0.00000e+00']
# test_list = df['p-value'].to_list()
# test_list = list(map(float, test_list))
# print(max(test_list))

# #calculating the negative log of the p-value, setting infinite values to the max non-infinite value observed, and
# #normalizing by max -log(p-value) score
# pval_mlog = -np.log(list(map(float, list(df['p-value']))))

# inf_mask = np.ma.array(pval_mlog, mask=~np.isfinite(pval_mlog))
# max_ind = np.ma.argmax(inf_mask, fill_value=-np.inf)
# print(max_ind)
# max_val = pval_mlog[max_ind]
# print(max_val)

# for ind in range(len(pval_mlog)):
#     if pval_mlog[ind] > pval_mlog[max_ind]:
#         pval_mlog[ind] = pval_mlog[max_ind]
        
# df['pval_mlog'] = pval_mlog/pval_mlog[max_ind]

# df[(df['Trait']=='Weight')&(df['Reference SNP cluster ID']=='16:53812770_ATTTT_A')]

# # Reference SNP cluster ID: rs11642015, chr16:53768582-53768583, p-value = 1.14192e-191

# #creating df with SNP, trait, and p-value
# ts_df = df[['Reference SNP cluster ID', 'Trait', 'pval_mlog']]

# #finding unique traits and SNPs
# SNP_values = np.unique(ts_df['Reference SNP cluster ID'].values)
# trait_values = np.unique(ts_df['Trait'].values)

# ts = ts_df.groupby(['Reference SNP cluster ID', 'Trait']).max()

# #20211129 - changed from original way I did this. 
# # I was averaging all -ln(p-values) from a given trait vs SNP combination
# # now I am taking the max valeu
# # ts = ts_df.groupby(['Reference SNP cluster ID', 'Trait']).mean()
# ts = ts.reset_index()

# ts['trait_ind'] = ts.groupby(['Trait']).ngroup()
# ts['snp_ind'] = ts.groupby(['Reference SNP cluster ID']).ngroup()

# columns = ts['snp_ind'].to_list()
# rows = ts['trait_ind'].to_list()
# pval_mlog_data = ts['pval_mlog'].to_list()

# data_coo = sp.sparse.coo_matrix((pval_mlog_data, (rows, columns)), shape=(len(trait_values), len(SNP_values)))

5e-08
736764
743.7469247408213

/tmp/ipykernel_17583/461438952.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pval_mlog'] = pval_mlog/pval_mlog[max_ind]

In [ ]:
len(SNP_values)

In [3]:
data_matrix = data_coo.toarray()

In [6]:
sys.getsizeof(data_matrix)

63793819720

In [8]:
data_matrix.shape

(3815, 2090230)

In [8]:
pickle_out = open('/home/ctrader/Hold/GWAS/GWAS_trait_values_CT20220110.pickle', 'wb')
pickle.dump(trait_values, pickle_out)
pickle_out.close()

In [2]:
pickle_in = open('/home/ctrader/Hold/GWAS/GWAS_trait_values_CT20220110.pickle', 'rb')
trait_values=pickle.load(pickle_in)

In [3]:
trait_values

array(['#Arthrosis', '#Deforming dorsopathies', '#Other joint disorders',
       ..., 'malignant neoplasm of female genital organs',
       'malignant neoplasm of male genital organs',
       'severe traumatic brain injury, does not include concussion'],
      dtype=object)

**Load Model**

In [42]:
pickle_in = open('/home/ctrader/Hold/GWAS/gwas_model_e30_d10_reg00001_CT20211006.pickle', 'rb')
gwas_model_e30_d10_reg00001=pickle.load(pickle_in)

pickle_in = open('/home/ctrader/Hold/GWAS/gwas_data_e30_d10_reg00001_CT20211006.pickle', 'rb')
data_e30_d10_reg00001=pickle.load(pickle_in)

In [4]:
# snp_b, snp_e = gwas_model_e30_d10_reg00001.get_item_representations()
# snp_e = snp_e.T
# trait_b, trait_e = gwas_model_e30_d10_reg00001.get_user_representations()

In [5]:
# n_dimensions, n_snps = snp_e.shape
# n_traits, n_dimensions = trait_e.shape

In [6]:
# gwas_model_e30_d10_reg00001.predict(1600, np.arange(n_snps))

In [7]:
# predictions = ((np.dot(trait_e, snp_e) + snp_b).T + trait_b).T

In [8]:
# predictions_sorted = np.argsort(-predictions, axis=1)

In [11]:
# predictions_sorted_100 = predictions_sorted[:, :100]

In [60]:
predictions_sorted_100 = generate_100_recs(gwas_model_e30_d10_reg00001)

NameError: name 'generate_100_recs' is not defined

In [77]:
pickle_out = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/top_100_SNP_recommendations_for_each_trait_all_traits_CT20220112.pickle', 'wb')
pickle.dump(predictions_sorted_100, pickle_out)
pickle_out.close()

In [61]:
pickle_in = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/top_100_SNP_recommendations_for_each_trait_all_traits_CT20220112.pickle', 'rb')
predictions_sorted_100=pickle.load(pickle_in)

In [5]:
ts_trait_based = ts.groupby(['Trait']).first()
trait_values_order_to_match_subthreshold = list(ts_trait_based.loc[np.array(trait_values)]['trait_ind'])
ts_snp_ind_based = ts.groupby(['snp_ind']).first()
df_snp_id_based = df.groupby(['Reference SNP cluster ID']).first()

In [123]:
#before p-value was found for each recommended SNP
top_100_recommended_snps_all_traits_chrm_list = []
top_100_recommended_snps_all_traits_start_list = []
top_100_recommended_snps_all_traits_end_list = []
top_100_recommended_snps_all_traits_order_list = []
top_100_recommended_snps_all_traits_id_list = []
j=0
for i in trait_values_order_to_match_subthreshold:
    #getting information for all SNP recs for each trait
    snp_info_df = df_snp_id_based.loc[ts_snp_ind_based.loc[predictions_sorted_100[i]]['Reference SNP cluster ID']]
    top_100_recommended_snps_all_traits_chrm_list.extend(list(snp_info_df['Chromosome']))
    top_100_recommended_snps_all_traits_start_list.extend(list(snp_info_df['p1']))
    top_100_recommended_snps_all_traits_end_list.extend(list(snp_info_df['p2']))
    top_100_recommended_snps_all_traits_order_list.extend(list(100*j + np.arange(100)))
    top_100_recommended_snps_all_traits_id_list.extend(list(snp_info_df.index))
    j+=1

In [124]:
pickle_out = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/top_100_SNP_recommendations_for_each_trait_all_traits_id_list_CT20220124.pickle', 'wb')
pickle.dump(top_100_recommended_snps_all_traits_id_list, pickle_out)
pickle_out.close()

In [70]:
pickle_in = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/top_100_SNP_recommendations_for_each_trait_all_traits_id_list_CT20220124.pickle', 'rb')
top_100_recommended_snps_all_traits_id_list=pickle.load(pickle_in)

In [15]:
# top_100_recommended_snps_all_traits_pval_list = []
# for i in trait_values_order_to_match_subthreshold:
#     snp_info_df = df_snp_id_based.loc[ts_snp_ind_based.loc[predictions_sorted_100[i]]['Reference SNP cluster ID']]

In [102]:
tv = trait_values[0:5]

In [24]:
print(trait_df[trait_df['Reference SNP cluster ID']==rec_snp_id]['p-value'])

4512595    0.000004
Name: p-value, dtype: float64

In [26]:
trait_df

NameError: name 'trait_df' is not defined

In [77]:
i=0
rec_snp_id = top_100_recommended_snps_all_traits_id_list[(i*100):(i*100)+100]

trait_df_snp_ind_based = trait_df.set_index('Reference SNP cluster ID')
trait_df_snp_ind_based = trait_df_snp_ind_based.loc[trait_df_snp_ind_based.index.isin(rec_snp_id)]
trait_df_snp_ind_based = trait_df_snp_ind_based.sort_values(['p-value'])
trait_df_snp_ind_based = trait_df_snp_ind_based.groupby(['Reference SNP cluster ID']).first()

trait_df_snp_ind_based = trait_df_snp_ind_based.loc[rec_snp_id]
pvals_for_rec_snps.extend(trait_df_snp_ind_based['p-value'])

In [148]:
trait_num = 0




tv = trait_values[:5]




#load traits and phenotypes
trait_codes = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:
    for line in f:
        trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])

trait_codes_df['description'] = trait_codes_df['description'].str.replace(')', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('(', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('-', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('[', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace(']', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('+', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('_', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace(' ', '')

#find the phenotype for each trait
phenotype_list = []
not_added = []
for original_trait in tv:
    trait = original_trait.replace(')', ' ').replace('(', ' ').replace('-', ' ').replace('[', ' ').replace(']', ' ').replace('+', ' ').replace('_', ' ').replace(' ', '')
    if len(trait_codes_df[trait_codes_df['description']==(trait)])==1:
        phenotype_list.append(list(trait_codes_df[trait_codes_df['description']==(trait)]['phenotype'])[0])
    elif ((len(trait_codes_df[trait_codes_df['description']==(trait)])==2) & (len(trait_codes_df[(trait_codes_df['description']==(trait)) & (trait_codes_df['phenotype'].str.contains('irnt'))])==1)):
        phenotype_list.append(list(trait_codes_df[(trait_codes_df['description']==(trait)) & (trait_codes_df['phenotype'].str.contains('irnt'))]['phenotype'])[0])
    else:
        phenotype_list.append('SKIP_CT20220107')
        not_added.append(original_trait)

#search through full data to find the p-values for each recommended SNP for each trait
pvals_for_rec_snps = []
snp_id_check = []
for phenotype, trait, i in zip(phenotype_list, tv, range(len(phenotype_list))):
    i = i + trait_num
    if phenotype != 'SKIP_CT20220107':
        t = time.time()
        print(trait, phenotype)
        trait_data = []
        with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/phenotypes/' + phenotype + '.gwas.imputed_v3.both_sexes/' + phenotype + '.hg38.bed.gz','r') as f:
            for line in f:
                trait_data.append(line.decode("utf-8").strip('\n').split('\t'))
        trait_df = pd.DataFrame(trait_data, columns=['Chromosome', 'Start', 'End', 'Reference SNP cluster ID', 'p-value'])
        trait_df['p-value'] = trait_df['p-value'].astype('float')

        rec_snp_ids_one_trait = top_100_recommended_snps_all_traits_id_list[(i*100):(i*100)+100]
        
        trait_df_snp_ind_based = trait_df.set_index('Reference SNP cluster ID')
        trait_df_snp_ind_based = trait_df_snp_ind_based.loc[trait_df_snp_ind_based.index.isin(rec_snp_ids_one_trait)]
        trait_df_snp_ind_based = trait_df_snp_ind_based.sort_values(['p-value'])
        trait_df_snp_ind_based = trait_df_snp_ind_based.groupby(['Reference SNP cluster ID']).first()
        
        if len(trait_df_snp_ind_based)==100:
            trait_df_snp_ind_based = trait_df_snp_ind_based.loc[rec_snp_ids_one_trait]
            pvals_for_rec_snps.extend(list(trait_df_snp_ind_based['p-value']))
            snp_id_check.extend(list(trait_df_snp_ind_based.index))
        
        else:
            trait_df_snp_ind_based['SNP ID Col 2'] = trait_df_snp_ind_based.index
            for snp_id in rec_snp_ids_one_trait:
                snp_df = trait_df_snp_ind_based[trait_df_snp_ind_based['SNP ID Col 2']==snp_id]
                snp_id_check.append(snp_id)
                if len(snp_df)==1:
                    pvals_for_rec_snps.append(snp_df['p-value'])
                else:
                    pvals_for_rec_snps.append(np.nan)
                    
        print(time.time()-t)
    else:
        pvals_for_rec_snps.extend(list(np.array(['SKIP_CT20220107']*100)))
        snp_id_check.extend(list(np.array(['SKIP_CT20220107']*100)))

#pickle out the p-values and traits 
# pickle_out = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/recommended_SNPs_for_each_trait_'+str(trait_num)+'_through_'+str(trait_num+4)+'_CT20220124.pickle', 'wb')
# pickle.dump(snp_id_check, pickle_out)
# pickle_out.close()

# pickle_out = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/recommended_SNP_pvals_for_each_trait_'+str(trait_num)+'_through_'+str(trait_num+4)+'_CT20220124.pickle', 'wb')
# pickle.dump(pvals_for_rec_snps, pickle_out)
# pickle_out.close()

/tmp/ipykernel_138476/480664581.py:19: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace(')', ' ')
/tmp/ipykernel_138476/480664581.py:20: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace('(', ' ')
/tmp/ipykernel_138476/480664581.py:22: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace('[', ' ')
/tmp/ipykernel_138476/480664581.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace(']', ' ')
/tmp/ipykernel_138476/480664581.py:24: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace('+', ' ')

#Arthrosis M13_ARTHROSIS
92.29880619049072
#Deforming dorsopathies M13_DEFORMDORSO
77.37968158721924
#Other joint disorders M13_OTHERJOINT
93.77946162223816
#Other necrotizing vasculopathies M13_NECROVASC

KeyboardInterrupt:

In [3]:
rec_100_snp_pvals_all_traits = []
for i in range(0, 3815, 5):
    pickle_in = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/recommended_SNP_pvals_for_each_trait_'+str(i)+'_through_'+str(i+4)+'_CT20220124.pickle', 'rb')
    rec_100_snp_pvals_5_traits=pickle.load(pickle_in)
    rec_100_snp_pvals_all_traits.extend(rec_100_snp_pvals_5_traits)

In [4]:
rec_100_snps_all_traits = []
for i in range(0, 3815, 5):
    pickle_in = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/recommended_SNPs_for_each_trait_'+str(i)+'_through_'+str(i+4)+'_CT20220124.pickle', 'rb')
    rec_100_snps_5_traits=pickle.load(pickle_in)
    rec_100_snps_all_traits.extend(rec_100_snps_5_traits)

In [5]:
phen_list = []
for i in range(0, 3815, 5):
    pickle_in = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/phenotype_list_for_recs_'+str(i)+'_through_'+str(i+4)+'_CT20220124.pickle', 'rb')
    x=pickle.load(pickle_in)
    phen_list.extend(x)

In [73]:
ts[ts['trait_ind']==1]['Trait'].iloc[0]

'#Deforming dorsopathies'

In [76]:
ts[ts['snp_ind']==1857466]['Reference SNP cluster ID'].iloc[0]

'rs761308380'

In [7]:
t = d[d['Trait']=='Radial styloid tenosynovitis [de Quervain]']
# t[t['Reference SNP cluster ID']=='rs761308380']
t

Empty DataFrame
Columns: [Chromosome, p1, p2, Reference SNP cluster ID, p-value, Trait]
Index: []

In [194]:
t = d[d['p-value']=='8.97135e-15']
t

,Chromosome,p1,p2,Reference SNP cluster ID,p-value,Trait
2141,chr1,999705,999706,rs144665333,8.97135e-15,#Deforming dorsopathies
8057520,chr21,33432280,33432281,rs201843430,8.97135e-15,"Diagnoses - main ICD10: J40 Bronchitis, not sp..."

In [208]:
phenotype = 'M13_DEQUERVAIN'
trait_data = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/phenotypes/' + phenotype + '.gwas.imputed_v3.both_sexes/' + phenotype + '.hg38.bed.gz','r') as f:
    for line in f:
        trait_data.append(line.decode("utf-8").strip('\n').split('\t'))
trait_dfM13_DEQUERVAIN = pd.DataFrame(trait_data, columns=['Chromosome', 'Start', 'End', 'Reference SNP cluster ID', 'p-value'])
trait_dfM13_DEQUERVAIN['p-value'] = trait_dfM13_DEQUERVAIN['p-value'].astype('float')

In [210]:
trait_dfM13_DEQUERVAIN[trait_dfM13_DEQUERVAIN['p-value']==8.97135e-15]

    Chromosome   Start     End Reference SNP cluster ID       p-value
957       chr1  999705  999706              rs144665333  8.971350e-15

In [204]:
M13_DEFORMDORSOtrait_df[M13_DEFORMDORSOtrait_df['p-value']==8.97135e-15]

Empty DataFrame
Columns: [Chromosome, Start, End, Reference SNP cluster ID, p-value]
Index: []

In [209]:
trait_dfM13_DEQUERVAIN[trait_dfM13_DEQUERVAIN['Reference SNP cluster ID']=='rs144665333']

    Chromosome   Start     End Reference SNP cluster ID       p-value
957       chr1  999705  999706              rs144665333  8.971350e-15

In [207]:
M13_DEFORMDORSOtrait_df[M13_DEFORMDORSOtrait_df['Reference SNP cluster ID']=='rs144665333']

    Chromosome   Start     End Reference SNP cluster ID   p-value
957       chr1  999705  999706              rs144665333  0.932049

In [203]:
phenotype = 'M13_DEFORMDORSO'
trait_data = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/phenotypes/' + phenotype + '.gwas.imputed_v3.both_sexes/' + phenotype + '.hg38.bed.gz','r') as f:
    for line in f:
        trait_data.append(line.decode("utf-8").strip('\n').split('\t'))
M13_DEFORMDORSOtrait_df = pd.DataFrame(trait_data, columns=['Chromosome', 'Start', 'End', 'Reference SNP cluster ID', 'p-value'])
M13_DEFORMDORSOtrait_df['p-value'] = M13_DEFORMDORSOtrait_df['p-value'].astype('float')

In [107]:
# rec_100_snps_all_traits[381491]
# phen_list[1]

In [3]:
trait_codes = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:
    for line in f:
        trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])

In [4]:
pd.options.display.max_colwidth=1000
trait_codes_df[trait_codes_df['phenotype']=='M13_DEQUERVAIN']

,phenotype,description,variable_type,source,n_non_missing,n_missing,n_controls,n_cases,PHESANT_transformation,notes
1033,M13_DEQUERVAIN,Radial styloid tenosynovitis [de Quervain],categorical,finngen,361194,0,360952,242,NA,NA

In [84]:
rec_100_snp_pvals_all_traits[115]

0.789317

In [51]:
#including p-val information and creating lists for bed file
top_100_recommended_snps_all_traits_chrm_list = []
top_100_recommended_snps_all_traits_start_list = []
top_100_recommended_snps_all_traits_end_list = []
top_100_recommended_snps_all_traits_order_list = []
top_100_recommended_snps_all_traits_id_list = []
top_100_recommended_snps_all_traits_pvals = []
for i in range(0, len(rec_100_snps_all_traits), 100):
    #getting information for all SNP recs for each trait
#     snp_info_df = df_snp_id_based.loc[ts_snp_ind_based.loc[predictions_sorted_100[i]]['Reference SNP cluster ID']]
    per_trait_rec_snps_ids = rec_100_snps_all_traits[i:i+100]
    if per_trait_rec_snps_ids[0] == 'SKIP_CT20220107':
        continue
    snp_info_df = df_snp_id_based.loc[per_trait_rec_snps_ids]
#     if len(snp_info_df) != 100:
#         print(len(snp_info_df))
    top_100_recommended_snps_all_traits_chrm_list.extend(list(snp_info_df['Chromosome']))
    top_100_recommended_snps_all_traits_start_list.extend(list(snp_info_df['p1']))
    top_100_recommended_snps_all_traits_end_list.extend(list(snp_info_df['p2']))
    top_100_recommended_snps_all_traits_order_list.extend(list(i + np.arange(100)))
    top_100_recommended_snps_all_traits_id_list.extend(list(snp_info_df.index))
    top_100_recommended_snps_all_traits_pvals.extend(rec_100_snp_pvals_all_traits[i:i+100])

In [60]:
#double checking results
test = []
for i in rec_100_snps_all_traits:
    if i != 'SKIP_CT20220107':
        test.append(i)
for i, j in zip(test, top_100_recommended_snps_all_traits_id_list):
    if i != j:
        print(i, j)

In [67]:
#double checking results
c=0
for i in range(len(rec_100_snps_all_traits)):
    if rec_100_snps_all_traits[i] != 'SKIP_CT20220107':
        if rec_100_snps_all_traits[i] != top_100_recommended_snps_all_traits_id_list[i-c]:
            print(rec_100_snps_all_traits[i], top_100_recommended_snps_all_traits_id_list[i-c])
        
    else:
        c += 1

In [73]:
#Creating a bed file for top 100 recommended snps for each trait with pvals
today = date.today()
bed_path_name = os.path.join('/home/ctrader/Hold/GWAS/recommendations/', 'GWAS_top_100_recommended_SNPs_for_each_trait_all_traits_with_pvals_CT' + today.strftime("%Y%m%d") + '.bed')
f= open(bed_path_name, 'w')
for i in range(len(top_100_recommended_snps_all_traits_chrm_list)):
    f.write(top_100_recommended_snps_all_traits_chrm_list[i] + '\t' + str(top_100_recommended_snps_all_traits_start_list[i]) + '\t' + str(top_100_recommended_snps_all_traits_end_list[i]) + '\t' + str(top_100_recommended_snps_all_traits_id_list[i]) + '\t' + str(top_100_recommended_snps_all_traits_order_list[i])+ '\t' + str(top_100_recommended_snps_all_traits_pvals[i]) + '\n')
f.close()

**Function to recommend 100 SNPs for each trait**

In [23]:
def generate_100_recs(model):
    #retrieving the trait and SNP biases and embeddings for calculating prediction scores
    snp_b, snp_e = model.get_item_representations()
    snp_e = snp_e.T
    trait_b, trait_e = model.get_user_representations()
    n_dimensions, n_snps = snp_e.shape
    n_traits, n_dimensions = trait_e.shape
    #calculating predictions scores for each trait-SNP interaction
    predictions = ((np.dot(trait_e, snp_e) + snp_b).T + trait_b).T
    #sorting prediction scores to get the ordered SNP recommendations for each trait
    predictions_sorted = np.argsort(-predictions, axis=1)
    #taking the first 100 SNP recommendations for each trait
#     predictions_sorted_100 = predictions_sorted[:, :100]
    predictions_sorted_100_new = np.zeros([n_traits, 100]).astype(int)
    for i in range(len(predictions_sorted)):
        count=0
        for j in predictions_sorted[i]:
            if data_matrix[i, j] == 0:
                predictions_sorted_100_new[i, count]=j
                count+=1
                if count == 100:
                    break
    return predictions_sorted_100

In [46]:
snp_b, snp_e = gwas_model_e30_d10_reg00001.get_item_representations()
snp_e = snp_e.T
trait_b, trait_e = gwas_model_e30_d10_reg00001.get_user_representations()
n_dimensions, n_snps = snp_e.shape
n_traits, n_dimensions = trait_e.shape

predictions = ((np.dot(trait_e, snp_e) + snp_b).T + trait_b).T
predictions_sorted = np.argsort(-predictions, axis=1)

In [49]:
predictions_sorted

array([[1579853, 1136184,  505766, ...,  410638,  102652, 1500625],
       [1397627, 1387002, 1930278, ..., 1008147, 1002570, 2005792],
       [1579853, 1442482, 1579859, ...,  737550,  394384, 1756435],
       ...,
       [ 502746,  513280, 1767920, ...,  673519, 1310764, 1804105],
       [1383034,  262861,  396913, ...,  722791, 1884527, 1864524],
       [1397627, 1387002, 1418775, ...,   55130, 1911456, 1718382]])

In [66]:
predictions_sorted_100_new = np.zeros([n_traits, 100]).astype(int)
for i in range(len(predictions_sorted)):
    count=0
    for j in predictions_sorted[i]:
        if data_matrix[i, j] == 0:
            predictions_sorted_100_new[i, count]=j
            count+=1
            if count == 100:
                break

In [69]:
data_matrix[1, 1857466]

0.04958729701043407

In [68]:
print(predictions_sorted_100_new[1])
print(predictions_sorted_100[1])

[1397627 1387002 1930278 1418775 1807023 1960888 1994614 1974248 1014146
 1427574 1251707  531659  217756 1307683  187615 1957431 1501996  259467
 1479849 1079079  554607  530615 1347770 1343291  899003  174302 1889070
 1279249  901851 1276607  349512 1137141  237365  502746  385965  505011
  892580  536178  276845 1523221 1289027 1515393  891663  224331  239325
 1593960 1144914 1316766  609535 1169629  908562  272923  470157  201808
  227478 1976750 1465526 1017339    1826  441780  453443  200295  266409
 1065875  474180 1992110  642890   80522  794212  262785 1549497 1904039
 1059298 1135334  675304  248547  617976  476645 1774873 1309903 1139639
  563917  432996 1591950 1142883 2000191 1312701   82933  261145  610749
  861081 1534337  266034 1591095  544875 1593687  270405 1037492 1294143
 1819062]
[1397627 1387002 1930278 1418775 1807023 1960888 1994614 1974248 1014146
 1427574 1251707  531659  217756 1307683  187615 1857466 1957431 1501996
  259467 1479849 1079079  554607  530615 1347770 1343291  899003  174302
 1889070 1279249  901851 1276607  349512 1137141  237365  502746  385965
  505011  892580  536178  276845 1523221 1289027 1515393  891663  224331
  239325 1593960 1144914 1316766  609535 1169629  908562  272923  470157
  201808 1113419  227478 1976750 1465526 1017339    1826  441780  453443
  200295  266409 1065875  492337  474180 1992110  604074  642890 1526545
   80522  794212  262785 1549497 1904039 1059298 1135334  675304  248547
  617976  476645 1488917 1774873 1309903 1139639  563917  432996 1591950
 1142883 2000191 1312701   82933  261145  610749  861081 1534337  266034
 1591095]

**Function to find the top 100 subthreshold SNPs for each trait**

In [4]:
trait_codes = []
with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:        
    for line in f:
        trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])

In [5]:
trait_codes_df['description'] = trait_codes_df['description'].str.replace(')', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('(', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('-', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('[', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace(']', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('+', ' ')
# trait_codes_df['description'] = trait_codes_df['description'].str.replace('  ', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace('_', ' ')
trait_codes_df['description'] = trait_codes_df['description'].str.replace(' ', '')

# trait_codes_df['description'] = trait_codes_df['description'].str.replace('/', '')

/tmp/ipykernel_139643/3393187603.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace(')', ' ')
/tmp/ipykernel_139643/3393187603.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace('(', ' ')
/tmp/ipykernel_139643/3393187603.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace('[', ' ')
/tmp/ipykernel_139643/3393187603.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace(']', ' ')
/tmp/ipykernel_139643/3393187603.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  trait_codes_df['description'] = trait_codes_df['description'].str.replace('+', ' ')

In [6]:
phenotype_list = []
not_added = []
for original_trait in trait_values:
    trait = original_trait.replace(')', ' ').replace('(', ' ').replace('-', ' ').replace('[', ' ').replace(']', ' ').replace('+', ' ').replace('_', ' ').replace(' ', '')
    if len(trait_codes_df[trait_codes_df['description']==(trait)])==1:
        phenotype_list.append(list(trait_codes_df[trait_codes_df['description']==(trait)]['phenotype'])[0])
    elif ((len(trait_codes_df[trait_codes_df['description']==(trait)])==2) & (len(trait_codes_df[(trait_codes_df['description']==(trait)) & (trait_codes_df['phenotype'].str.contains('irnt'))])==1)):
        phenotype_list.append(list(trait_codes_df[(trait_codes_df['description']==(trait)) & (trait_codes_df['phenotype'].str.contains('irnt'))]['phenotype'])[0])
    else:
        phenotype_list.append('SKIP_CT20220107')
        not_added.append(original_trait)

In [23]:
print(len(phenotype_list))

3815

In [24]:
top_100_SNPs_for_each_trait = []

In [27]:
phenotype_list[4]

'NECROVASC_FG'

In [35]:
for phenotype, trait in zip(phenotype_list[4:5], trait_values[4:5]):
    if phenotype != 'SKIP_CT20220107':
        t = time.time()
        print(trait, phenotype)
        trait_data = []
        with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/phenotypes/' + phenotype + '.gwas.imputed_v3.both_sexes/' + phenotype + '.hg38.bed.gz','r') as f:        
            for line in f:        
                trait_data.append(line.decode("utf-8").strip('\n').split('\t'))
        trait_df = pd.DataFrame(trait_data, columns=['Chromosome', 'Start', 'End', 'Reference SNP cluster ID', 'p-value'])
        trait_df['p-value'] = trait_df['p-value'].astype('float')
        trait_df = trait_df[trait_df['p-value']!=0]
        trait_df = trait_df.sort_values(['p-value']).reset_index()
        top_100_SNPs_for_each_trait.append(trait_df.iloc[:100])
        print(time.time()-t)
    else:
        top_100_SNPs_for_each_trait.append('SKIP_CT20220107')

#Other necrotizing vasculopathies (FG) NECROVASC_FG
181.69249606132507

In [40]:
trait_df[trait_df['p-value']!=0].iloc[:100]

,index,Chromosome,Start,End,Reference SNP cluster ID,p-value
9,976661,chr1,236571429,236571430,rs75511846,2.736333e-319
10,5902312,chr2,24308650,24308651,rs6744320,1.209370e-256
11,3508740,chr14,20583944,20583945,rs142227946,6.958250e-248
12,10589441,chr6,35291697,35291698,rs150457131,1.099200e-230
13,5902209,chr2,24275805,24275806,rs77507357,1.371270e-226
...,...,...,...,...,...,...
104,1753877,chr11,4999646,4999647,rs76895431,7.491240e-47
105,3938230,chr15,23645131,23645132,rs74004212,1.046520e-46
106,932653,chr1,228158538,228158539,rs549807766,1.766610e-46
107,7507769,chr22,42140283,42140284,rs183760077,2.191870e-46
108,3938231,chr15,23645132,23645133,rs2233066,2.229750e-46

In [7]:
top_100_subthreshold_snps_all_traits = []
for i in range(0, 3815, 5):
    pickle_in = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/top_100_SNPs_for_each_trait_'+str(i)+'_through_'+str(i+4)+'_CT20220110.pickle', 'rb')
    top_100_snps_5_traits=pickle.load(pickle_in)
    top_100_subthreshold_snps_all_traits.extend(top_100_snps_5_traits)

In [11]:
pickle_out = open('/home/ctrader/Hold/GWAS/pickled_subthreshold_data/top_100_SNPs_for_each_trait_all_traits_CT20220112.pickle', 'wb')
pickle.dump(top_100_subthreshold_snps_all_traits, pickle_out)
pickle_out.close()

In [70]:
top_100_subthreshold_snps_all_traits_chrm_list = []
top_100_subthreshold_snps_all_traits_start_list = []
top_100_subthreshold_snps_all_traits_end_list = []
top_100_subthreshold_snps_all_traits_pvalue_list = []
top_100_subthreshold_snps_all_traits_order_list = []
top_100_subthreshold_snps_all_traits_id_list = []
for i in range(len(top_100_subthreshold_snps_all_traits)):
    if isinstance(top_100_subthreshold_snps_all_traits[i], pd.core.frame.DataFrame):
        top_100_subthreshold_snps_all_traits_chrm_list.extend(list(top_100_subthreshold_snps_all_traits[i]['Chromosome']))
        top_100_subthreshold_snps_all_traits_start_list.extend(list(top_100_subthreshold_snps_all_traits[i]['Start']))
        top_100_subthreshold_snps_all_traits_end_list.extend(list(top_100_subthreshold_snps_all_traits[i]['End']))
        top_100_subthreshold_snps_all_traits_pvalue_list.extend(list(top_100_subthreshold_snps_all_traits[i]['p-value']))
        top_100_subthreshold_snps_all_traits_order_list.extend(list(100*i + np.arange(100)))
        top_100_subthreshold_snps_all_traits_id_list.extend(list(top_100_subthreshold_snps_all_traits[i]['Reference SNP cluster ID']))

In [71]:
#Creating a bed file for top 100 subthreshold snps for each trait
today = date.today()
bed_path_name = os.path.join('/home/ctrader/Hold/GWAS/recommendations/', 'GWAS_top_100_subthreshold_SNPs_for_each_trait_all_traits_CT' + today.strftime("%Y%m%d") + '.bed')
f= open(bed_path_name, 'w')
for i in range(len(top_100_subthreshold_snps_all_traits_chrm_list)):
    f.write(top_100_subthreshold_snps_all_traits_chrm_list[i] + '\t' + str(top_100_subthreshold_snps_all_traits_start_list[i]) + '\t' + str(top_100_subthreshold_snps_all_traits_end_list[i]) + '\t' + str(top_100_subthreshold_snps_all_traits_pvalue_list[i]) + '\t' + str(top_100_subthreshold_snps_all_traits_id_list[i]) + '\t' + str(top_100_subthreshold_snps_all_traits_order_list[i]) + '\n')
f.close()

In [217]:
trait_codes_df[trait_codes_df['description']==('3mm asymmetry angle (left)')]

,phenotype,description,variable_type,source,n_non_missing,n_missing,n_controls,n_cases,PHESANT_transformation,notes
3846,5111_irnt,3mm asymmetry angle (left),continuous_irnt,phesant,73818,287376,NA,NA,5111_0|| INTEGER || CONTINUOUS || IRNT ||,This is the asymmetric angle of keratometry re...
4120,5111_raw,3mm asymmetry angle (left),continuous_raw,phesant,73818,287376,NA,NA,5111_0|| INTEGER || CONTINUOUS || ||,This is the asymmetric angle of keratometry re...

In [224]:
list(trait_codes_df[(trait_codes_df['description']==('3mm asymmetry angle (left)')) & (trait_codes_df['phenotype'].str.contains('irnt'))]['phenotype'])[0]

'5111_irnt'

In [185]:
for trait in trait_values:
    if len(trait_codes_df[trait_codes_df['description']==(trait)])==2:

        if len(trait_codes_df[(trait_codes_df['description']==(trait)) & (trait_codes_df['phenotype'].str.contains('irnt'))])!=1:
            print(trait)

Asthma
Mesothelioma
Snoring

In [231]:
for i, j in zip(trait_values, phenotype_list):
    print(i, j)

#Arthrosis M13_ARTHROSIS
#Deforming dorsopathies M13_DEFORMDORSO
#Other joint disorders M13_OTHERJOINT
#Other necrotizing vasculopathies M13_NECROVASC
#Other necrotizing vasculopathies (FG) NECROVASC_FG
#Polyarthropathies M13_POLYARTHROPATHIES
#Spondylopathies M13_SPONDYLOPATHY
3mm asymmetry angle (left) 5111_irnt
3mm asymmetry angle (right) 5108_irnt
3mm asymmetry index (left) 5156_irnt
3mm asymmetry index (right) 5159_irnt
3mm cylindrical power (left) 5119_irnt
3mm cylindrical power (right) 5116_irnt
3mm cylindrical power angle (left) 5112_irnt
3mm cylindrical power angle (right) 5115_irnt
3mm index of best keratometry results (left) 5292
3mm index of best keratometry results (right) 5237
3mm regularity index (left) 5163_irnt
3mm regularity index (right) 5160_irnt
3mm strong meridian (left) 5135_irnt
3mm strong meridian (right) 5132_irnt
3mm strong meridian angle (left) 5104_irnt
3mm strong meridian angle (right) 5107_irnt
3mm weak meridian (left) 5096_irnt
3mm weak meridian (right) 5099_irnt
3mm weak meridian angle (left) 5103_irnt
3mm weak meridian angle (right) 5100_irnt
6mm asymmetry angle (left) 5110_irnt
6mm asymmetry angle (right) 5109_irnt
6mm asymmetry index (left) 5157_irnt
6mm asymmetry index (right) 5158_irnt
6mm cylindrical power (left) 5118_irnt
6mm cylindrical power (right) 5117_irnt
6mm cylindrical power angle (right) 5114_irnt
6mm index of best keratometry results (left) 5306
6mm index of best keratometry results (right) 5251
6mm regularity index (left) 5162_irnt
6mm regularity index (right) 5161_irnt
6mm strong meridian (left) 5134_irnt
6mm strong meridian (right) 5133_irnt
6mm strong meridian angle (left) 5105_irnt
6mm strong meridian angle (right) 5106_irnt
6mm weak meridian (left) 5097_irnt
6mm weak meridian (right) 5098_irnt
6mm weak meridian angle (right) 5101_irnt
AV-block I9_AVBLOCK
Able to confide 2110
Able to pay rent/mortgage as an adult 20525
Able to walk or cycle unaided for 10 minutes 6017
Achalasia of cardia K11_ACHAL
Actinic keratosis L12_ACTINKERA
Actions taken following self-harm: Need hospital treatment (eg A&E) 20554_3
Actions taken following self-harm: Receive help from friends / family / neighbours 20554_6
Actions taken following self-harm: See anyone from psychiatric or mental health services, including liaison services 20554_1
Actions taken following self-harm: See own GP 20554_5
Actions taken following self-harm: Use a helpline / voluntary organization 20554_4
Activities undertaken to treat anxiety: Other therapeutic activities such as mindfulness, yoga or art classes 20550_3
Activities undertaken to treat anxiety: Talking therapies, such as psychotherapy, counselling, group therapy or CBT 20550_1
Activities undertaken to treat depression: Other therapeutic activities such as mindfulness, yoga or art classes 20547_3
Activities undertaken to treat depression: Talking therapies, such as psychotherapy, counselling, group therapy or CBT 20547_1
Acute alcohol intoxication F5_ALCOHOLAC
Acute gastritis K11_ACUTGASTR
Added milk to filtered coffee 100280
Added milk to standard tea 100460
Adhesive capsulitis of shoulder M13_ADHCAPSULITIS
Adopted as a child 1767
Adopted father still alive 3912
Adopted mother still alive 3942
Adult-onset Still disease STILL_ADULT
Age angina diagnosed 3627_irnt
Age asthma diagnosed 3786_irnt
Age asthma diagnosed by doctor 22147_irnt
Age at death 40007_irnt
Age at first episode of depression 20433_irnt
Age at first live birth 2754_irnt
Age at last episode of depression 20434_irnt
Age at last live birth 2764_irnt
Age at menopause (last menstrual period) 3581_irnt
Age cataract diagnosed 4700_irnt
Age completed full time education 845
Age diabetes diagnosed 2976_irnt
Age first had sexual intercourse 2139_irnt
Age hay fever, rhinitis or eczema diagnosed 3761_irnt
Age hayfever or allergic rhinitis diagnosed by doctor 22146_irnt
Age heart attack diagnosed 3894_irnt
Age high blood pressure diagnosed 2966_irnt
Age started hormone-replacement therapy (HRT) 3536_irnt
Age started oral contraceptive pill 2794_irnt
Age started smoking in current smokers 3436_irnt
Age started smoking in former smokers 2867_irnt
Age started wearing glasses or contact lenses 2217_irnt
Age stroke diagnosed 4056_irnt
Age when last took cannabis 20455_irnt
Age when periods started (menarche) 2714
Alcohol 100022
Alcohol abuse, main dg KRA_PSY_ALCOH
Alcohol consumed 100580
Alcohol drinker status: Current 20117_2
Alcohol drinker status: Never 20117_0
Alcohol drinker status: Previous 20117_1
Alcohol intake frequency. 1558
Alcohol intake versus 10 years previously 1628
Alcohol usually taken with meals 1618
All anxiety disorders F5_ALLANXIOUS
All influenza (not pneumonia) INFLUENZA
Alzheimer’s disease AD
Amount of alcohol drunk on a typical drinking day 20403
Anaesthetics administered during delivery: Epidural or caudal anaesthetic 41219_2
Anaesthetics administered during delivery: Epidural or caudal, and spinal anaesthetic 41219_6
Anaesthetics administered during delivery: General anaesthetic 41219_1
Anaesthetics administered during delivery: Spinal anaesthetic 41219_3
Anaesthetics administered post delivery: Epidural or caudal anaesthetic 41220_2
Anaesthetics administered post delivery: General anaesthetic 41220_1
Anaesthetics administered post delivery: Spinal anaesthetic 41220_3
Ankle spacing width 3143_irnt
Ankle spacing width (left) 4100_irnt
Ankle spacing width (right) 4119_irnt
Answered sexual history questions 2129
Anxiety (asthma-related co-morbidities) PULM_ANXIETY
Anxiety disorders KRA_PSY_ANXIETY
Any ICDMAIN event in hilmo or causes of death ICDMAIN_ANY_ENTRY
Any dementia KRA_PSY_DEMENTIA
Any mental disorder KRA_PSY_ANYMENTAL
Aortic aneurysm I9_AORTANEUR
Apple intake 104450
Arm fat mass (left) 23124_irnt
Arm fat mass (right) 23120_irnt
Arm fat percentage (left) 23123_irnt
Arm fat percentage (right) 23119_irnt
Arm fat-free mass (left) 23125_irnt
Arm fat-free mass (right) 23121_irnt
Arm predicted mass (left) 23126_irnt
Arm predicted mass (right) 23122_irnt
Arterial embolism and thrombosis I9_ARTEMBTHR
Arterial embolism and thrombosis of lower extremity artery I9_ARTEMBTHRLOW
Arthropathic psoriasis L12_PSORI_ARTHRO
Asthma SKIP_CT20220107
Asthma (mode) ASTHMA_MODE
Asthma, hospital admissions 1 ASTHMA_HOSPITAL1
Asthma-related pneumonia ASTHMA_PNEUMONIA
Astigmatism angle (left) 5089_irnt
Atrophic disorders of skin L12_ATROPHICSKIN
Attempted fluid intelligence (FI) test. 4924
Attendance/disability/mobility allowance: Attendance allowance 6146_1
Attendance/disability/mobility allowance: Blue badge 6146_3
Attendance/disability/mobility allowance: Disability living allowance 6146_2
Attendance/disability/mobility allowance: None of the above 6146_100
Average 16-hour sound level of noise pollution 24023_irnt
Average 24-hour sound level of noise pollution 24024_irnt
Average daytime sound level of noise pollution 24020_irnt
Average evening sound level of noise pollution 24021_irnt
Average monthly fortified wine intake 4451
Average monthly intake of other alcoholic drinks 4462
Average monthly spirits intake 4440
Average night-time sound level of noise pollution 24022_irnt
Average total household income before tax 738
Average weekly beer plus cider intake 1588
Average weekly champagne plus white wine intake 1578
Average weekly fortified wine intake 1608
Average weekly intake of other alcoholic drinks 5364
Average weekly red wine intake 1568
Average weekly spirits intake 1598
Avoided activities or situations because of previous stressful experience in past month 20495
Background diabetic retinopathy DM_BCKGRND_RETINOPAT
Background retinopathy and retinal vascular changes H7_BCKRNDRETINOPAT
Bacon intake 103070
Bacterial intestinal infections, IBD co-morbidities IBD_BACT_INTEST_INFECTIONS
Bacterial pneumonia (organism specified) PNEUMOBACTKNOWN
Banana intake 104460
Barret oesophagus K11_BARRET
Basal metabolic rate 23105_irnt
Basophill count 30160
Basophill percentage 30220_irnt
Beef intake SKIP_CT20220107
Been in serious accident believed to be life-threatening 20526
Been involved in combat or exposed to war-zone 20527
Beer/cider intake 100710
Behavioural and miscellaneous addictions: A behaviour 20552_2
Behavioural and miscellaneous addictions: Something else not mentioned 20552_1
Behavioural syndromes associated with physiological disturbances and physical factors F5_BEHAVE
Belief that own life is meaningful 20460
Belittlement by partner or ex-partner as an adult 20521
Bell's palsy G6_BELLPA
Benign paroxysmal vertigo H8_BPV
Bilateral oophorectomy (both ovaries removed) 2834
Bipolar and major depression status: Bipolar I Disorder 20126_1
Bipolar and major depression status: Bipolar II Disorder 20126_2
Bipolar and major depression status: No Bipolar or Depression 20126_0
Bipolar and major depression status: Probable Recurrent major depression (moderate) 20126_4
Bipolar and major depression status: Probable Recurrent major depression (severe) 20126_3
Bipolar and major depression status: Single Probable major depression episode 20126_5
Birth weight 20022_irnt
Birth weight of first child 2744
Blepharochalasis H7_BLEPHAROCHALASIS
Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Asthma 6152_8
Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT) 6152_5
Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung 6152_7
Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Emphysema/chronic bronchitis 6152_6
Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema 6152_9
Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above 6152_100
Blue cheese intake 102840
Body fat percentage 23099_irnt
Body mass index (BMI) SKIP_CT20220107
Both eyes present: Yes 5182_1
Bread intake 1438_irnt
Bread type: Brown 1448_2
Bread type: Other type of bread 1448_4
Bread type: White 1448_1
Bread type: Wholemeal or wholegrain 1448_3
Breakfast cereal consumed 100760
Breastfed as a baby 1677
Breathing problems during period of job: No 22616_0
Breathing problems during period of job: Yes 22616_1
Breathing problems improved/stopped away from workplace or on holiday: No 22618_0
Breathing problems improved/stopped away from workplace or on holiday: Yes 22618_1
Breathing problems responsible for leaving job: No 22619_0
Breathing problems responsible for leaving job: Yes 22619_1
Bring up phlegm/sputum/mucus on most days 22504
Bronchitis BRONCHITIS
COPD differential diagnosis COPD_EXCL
COPD related to chronic (opportunist) infections COPD_OPPORTUNIST_INFECTIONS
COPD, early/later onset COPD_EARLYANDLATER
Caffeine drink within last hour 3089
Cake intake 102190
Calcium 100024_irnt
Campylobacter enteritis CAMPYLOENTERITIS
Cancer code, self-reported: basal cell carcinoma 20001_1061
Cancer code, self-reported: bladder cancer 20001_1035
Cancer code, self-reported: brain cancer / primary malignant brain tumour 20001_1032
Cancer code, self-reported: chronic lymphocytic 20001_1055
Cancer code, self-reported: colon cancer/sigmoid cancer 20001_1022
Cancer code, self-reported: eye and/or adnexal cancer 20001_1030
Cancer code, self-reported: hodgkins lymphoma / hodgkins disease 20001_1052
Cancer code, self-reported: kidney/renal cell cancer 20001_1034
Cancer code, self-reported: large bowel cancer/colorectal cancer 20001_1020
Cancer code, self-reported: larynx/throat cancer 20001_1006
Cancer code, self-reported: leukaemia 20001_1048
Cancer code, self-reported: liver/hepatocellular cancer 20001_1024
Cancer code, self-reported: lung cancer 20001_1001
Cancer code, self-reported: malignant melanoma 20001_1059
Cancer code, self-reported: multiple myeloma 20001_1050
Cancer code, self-reported: non-hodgkins lymphoma 20001_1053
Cancer code, self-reported: non-melanoma skin cancer 20001_1060
Cancer code, self-reported: oesophageal cancer 20001_1017
Cancer code, self-reported: primary bone cancer 20001_1063
Cancer code, self-reported: rectal cancer 20001_1023
Cancer code, self-reported: rodent ulcer 20001_1073
Cancer code, self-reported: sarcoma/fibrosarcoma 20001_1068
Cancer code, self-reported: skin cancer 20001_1003
Cancer code, self-reported: small intestine/small bowel cancer 20001_1019
Cancer code, self-reported: squamous cell carcinoma 20001_1062
Cancer code, self-reported: stomach cancer 20001_1018
Cancer code, self-reported: thyroid cancer 20001_1065
Cancer code, self-reported: tongue cancer 20001_1011
Cancer code, self-reported: unclassifiable 20001_99999
Cancer diagnosed by doctor 2453
Cancer year/age first occurred 84_irnt
Carbohydrate 100005_irnt
Cardiac arrhytmias, COPD co-morbidities CARDIAC_ARRHYTM
Cardiomyopathies, Primary/intrinsic I9_CARDMPRI
Cardiomyopathy I9_CARDMYO
Cardiomyopathy, other and unspecified I9_CARDMYOOTH
Carotene 100019_irnt
Carpal tunnel syndrome G6_CARPTU
Cascot confidence score 20121_irnt
Cereal intake 1458
Cereal type: Biscuit cereal (e.g. Weetabix) 1468_2
Cereal type: Bran cereal (e.g. All Bran, Branflakes) 1468_1
Cereal type: Muesli 1468_4
Cereal type: Oat cereal (e.g. Ready Brek, porridge) 1468_3
Cereal type: Other (e.g. Cornflakes, Frosties) 1468_5
Cerebral aneurysm, nonruptured I9_ANEURYSM
Cerebral palsy and other paralytic syndromes G6_CPETAL
Certain infectious and parasitic diseases SKIP_CT20220107
Cervicalgia M13_CERVICALGIA
Chalazion H7_CHALAZION
Cheese consumers 102800
Cheese intake 1408
Chest pain felt during physical activity 6015
Chest pain felt outside physical activity 6016
Chest pain or discomfort 2335
Chest pain or discomfort when walking uphill or hurrying 3751
Childhood allergy (age < 16) CHILDHOOD_ALLERGY
Childhood asthma (age<16) ASTHMA_CHILD
Childhood sunburn occasions 1737
Chirrosis of liver, NAS CHIRHEP_NAS
Cholangitis (sclerosing) K11_CHOLANGI
Chron's disease NAS CHRONNAS
Chrondropathies M13_CHRONDROPATHIES
Chronic gastritis K11_CHRONGASTR
Chronic pancreatitis K11_CHRONPANC
Chronic suppurative otitis media H8_CHRON_SUPOTITIS
Chrystal arthropathies, rheuma endpoint RHEUMA_CHRYSTAL
Close to major road 24014
Coeliac disease K11_COELIAC
Coffee consumed 100240
Coffee intake 1498
Coffee type: Decaffeinated coffee (any type) 1508_1
Coffee type: Ground coffee (include espresso, filter etc) 1508_3
Coffee type: Instant coffee 1508_2
Coffee type: Other type of coffee 1508_4
Comparative body size at age 10 1687
Comparative height size at age 10 1697
Completion status of test: Fully completed 6020_1
Completion status of test: Heart rate reached safety level 6020_33
Completion status of test: Incomplete - other reason 6020_34
Completion status of test: Participant reported chest-pain and/or other discomfort 6020_32
Completion status of test: Participant wanted to stop early 6020_31
Concussion G6_CONCUS
Conduction disorders I9_CONDUCTIO
Conductive and sensorineural hearing loss H8_CONSENHEARINGLOSS
Conductive hearing loss, unspecified H8_HL_CON_NAS
Congenital malformations of heart and great arteries CONGEN_HEART_ARTER
Congenital malformations, deformations and chromosomal abnormalities XVII_MALFORMAT_ABNORMAL
Consecutive night shifts during mixed shift periods 22644_irnt
Convergent concomitant strabismus H7_CONVERSTRAB
Cooked vegetable intake 1289
Corneal hysteresis (left) 5264_irnt
Corneal hysteresis (right) 5256_irnt
Corneal resistance factor (left) 5265_irnt
Corneal resistance factor (right) 5257_irnt
Corneal ulcer H7_CORNULCER
Coronary atherosclerosis I9_CORATHER
Cough on most days 22502
Coxarthrosis [arthrosis of hip](FG) COX_ARTHROSIS
Creatinine (enzymatic) in urine 30510_irnt
Crisp intake 102460
Crohn's disease of large intestine CHRONLARGE
Crohn's disease of small interstine CHRONSMALL
Cucumber intake 104210
Current employment status: Doing unpaid or voluntary work 6142_6
Current employment status: Full or part-time student 6142_7
Current employment status: Looking after home and/or family 6142_3
Current employment status: None of the above 6142_100
Current employment status: Retired 6142_2
Current employment status: Unable to work because of sickness or disability 6142_4
Current employment status: Unemployed 6142_5
Current eye infection 5183
Current tobacco smoking 1239
Cylindrical power (left) 5086_irnt
Cylindrical power (right) 5087_irnt
DVT of lower extremities I9_PHLETHROMBDVTLOW
DVT of lower extremities and pulmonary embolism I9_DVTANDPULM
Dark chocolate intake 102290
Day shifts worked: Shift pattern was worked for some (but not all) of job 22630_0
Day shifts worked: Shift pattern was worked for whole of job 22630_1
Day-of-week questionnaire completion requested: Friday 20079_5
Day-of-week questionnaire completion requested: Saturday 20079_6
Day-of-week questionnaire completion requested: Sunday 20079_7
Day-of-week questionnaire completion requested: Thursday 20079_4
Day-of-week questionnaire completion requested: Tuesday 20079_2
Day-of-week questionnaire completion requested: Wednesday 20079_3
Daytime dozing / sleeping (narcolepsy) 1220
Death due to cardiac causes I9_K_CARDIAC
Decaffeinated coffee 100360
Deformity of finger(s) M13_FINGERDEFORM
Degeneration of macula and posterior pole H7_MACULADEGEN
Delivery methods: Elective caesarean section 41221_7
Delivery methods: Emergency caesarean section 41221_8
Delivery methods: Low forceps, not breech 41221_2
Delivery methods: Other forceps, not breech 41221_3
Delivery methods: Other than those specified above 41221_9
Delivery methods: Spontaneous other cephalic 41221_1
Delivery methods: Spontaneous vertex 41221_0
Delivery methods: Ventouse, vacuum extraction 41221_4
Dementia F5_DEMENTIA
Demyelenating diseases of the central nervous system G6_DEMYEL
Depression F5_DEPRESSIO
Depression possibly related to childbirth 20445
Depression possibly related to stressful or traumatic event 20447
Dessert consumers 102130
Destinations on discharge from hospital (recoded): High security psychiatric hospital: NHS 41248_3001
Destinations on discharge from hospital (recoded): Nursing, residential care, group home: Local Authoritory 41248_7002
Destinations on discharge from hospital (recoded): Nursing, residential care, group home: NHS 41248_7001
Destinations on discharge from hospital (recoded): Nursing, residential care, group home: Non-NHS 41248_7003
Destinations on discharge from hospital (recoded): Other hospital: Non-NHS 41248_8002
Destinations on discharge from hospital (recoded): Temporary place of residence 41248_2000
Destinations on discharge from hospital (recoded): Transfer to other NHS provider 41248_5000
Destinations on discharge from hospital (recoded): Transfer to other NHS provider: General ward, young physically disabled, A&E 41248_5001
Destinations on discharge from hospital (recoded): Transfer to other NHS provider: Psychiatry, learning disabilities 41248_5003
Destinations on discharge from hospital (recoded): Transfer within NHS provider 41248_6000
Destinations on discharge from hospital (recoded): Transfer within NHS provider: Geriatrics 41248_6007
Destinations on discharge from hospital (recoded): Transfer within NHS provider: Medical specialty 41248_6005
Destinations on discharge from hospital (recoded): Transfer within NHS provider: Surgical specialty 41248_6004
Destinations on discharge from hospital (recoded): Usual Place of residence 41248_1000
Destinations on discharge from hospital (recoded): Usual Place of residence: Living alone 41248_1002
Destinations on discharge from hospital (recoded): Usual Place of residence: Living with relatives 41248_1001
Detention categories: Formally detained under Part II, Mental Health Act 1983 41215_1
Detention categories: Informal, not formally detained 41215_0
Diabetes diagnosed by doctor 2443
Diabetic hypoglycemia DM_HYPOGLYC
Diabetic ketoacidosis DM_KETOACIDOSIS
Diagnoses - main ICD10: A04 Other bacterial intestinal infections A04

Diagnoses - main ICD10: Z45 Adjustment and management of implanted device Z45
Diagnoses - main ICD10: Z46 Fitting and adjustment of other devices Z46
Diagnoses - main ICD10: Z47 Other orthopaedic follow-up care Z47
Diagnoses - main ICD10: Z48 Other surgical follow-up care Z48
Diagnoses - main ICD10: Z50 Care involving use of rehabilitation procedures Z50
Diagnoses - main ICD10: Z51 Other medical care Z51
Diagnoses - main ICD10: Z52 Donors of organs and tissues Z52
Diagnoses - main ICD10: Z53 Persons encountering health services for specifie procedures, not carried out Z53
Diagnoses - main ICD10: Z71 Persons encountering health services for other counselling and medical advice, not elsewhere classified Z71
Diagnoses - main ICD10: Z76 Persons encountering health services in other circumstances Z76
Diagnoses - main ICD10: Z80 Family history of malignant neoplasm Z80
Diagnoses - main ICD10: Z85 Personal history of malignant neoplasm Z85
Diagnoses - main ICD10: Z87 Personal history of other diseases and conditions Z87
Diastolic blood pressure, automated reading 4079_irnt
Diastolic blood pressure, manual reading 94_irnt
Did your sleep change? 20532
Difference in mobile phone use compared to two years previously 1140
Difficulty concentrating during worst depression 20435
Difficulty concentrating during worst period of anxiety 20419
Difficulty not smoking for 1 day 3476
Difficulty stopping worrying during worst period of anxiety 20541
Diffuse brain injury G6_DIFBRAININJ
Diplopia H7_DIPLOPIA
Diseases of appendix K11_APPENDIX
Diseases of liver K11_LIVER
Diseases of peritoneum K11_PERITON
Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism III_BLOOD_IMMUN
Diseases of the circulatory system IX_CIRCULATORY
Diseases of the digestive system XI_DIGESTIVE
Diseases of the ear and mastoid process VIII_EAR_MASTOID
Diseases of the eye and adnexa VII_EYE_ADNEXA
Diseases of the genitourinary system XIV_GENITOURINARY
Diseases of the musculoskeletal system and connective tissue XIII_MUSCULOSKELET
Diseases of the myoneural junction and muscle G6_MYONEU
Diseases of the nervous system VI_NERVOUS
Diseases of the respiratory system X_RESPIRATORY
Diseases of the skin and subcutaneous tissue XII_SKIN_SUBCUTAN
Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified I9_DISVEINLYMPH
Disorders of brain, other and unspecified G6_DISBROTHUNS
Disorders of gallbladder, biliary tract and pancreas K11_GALLBILPANC
Disorders of lacrimal system H7_LACRIMALSYSTEM
Disorders of lens H7_LENS
Disorders of muscles M13_MUSCLE
Disorders of refraction and accommodation H7_REFRAACCOMMODIS
Disorders of synovium and tendon M13_SYNOTEND
Disorders of vestibular function (Vertigo) H8_VERTIGO
Disorders of vitreous body H7_VITRBODYGLOBE
Dissection of aorta I9_AORTDIS
Distance between home and job workplace 796_irnt
Divergent concomitant strabismus H7_DIVERGSTRAB
Doctor diagnosed COPD (chronic obstructive pulmonary disease) 22130
Doctor diagnosed asthma 22127
Doctor diagnosed bronchiectasis 22134
Doctor diagnosed chronic bronchitis 22129
Doctor diagnosed emphysema 22128
Doctor diagnosed hayfever or allergic rhinitis 22126
Doctor diagnosed lung cancer (not mesothelioma) 22140
Doctor diagnosed sarcoidosis 22133
Doctor diagnosed tuberculosis 22137
Dorsalgia M13_DORSALGIA
Dried fruit intake 1319
Drinking water intake 100150
Drive faster than motorway speed limit 1100
Duration of light DIY 1021
Duration of moderate activity 894
Duration of strenuous sports 1001
Duration of vigorous activity 914_irnt
Duration of walks 874_irnt
Duration screen displayed 4290_irnt
Duration to first press of snap-button in each round 404_irnt
Duration walking for pleasure 981
ECG, heart rate 5983_irnt
ECG, load 5984_irnt
ECG, phase time 5986_irnt
Ease of skin tanning 1727
Ectropion of eyelid H7_ECTROPION
Egg consumers 102930
Endocarditis I9_ENDOCARD
Endocrine, nutritional and metabolic diseases IV_ENDOCRIN_NUTRIT
Endometriosis of ovary ENDOMETRIOSIS_OVARY
Endometriosis of pelvic peritoneum ENDOMETRIOSIS_PELVICPERITONEUM
Endometriosis of uterus ENDOMETRIOSIS_UTERUS
Endometriosis, IBD co-morbidity IBD_ENDOMETRIOSIS
Energy 100002_irnt
Englyst dietary fibre 100009_irnt
Enterocolitis due to Clostridium difficile C_DIFFICILE_ENTEROCOLITIS
Enthesopathies of lower limb, excluding foot M13_ENTESOPATHYLOW
Entropion and trichiasis of eyelid H7_ENTROPION
Eosinophill count 30150
Eosinophill percentage 30210_irnt
Epiphora H7_EPIPHORA
Episodal and paroxysmal disorders G6_EPIPAROX
Ever addicted to a behaviour or miscellanous 20431
Ever addicted to alcohol 20406
Ever addicted to any substance or behaviour 20401
Ever addicted to illicit or recreational drugs 20456
Ever addicted to prescription or over-the-counter medication 20503
Ever been injured or injured someone else through drinking alcohol: No 20411_0
Ever been injured or injured someone else through drinking alcohol: Yes, but not in the last year 20411_1
Ever been injured or injured someone else through drinking alcohol: Yes, during the last year 20411_2
Ever believed in an un-real conspiracy against self 20468
Ever believed in un-real communications or signs 20474
Ever contemplated self-harm 20485
Ever depressed for a whole week 4598
Ever had bowel cancer screening 2345
Ever had cataract surgery: Both eyes 5324_4
Ever had cataract surgery: Left eye only 5324_3
Ever had cataract surgery: Right eye only 5324_2
Ever had corneal graft surgery: No 5328_0
Ever had eye surgery 5181
Ever had hysterectomy (womb removed) 3591
Ever had known person concerned about, or recommend reduction of, alcohol consumption: No 20405_0
Ever had known person concerned about, or recommend reduction of, alcohol consumption: Yes, but not in the last year 20405_1
Ever had known person concerned about, or recommend reduction of, alcohol consumption: Yes, during the last year 20405_2
Ever had laser treatment for glaucoma or high eye pressure: Both eyes 5327_4
Ever had laser treatment for glaucoma or high eye pressure: No 5327_0
Ever had period extreme irritability 20502
Ever had period of mania / excitability 20501
Ever had prolonged loss of interest in normal activities 20441
Ever had prostate specific antigen (PSA) test 2365
Ever had refractive laser eye surgery: Both eyes 5325_4
Ever had refractive laser eye surgery: Left eye only 5325_3
Ever had refractive laser eye surgery: No 5325_0
Ever had refractive laser eye surgery: Right eye only 5325_2
Ever had same-sex intercourse 2159
Ever heard an un-real voice 20463
Ever highly irritable/argumentative for 2 days 4653
Ever manic/hyper for 2 days 4642
Ever prescribed a medication for unusual or psychotic experiences 20466
Ever seen an un-real vision 20471
Ever self-harmed 20480
Ever smoked 20160
Ever sought or received professional help for mental distress 20499
Ever stopped smoking for 6+ months 2907
Ever suffered mental distress preventing usual activities 20500
Ever taken cannabis 20453
Ever talked to a health professional about unusual or psychotic experiences 20477
Ever thought that life not worth living 20479
Ever tried to stop smoking 3486
Ever unenthusiastic/disinterested for a whole week 4631
Ever used hormone-replacement therapy (HRT) 2814
Ever worried more than most people would in similar situation 20425
Exposure to tobacco smoke at home 1269
Exposure to tobacco smoke outside home 1279
External causes of morbidity and mortality XX_EXTERNAL_MORB_MORT
Extrapyramidal and movement disorders G6_XTRAPYR
Eye problems/disorders: Cataract 6148_4
Eye problems/disorders: Diabetes related eye disease 6148_1
Eye problems/disorders: Glaucoma 6148_2
Eye problems/disorders: Injury or trauma resulting in loss of vision 6148_3
Eye problems/disorders: Macular degeneration 6148_5
Eye problems/disorders: None of the above 6148_100
Eye problems/disorders: Other serious eye condition 6148_6
FI1 : numeric addition test 4935
FI10 : arithmetic sequence recognition 5699
FI13 : subset inclusion logic 5866
FI2 : identify largest number 4946
FI3 : word interpolation 4957
FI4 : positional arithmetic 4968
FI6 : conditional arithmetic 4990
FI7 : synonym 5001
FI8 : chained arithmetic 5012
Facial ageing 1757
Fat 100004_irnt
Fat removed from meat 103120
Father still alive 1797
Father's age at death 1807_irnt
Fed-up feelings 1960
Feelings of tiredness during worst episode of depression 20449
Felt distant from other people in past month 20496
Felt hated by family member as a child 20487
Felt irritable or had angry outbursts in past month 20494
Felt very upset when reminded of stressful experience in past month 20498
Fibroblastic disorders M13_FIBROBLASTIC
Fibromyalgia related co-morbidities FIBRO_COMORB
Filtered coffee intake 100270
Final attempt correct: abandon 4294_9
Final attempt correct: no 4294_0
Final attempt correct: yes 4294_1
Fizzy drink intake 100170
Fluid intelligence score 20016_irnt
Folate 100014_irnt
Follicular lymphoma C_FOLLICULAR_LYMPHOMA
Food weight 100001_irnt
Forced expiratory volume in 1-second (FEV1) 3063_irnt
Forced expiratory volume in 1-second (FEV1), Best measure 20150_irnt
Forced expiratory volume in 1-second (FEV1), predicted 20153_irnt
Forced expiratory volume in 1-second (FEV1), predicted percentage 20154_irnt
Forced vital capacity (FVC) 3062_irnt
Forced vital capacity (FVC), Best measure 20151_irnt
Foreign body granuloma of skin and subcutaneous tissue L12_FOREIGNBODYGRANULOMA
Former alcohol drinker 3731
Fortified wine intake 100720
Fractured bone site(s): Ankle 6151_1
Fractured bone site(s): Arm 6151_6
Fractured bone site(s): Hip 6151_3
Fractured bone site(s): Leg 6151_2
Fractured bone site(s): Other bones 6151_7
Fractured bone site(s): Spine 6151_4
Fractured bone site(s): Wrist 6151_5
Fractured heel 3082
Fractured/broken bones in last 5 years 2463
Frequency of consuming six or more units of alcohol 20416
Frequency of depressed mood in last 2 weeks 2050
Frequency of difficulty controlling worry during worst period of anxiety 20537
Frequency of drinking alcohol 20414
Frequency of failure to fulfil normal expectations due to drinking alcohol in last year 20407
Frequency of feeling guilt or remorse after drinking alcohol in last year 20409
Frequency of friend/family visits 1031
Frequency of inability to cease drinking in last year 20413
Frequency of light DIY in last 4 weeks 1011
Frequency of memory loss due to drinking alcohol in last year 20408
Frequency of needing morning drink of alcohol after heavy drinking session in last year 20412
Frequency of other exercises in last 4 weeks 3637
Frequency of solarium/sunlamp use 2277
Frequency of stair climbing in last 4 weeks 943
Frequency of tenseness / restlessness in last 2 weeks 2070
Frequency of tiredness / lethargy in last 2 weeks 2080
Frequency of unenthusiasm / disinterest in last 2 weeks 2060
Frequency of unusual or psychotic experiences in past year 20467
Frequency of walking for pleasure in last 4 weeks 971
Frequent trouble falling or staying asleep during worst period of anxiety 20427
Fresh fruit intake 1309
Fried potatoes intake 104020
Friendships satisfaction 4570
GI-bleeding K11_GIBLEEDING
Ganglion M13_GANGLION
Gap coding: Looking after the home and/or family 22660_105
Gap coding: Paid work for less than 15 hours per week on average or lasting less than 6 months 22660_101
Gap coding: Retired 22660_108
Gap coding: Unable to work due to sickness or disability 22660_106
Gap coding: Unemployed 22660_107
Gap coding: Unpaid or voluntary work 22660_102
Gas or solid-fuel cooking/heating: A gas fire that you use regularly in winter time 6139_2
Gas or solid-fuel cooking/heating: An open solid fuel fire that you use regularly in winter time 6139_3
Gastroduodenal ulcer K11_GASTRODUOULC
General happiness 20458
General happiness with own health 20459
General pain for 3+ months 2956
Gestational diabetes only 4041
Getting up in morning 1170
Giant cell arteritis M13_GIANTCELL
Glaucoma suspect H7_GLAUCSUSP
Glomerular diseases N14_GLOMERULAR
Glomerulonephritis GLOMER_NEPHRITIS
Gonarthrosis [arthrosis of knee](FG) KNEE_ARTHROSIS
Gout, FINNGEN GOUT
Gout, unspecified GOUT_NOS
Granulomatous disorders of skin and subcutaneous tissue L12_GRANULOMATOUSSKIN
Guillain-Barre syndrome G6_GUILBAR
Guilty feelings 2030
Had major operations 2415
Had menopause 2724
Had other major operations 2844
Haematocrit percentage 30030_irnt
Haemoglobin concentration 30020_irnt
Hair colour (natural, before greying): Black 1747_5
Hair colour (natural, before greying): Blonde 1747_1
Hair colour (natural, before greying): Dark brown 1747_4
Hair colour (natural, before greying): Light brown 1747_3
Hair colour (natural, before greying): Other 1747_6
Hair colour (natural, before greying): Red 1747_2
Hair/balding pattern: Pattern 1 2395_1
Hair/balding pattern: Pattern 2 2395_2
Hair/balding pattern: Pattern 3 2395_3
Hair/balding pattern: Pattern 4 2395_4
Hallux rigidus M13_HALLUXRIGIDUS
Hallux valgus (acquired) M13_HALLUXVALGUS
Hand grip strength (left) 46_irnt
Hand grip strength (right) 47_irnt
Handedness (chirality/laterality): Left-handed 1707_2
Handedness (chirality/laterality): Right-handed 1707_1
Handedness (chirality/laterality): Use both right and left hands equally 1707_3
Hands-free device/speakerphone use with mobile phone in last 3 month 1130
Happiness 4526
Hard cheese intake 102820
Headaches for 3+ months 3799
Health satisfaction 4548
Hearing aid user 3393
Hearing difficulty/problems with background noise 2257
Hearing difficulty/problems: No 2247_0
Hearing difficulty/problems: Yes 2247_1
Hearing test done: I can only hear on the left side 4849_12
Hearing test done: I can only hear on the right side 4849_11
Hearing test done: No, I am unable to do this 4849_0
Hearing test done: Yes 4849_1
Heart failure HEARTFAIL
Heart failure, not strict I9_HEARTFAIL_NS
Heart failure,strict I9_HEARTFAIL
Heating type(s) in home: Electric storage heaters 6140_2
Heating type(s) in home: Gas central heating 6140_1
Heating type(s) in home: None of the above 6140_100
Heating type(s) in home: Oil (kerosene) central heating 6140_3
Heating type(s) in home: Open fire without central heating 6140_6
Heating type(s) in home: Portable gas or paraffin heaters 6140_4
Heating type(s) in home: Solid fuel central heating 6140_5
Heel Broadband ultrasound attenuation, direct entry 3144_irnt
Heel bone mineral density (BMD) 3148_irnt
Heel bone mineral density (BMD) (left) 4105_irnt
Heel bone mineral density (BMD) (right) 4124_irnt
Heel bone mineral density (BMD) T-score, automated 78_irnt
Heel bone mineral density (BMD) T-score, automated (left) 4106_irnt
Heel bone mineral density (BMD) T-score, automated (right) 4125_irnt
Heel broadband ultrasound attenuation (left) 4101_irnt
Heel broadband ultrasound attenuation (right) 4120_irnt
Heel quantitative ultrasound index (QUI), direct entry 3147_irnt
Heel quantitative ultrasound index (QUI), direct entry (left) 4104_irnt
Heel quantitative ultrasound index (QUI), direct entry (right) 4123_irnt
Hernia K11_HERNIA
Hidradenitis suppurativa L12_HIDRADENITISSUP
High light scatter reticulocyte count 30300_irnt
High light scatter reticulocyte percentage 30290_irnt
Hip circumference 49_irnt
Hip pain for 3+ months 3414
History of psychiatric care on admission: One or more previous psychiatric episodes with another Health Care Provider 41218_2
History of psychiatric care on admission: One or more previous psychiatric episodes with this Health Care Provider 41218_1
Hodgkin lymphoma C_HODGKIN_LYMPHOMA
Home area population density - urban or rural: England/Wales - Hamlet and Isolated Dwelling - less sparse 20118_8
Home area population density - urban or rural: England/Wales - Town and Fringe - less sparse 20118_6
Home area population density - urban or rural: England/Wales - Urban - less sparse 20118_5
Home area population density - urban or rural: England/Wales - Village - less sparse 20118_7
Home area population density - urban or rural: Scotland - Accessible Rural 20118_16
Home area population density - urban or rural: Scotland - Accessible Small Town 20118_13
Home area population density - urban or rural: Scotland - Large Urban Area 20118_11
Home area population density - urban or rural: Scotland - Other Urban Area 20118_12
Home location - east co-ordinate (rounded) 22702_irnt
Home location - north co-ordinate (rounded) 22704_irnt
Home location at assessment - east co-ordinate (rounded) 20074_irnt
Home location at assessment - north co-ordinate (rounded) 20075_irnt
Hordeolum and other deep inflammation of eyelid H7_HORDEOLUM
Hospital episode type: General episode 41231_1
Hot drink temperature 1518
How are people in household related to participant: Brother and/or sister 6141_3
How are people in household related to participant: Grandchild 6141_6
How are people in household related to participant: Grandparent 6141_5
How are people in household related to participant: Husband, wife or partner 6141_1
How are people in household related to participant: Mother and/or father 6141_4
How are people in household related to participant: Other related 6141_7
How are people in household related to participant: Other unrelated 6141_8
Hydrocephalus G6_HYDROCEPH
Hypergammalglobulinemia, unspecified D3_HYPERGAMMAGLONAS
Hypertension I9_HYPTENS
Hypertension complicating pregnancy, childbirth, and the puerperium I9_HYPTENSPREG
Hypertensive diseases I9_HYPERTENSION
Hypertensive heart and/or renal disease I9_HYPTENSHR
Hypertrophic disorders of skin L12_HYPERTROPHICSKIN
Hypertrophic scar L12_HYPETROPHICSCAR
Hypothyroidism (congenital or acquired) HYPOTHYROIDISM
Hypothyroidism,other/unspecified E4_HYTHYNAS
ILD differential diagnosis ILD_DIFF_DG
Idiopathic pulmonary fibrosis (attempt to specificity) IPF
Idiopathic thrombocytopenic purpura D3_ITP
Illness, injury, bereavement, stress in last 2 years: Death of a spouse or partner 6145_4
Illness, injury, bereavement, stress in last 2 years: Financial difficulties 6145_6
Illness, injury, bereavement, stress in last 2 years: Marital separation/divorce 6145_5
Illness, injury, bereavement, stress in last 2 years: None of the above 6145_100
Illness, injury, bereavement, stress in last 2 years: Serious illness, injury or assault to yourself 6145_1
Illnesses of adopted father: Alzheimer's disease/dementia 20112_10
Illnesses of adopted father: Bowel cancer 20112_4
Illnesses of adopted father: Chronic bronchitis/emphysema 20112_6
Illnesses of adopted father: Diabetes 20112_9
Illnesses of adopted father: Heart disease 20112_1
Illnesses of adopted father: High blood pressure 20112_8
Illnesses of adopted father: Lung cancer 20112_3
Illnesses of adopted father: None of the above (group 2) 20112_101
Illnesses of adopted father: Prostate cancer 20112_13
Illnesses of adopted father: Stroke 20112_2
Illnesses of adopted mother: Alzheimer's disease/dementia 20113_10
Illnesses of adopted mother: Bowel cancer 20113_4
Illnesses of adopted mother: Breast cancer 20113_5
Illnesses of adopted mother: Chronic bronchitis/emphysema 20113_6
Illnesses of adopted mother: Diabetes 20113_9
Illnesses of adopted mother: Heart disease 20113_1
Illnesses of adopted mother: High blood pressure 20113_8
Illnesses of adopted mother: Lung cancer 20113_3
Illnesses of adopted mother: None of the above (group 1) 20113_100
Illnesses of adopted mother: Severe depression 20113_12
Illnesses of adopted mother: Stroke 20113_2
Illnesses of adopted siblings: Diabetes 20114_9
Illnesses of adopted siblings: Heart disease 20114_1
Illnesses of adopted siblings: High blood pressure 20114_8
Illnesses of adopted siblings: None of the above (group 2) 20114_101
Illnesses of adopted siblings: Severe depression 20114_12
Illnesses of father: Alzheimer's disease/dementia 20107_10
Illnesses of father: Bowel cancer 20107_4
Illnesses of father: Chronic bronchitis/emphysema 20107_6
Illnesses of father: Diabetes 20107_9
Illnesses of father: Heart disease 20107_1
Illnesses of father: High blood pressure 20107_8
Illnesses of father: Lung cancer 20107_3
Illnesses of father: None of the above (group 1) 20107_100

Malignant neoplasm of small intestine SKIP_CT20220107
Malignant neoplasm of stomach SKIP_CT20220107
Malignant neoplasm of testis SKIP_CT20220107
Malignant neoplasm of thyroid gland SKIP_CT20220107
Malignant neoplasm of tonsil SKIP_CT20220107
Malignant neoplasm of urinary organs C3_URINARY_TRACT
Malignant neoplasm, without specification of site SKIP_CT20220107
Manic/hyper symptoms: All of the above 6156_15
Manic/hyper symptoms: I needed less sleep than usual 6156_13
Manic/hyper symptoms: I was more creative or had more ideas than usual 6156_14
Manifestations of mania or irritability: I needed less sleep than usual 20548_5
Manifestations of mania or irritability: I was easily distracted 20548_7
Manifestations of mania or irritability: I was more active than usual 20548_9
Manifestations of mania or irritability: I was more confident than usual 20548_8
Manifestations of mania or irritability: I was more creative or had more ideas than usual 20548_6
Manifestations of mania or irritability: I was more restless than usual 20548_2
Manifestations of mania or irritability: I was more talkative than usual 20548_1
Manifestations of mania or irritability: My thoughts were racing 20548_3
Maternal smoking around birth 1787
Mature T/NK-cell lymphomas C_TNK_LYMPHOMA
Maximum digits remembered correctly 4282
Maximum frequency of taking cannabis 20454
Maximum heart rate during fitness test 6033_irnt
Maximum workload during fitness test 6032_irnt
Mean corpuscular haemoglobin 30050_irnt
Mean corpuscular haemoglobin concentration 30060_irnt
Mean corpuscular volume 30040_irnt
Mean platelet (thrombocyte) volume 30100_irnt
Mean reticulocyte volume 30260_irnt
Mean signal-to-noise ratio (SNR), (left) 4233_irnt
Mean signal-to-noise ratio (SNR), (right) 4244_irnt
Mean sphered cell volume 30270_irnt
Mean time to correctly identify matches 20023_irnt
Meat consumers 103000
Medication for cholesterol, blood pressure or diabetes: Blood pressure medication 6177_2
Medication for cholesterol, blood pressure or diabetes: Cholesterol lowering medication 6177_1
Medication for cholesterol, blood pressure or diabetes: Insulin 6177_3
Medication for cholesterol, blood pressure or diabetes: None of the above 6177_100
Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Blood pressure medication 6153_2
Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Cholesterol lowering medication 6153_1
Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Hormone replacement therapy 6153_4
Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Insulin 6153_3
Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: None of the above 6153_100
Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Oral contraceptive pill or minipill 6153_5
Medication for pain relief, constipation, heartburn: Aspirin 6154_1
Medication for pain relief, constipation, heartburn: Ibuprofen (e.g. Nurofen) 6154_2
Medication for pain relief, constipation, heartburn: Laxatives (e.g. Dulcolax, Senokot) 6154_6
Medication for pain relief, constipation, heartburn: None of the above 6154_100
Medication for pain relief, constipation, heartburn: Omeprazole (e.g. Zanprol) 6154_5
Medication for pain relief, constipation, heartburn: Paracetamol 6154_3
Medication for pain relief, constipation, heartburn: Ranitidine (e.g. Zantac) 6154_4
Medication related adverse effects ASTHMA_MEDICATIO_COMORB
Medication related adverse effects (Asthma/COPD) PULM_MEDICATIO_COMORB
Melignant neoplasm of mesothelium and soft tissue C3_MESTOTHEL_SOFTTISSUE
Memory loss MEMLOSS
Meningitis MENINGITIS
Meniscus derangement M13_MENISCUSDERANGEMENTS
Mental and behavioural disorders V_MENTAL_BEHAV
Mental health problems ever diagnosed by a professional: A personality disorder 20544_4
Mental health problems ever diagnosed by a professional: Agoraphobia 20544_17
Mental health problems ever diagnosed by a professional: Anorexia nervosa 20544_16
Mental health problems ever diagnosed by a professional: Anxiety, nerves or generalized anxiety disorder 20544_15
Mental health problems ever diagnosed by a professional: Any other phobia (eg disabling fear of heights or spiders) 20544_5
Mental health problems ever diagnosed by a professional: Any other type of psychosis or psychotic illness 20544_3
Mental health problems ever diagnosed by a professional: Autism, Asperger's or autistic spectrum disorder 20544_14
Mental health problems ever diagnosed by a professional: Bulimia nervosa 20544_12
Mental health problems ever diagnosed by a professional: Depression 20544_11
Mental health problems ever diagnosed by a professional: Mania, hypomania, bipolar or manic-depression 20544_10
Mental health problems ever diagnosed by a professional: Obsessive compulsive disorder (OCD) 20544_7
Mental health problems ever diagnosed by a professional: Panic attacks 20544_6
Mental health problems ever diagnosed by a professional: Psychological over-eating or binge-eating 20544_13
Mental health problems ever diagnosed by a professional: Schizophrenia 20544_2
Mental health problems ever diagnosed by a professional: Social anxiety or social phobia 20544_1
Mesothelioma SKIP_CT20220107
Methods of self-harm used: Ingesting a medication in excess of the normal dose 20553_4
Methods of self-harm used: Ingesting alcohol or a recreational or illicit drug 20553_6
Methods of self-harm used: Self-injury such as self-cutting, scratching or hitting, etc. 20553_5
Methods of self-harm used: Something not listed 20553_1
Methods of self-harm used: Stopping prescribed medication 20553_3
Microalbumin in urine 30500_irnt
Milk added to cereal 100890
Milk chocolate intake 102280
Milk intake 100520
Milk type used: Full cream 1418_1
Milk type used: Never/rarely have milk 1418_6
Milk type used: Other type of milk 1418_5
Milk type used: Skimmed 1418_3
Milk type used: Soya 1418_4
Mineral and other dietary supplements: Calcium 6179_3
Mineral and other dietary supplements: Fish oil (including cod liver oil) 6179_1
Mineral and other dietary supplements: Glucosamine 6179_2
Mineral and other dietary supplements: Iron 6179_5
Mineral and other dietary supplements: None of the above 6179_100
Mineral and other dietary supplements: Selenium 6179_6
Mineral and other dietary supplements: Zinc 6179_4
Miserableness 1930
Monocyte count 30130_irnt
Monocyte percentage 30190_irnt
Mood [affective] disorders F5_MOOD
Mood disorders KRA_PSY_MOOD
Mood swings 1920
More irritable than usual during worst period of anxiety 20422
Morning/evening person (chronotype) 1180
Most recent bowel cancer screening 2355
Mother still alive 1835
Mother's age at death 3526_irnt
Motor neuron disease G6_ALS
Mouth/teeth dental problems: Bleeding gums 6149_3
Mouth/teeth dental problems: Dentures 6149_6
Mouth/teeth dental problems: Loose teeth 6149_4
Mouth/teeth dental problems: Mouth ulcers 6149_1
Mouth/teeth dental problems: None of the above 6149_100
Mouth/teeth dental problems: Painful gums 6149_2
Mouth/teeth dental problems: Toothache 6149_5
Multiple myeloma and malignant plasma cell neoplasms C_MULTIPLE_MYELOMA_PLASMA_CELL
Multiple worries during worst period of anxiety 20540
Myalgia M13_MYALGIA
Mycoses AB1_MYCOSES
Myeloid leukaemia C_MYELOID-LEUKAEMIA
Myocardial infarction I9_MI
Myocardial infarction, strict I9_MI_STRICT
Ménière disease H8_MENIERE
NA SKIP_CT20220107
Nail disorders L12_NAILDIS
Nap during day 1190
Neck/shoulder pain for 3+ months 3404
Neoplasms II_NEOPLASM
Nerve, nerve root and plexus disorders G6_NERPLEX
Nervous feelings 1970
Neuralgia and neuritis, unspecified M13_NEURALGIA
Neuroticism score 20127_irnt
Neutrophill count 30140_irnt
Neutrophill percentage 30200_irnt
Never eat eggs, dairy, wheat, sugar: Dairy products 6144_2
Never eat eggs, dairy, wheat, sugar: Eggs or foods containing eggs 6144_1
Never eat eggs, dairy, wheat, sugar: I eat all of the above 6144_5
Never eat eggs, dairy, wheat, sugar: Sugar or foods/drinks containing sugar 6144_4
Never eat eggs, dairy, wheat, sugar: Wheat products 6144_3
Night shifts worked: Shift pattern was worked for some (but not all) of job 22650_0
Night shifts worked: Shift pattern was worked for whole of job 22650_1
Night shifts worked: This type of shift pattern was not worked during job 22650_9
Nitrogen dioxide air pollution; 2005 24016_irnt
Nitrogen dioxide air pollution; 2006 24017_irnt
Nitrogen dioxide air pollution; 2007 24018_irnt
Nitrogen dioxide air pollution; 2010 24003_irnt
Nitrogen oxides air pollution; 2010 24004_irnt
Noisy workplace 4825
Non-accidental death in close genetic family 4501
Non-butter spread type details: Flora Pro-Active or Benecol 2654_2
Non-butter spread type details: Hard (block) margarine 2654_5
Non-butter spread type details: Other low or reduced fat spread 2654_8
Non-butter spread type details: Other type of spread/margarine 2654_9
Non-butter spread type details: Soft (tub) margarine 2654_4
Non-cancer illness code, self-reported: abdominal hernia 20002_1511
Non-cancer illness code, self-reported: acne/acne vulgaris 20002_1548
Non-cancer illness code, self-reported: acute infective polyneuritis/guillain-barre syndrome 20002_1256
Non-cancer illness code, self-reported: adrenocortical insufficiency/addison's disease 20002_1234
Non-cancer illness code, self-reported: alcohol dependency 20002_1408
Non-cancer illness code, self-reported: allergy or anaphylactic reaction to drug 20002_1386
Non-cancer illness code, self-reported: allergy or anaphylactic reaction to food 20002_1385
Non-cancer illness code, self-reported: allergy to house dust mite 20002_1668
Non-cancer illness code, self-reported: allergy/hypersensitivity/anaphylaxis 20002_1374
Non-cancer illness code, self-reported: anaemia 20002_1446
Non-cancer illness code, self-reported: anal fissure 20002_1504
Non-cancer illness code, self-reported: angina 20002_1074
Non-cancer illness code, self-reported: ankylosing spondylitis 20002_1313
Non-cancer illness code, self-reported: anorexia/bulimia/other eating disorder 20002_1470
Non-cancer illness code, self-reported: anxiety/panic attacks 20002_1287
Non-cancer illness code, self-reported: appendicitis 20002_1502
Non-cancer illness code, self-reported: arthritis (nos) 20002_1538
Non-cancer illness code, self-reported: asbestosis 20002_1120
Non-cancer illness code, self-reported: asthma 20002_1111
Non-cancer illness code, self-reported: atrial fibrillation 20002_1471
Non-cancer illness code, self-reported: back pain 20002_1534
Non-cancer illness code, self-reported: back problem 20002_1294
Non-cancer illness code, self-reported: bell's palsy/facial nerve palsy 20002_1250
Non-cancer illness code, self-reported: benign / essential tremor 20002_1525
Non-cancer illness code, self-reported: benign neuroma 20002_1683
Non-cancer illness code, self-reported: bladder problem (not cancer) 20002_1201
Non-cancer illness code, self-reported: blepharitis / eyelid infection 20002_1613
Non-cancer illness code, self-reported: blistering/desquamating skin disorder 20002_1454
Non-cancer illness code, self-reported: bone disorder 20002_1293
Non-cancer illness code, self-reported: bowel / intestinal obstruction 20002_1602
Non-cancer illness code, self-reported: brain haemorrhage 20002_1491
Non-cancer illness code, self-reported: bronchiectasis 20002_1114
Non-cancer illness code, self-reported: bronchitis 20002_1412
Non-cancer illness code, self-reported: burns 20002_1407
Non-cancer illness code, self-reported: bursitis 20002_1620
Non-cancer illness code, self-reported: cardiomyopathy 20002_1079
Non-cancer illness code, self-reported: carpal tunnel syndrome 20002_1541
Non-cancer illness code, self-reported: cataract 20002_1278
Non-cancer illness code, self-reported: cellulitis 20002_1625
Non-cancer illness code, self-reported: cerebral aneurysm 20002_1425
Non-cancer illness code, self-reported: cerebral palsy 20002_1433
Non-cancer illness code, self-reported: cervical spondylosis 20002_1478
Non-cancer illness code, self-reported: chickenpox 20002_1571
Non-cancer illness code, self-reported: cholecystitis 20002_1163
Non-cancer illness code, self-reported: cholelithiasis/gall stones 20002_1162
Non-cancer illness code, self-reported: chronic fatigue syndrome 20002_1482
Non-cancer illness code, self-reported: chronic obstructive airways disease/copd 20002_1112
Non-cancer illness code, self-reported: chronic sinusitis 20002_1416
Non-cancer illness code, self-reported: chronic skin ulcers 20002_1455
Non-cancer illness code, self-reported: chronic/degenerative neurological problem 20002_1258
Non-cancer illness code, self-reported: clotting disorder/excessive bleeding 20002_1445
Non-cancer illness code, self-reported: colitis/not crohns or ulcerative colitis 20002_1459
Non-cancer illness code, self-reported: connective tissue disorder 20002_1373
Non-cancer illness code, self-reported: constipation 20002_1599
Non-cancer illness code, self-reported: cranial nerve problem/palsy 20002_1249
Non-cancer illness code, self-reported: crohns disease 20002_1462
Non-cancer illness code, self-reported: cystitis 20002_1514
Non-cancer illness code, self-reported: deep venous thrombosis (dvt) 20002_1094
Non-cancer illness code, self-reported: deliberate self-harm/suicide attempt 20002_1290
Non-cancer illness code, self-reported: depression 20002_1286
Non-cancer illness code, self-reported: diabetes 20002_1220
Non-cancer illness code, self-reported: diabetic eye disease 20002_1276
Non-cancer illness code, self-reported: diabetic neuropathy/ulcers 20002_1468
Non-cancer illness code, self-reported: disc degeneration 20002_1533
Non-cancer illness code, self-reported: disc problem 20002_1532
Non-cancer illness code, self-reported: diverticular disease/diverticulitis 20002_1458
Non-cancer illness code, self-reported: dry eyes 20002_1529
Non-cancer illness code, self-reported: duodenal ulcer 20002_1457
Non-cancer illness code, self-reported: dupuytren's contracture 20002_1544
Non-cancer illness code, self-reported: dyspepsia / indigestion 20002_1510
Non-cancer illness code, self-reported: ear/vestibular disorder 20002_1415
Non-cancer illness code, self-reported: eczema/dermatitis 20002_1452
Non-cancer illness code, self-reported: emphysema 20002_1472
Non-cancer illness code, self-reported: emphysema/chronic bronchitis 20002_1113
Non-cancer illness code, self-reported: encephalitis 20002_1246
Non-cancer illness code, self-reported: epilepsy 20002_1264
Non-cancer illness code, self-reported: essential hypertension 20002_1072
Non-cancer illness code, self-reported: eye infection 20002_1274
Non-cancer illness code, self-reported: eye trauma 20002_1279
Non-cancer illness code, self-reported: eye/eyelid problem 20002_1242
Non-cancer illness code, self-reported: femoral hernia 20002_1605
Non-cancer illness code, self-reported: fibromyalgia 20002_1542
Non-cancer illness code, self-reported: food intolerance 20002_1562
Non-cancer illness code, self-reported: fracture clavicle / collar bone 20002_1631
Non-cancer illness code, self-reported: fracture face / orbit / eye socket 20002_1629
Non-cancer illness code, self-reported: fracture fibula 20002_1653
Non-cancer illness code, self-reported: fracture finger 20002_1639
Non-cancer illness code, self-reported: fracture foot 20002_1654
Non-cancer illness code, self-reported: fracture forearm / wrist 20002_1634
Non-cancer illness code, self-reported: fracture hand 20002_1638
Non-cancer illness code, self-reported: fracture jaw 20002_1627
Non-cancer illness code, self-reported: fracture lower leg / ankle 20002_1651
Non-cancer illness code, self-reported: fracture metatarsal 20002_1655
Non-cancer illness code, self-reported: fracture neck of femur / hip 20002_1648
Non-cancer illness code, self-reported: fracture nose 20002_1628
Non-cancer illness code, self-reported: fracture patella / knee 20002_1650
Non-cancer illness code, self-reported: fracture pelvis 20002_1647
Non-cancer illness code, self-reported: fracture radius 20002_1635
Non-cancer illness code, self-reported: fracture rib 20002_1644
Non-cancer illness code, self-reported: fracture shaft of femur 20002_1649
Non-cancer illness code, self-reported: fracture shoulder / scapula 20002_1632
Non-cancer illness code, self-reported: fracture skull / head 20002_1626
Non-cancer illness code, self-reported: fracture tibia 20002_1652
Non-cancer illness code, self-reported: fracture toe 20002_1656
Non-cancer illness code, self-reported: fracture ulna 20002_1636
Non-cancer illness code, self-reported: fracture upper arm / humerus / elbow 20002_1633
Non-cancer illness code, self-reported: fracture vertebra / crush fracture / vertebral collapse 20002_1646
Non-cancer illness code, self-reported: fracture wrist / colles fracture 20002_1637
Non-cancer illness code, self-reported: gall bladder disease 20002_1161
Non-cancer illness code, self-reported: gastric/stomach ulcers 20002_1142
Non-cancer illness code, self-reported: gastritis/gastric erosions 20002_1143
Non-cancer illness code, self-reported: gastro-oesophageal reflux (gord) / gastric reflux 20002_1138
Non-cancer illness code, self-reported: gastroenteritis/dysentry 20002_1509
Non-cancer illness code, self-reported: gastrointestinal bleeding 20002_1191
Non-cancer illness code, self-reported: glaucoma 20002_1277
Non-cancer illness code, self-reported: gout 20002_1466
Non-cancer illness code, self-reported: haemorrhoids / piles 20002_1505
Non-cancer illness code, self-reported: hayfever/allergic rhinitis 20002_1387
Non-cancer illness code, self-reported: head injury 20002_1266
Non-cancer illness code, self-reported: headaches (not migraine) 20002_1436
Non-cancer illness code, self-reported: heart arrhythmia 20002_1077
Non-cancer illness code, self-reported: heart attack/myocardial infarction 20002_1075
Non-cancer illness code, self-reported: heart failure/pulmonary odema 20002_1076
Non-cancer illness code, self-reported: heart valve problem/heart murmur 20002_1078
Non-cancer illness code, self-reported: heart/cardiac problem 20002_1066
Non-cancer illness code, self-reported: helicobacter pylori 20002_1442
Non-cancer illness code, self-reported: hepatitis 20002_1155
Non-cancer illness code, self-reported: hepatitis a 20002_1578
Non-cancer illness code, self-reported: hereditary/genetic haematological disorder 20002_1451
Non-cancer illness code, self-reported: herpes simplex 20002_1575
Non-cancer illness code, self-reported: hiatus hernia 20002_1474
Non-cancer illness code, self-reported: high cholesterol 20002_1473
Non-cancer illness code, self-reported: hiv/aids 20002_1439
Non-cancer illness code, self-reported: hypertension 20002_1065
Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis 20002_1225
Non-cancer illness code, self-reported: hypopituitarism 20002_1430
Non-cancer illness code, self-reported: hypothyroidism/myxoedema 20002_1226
Non-cancer illness code, self-reported: infectious mononucleosis / glandular fever / epstein barr virus (ebv) 20002_1567
Non-cancer illness code, self-reported: infective/viral hepatitis 20002_1156
Non-cancer illness code, self-reported: inflammatory bowel disease 20002_1461
Non-cancer illness code, self-reported: inguinal hernia 20002_1513
Non-cancer illness code, self-reported: insomnia 20002_1616
Non-cancer illness code, self-reported: interstitial lung disease 20002_1115
Non-cancer illness code, self-reported: iritis 20002_1530
Non-cancer illness code, self-reported: iron deficiency anaemia 20002_1330
Non-cancer illness code, self-reported: irregular heart beat 20002_1485
Non-cancer illness code, self-reported: irritable bowel syndrome 20002_1154
Non-cancer illness code, self-reported: jaundice (unknown cause) 20002_1508
Non-cancer illness code, self-reported: joint disorder 20002_1295
Non-cancer illness code, self-reported: joint pain 20002_1537
Non-cancer illness code, self-reported: kidney stone/ureter stone/bladder stone 20002_1197

Treatment/medication code: vascalpha 5mg m/r tablet 20003_1141190160
Treatment/medication code: venlafaxine 20003_1140916282
Treatment/medication code: ventolin 100micrograms inhaler 20003_1140861998
Treatment/medication code: ventolin 2mg tablet 20003_1140862060
Treatment/medication code: verapamil 20003_1140888510
Treatment/medication code: vesicare 5mg tablet 20003_1141200384
Treatment/medication code: viscotears liquid eye gel 20003_1140865010
Treatment/medication code: vitamin a 20003_1140852756
Treatment/medication code: vitamin b compound tablet 20003_1140871024
Treatment/medication code: vitamin b1 preparation 20003_1140909872
Treatment/medication code: vitamin b12 preparation 20003_1140870570
Treatment/medication code: vitamin b6 preparation 20003_1140909874
Treatment/medication code: vitamin c product SKIP_CT20220107
Treatment/medication code: vitamin d product 20003_1140870954
Treatment/medication code: vitamin e product 20003_1140871112
Treatment/medication code: voltarol 25mg e/c tablet 20003_1140871168
Treatment/medication code: voltarol emulgel 20003_1140877892
Treatment/medication code: warfarin 20003_1140888266
Treatment/medication code: xalacom 0.005%/0.5% eye drops 20003_1141184726
Treatment/medication code: xalatan 0.005% eye drops 20003_1141146198
Treatment/medication code: xenical 120mg capsule 20003_1141168684
Treatment/medication code: zanidip 10mg tablet 20003_1141153032
Treatment/medication code: zantac 75 tablet 20003_1140916980
Treatment/medication code: zapain caplet 20003_1141178052
Treatment/medication code: zimovane ls 3.75mg tablet 20003_1140928004
Treatment/medication code: zinc product 20003_1140888538
Treatment/medication code: zirtek 10mg tablet 20003_1140862770
Treatment/medication code: zirtek allergy 10mg tablet 20003_1141180662
Treatment/medication code: zolmitriptan 20003_1141150620
Treatment/medication code: zolpidem 20003_1140865016
Treatment/medication code: zomig 2.5mg tablet 20003_1141150624
Treatment/medication code: zopiclone 20003_1140863144
Treatment/medication code: zoton 15mg capsule 20003_1140923688
Treatment/medication code: zydol 50mg capsule 20003_1140865000
Trigeminal neuralgia G6_TRINEU
Trigger finger M13_TRIGGERFINGER
Trouble falling asleep 20533
Trouble falling or staying asleep, or sleeping too much 20517
Trunk fat mass 23128_irnt
Trunk fat percentage 23127_irnt
Trunk fat-free mass 23129_irnt
Trunk predicted mass 23130_irnt
Type 1 diabetes E4_DM1
Type 1 diabetes with ketoacidosis E4_DM1KETO
Type 1 diabetes with ophthalmic complications E4_DM1OPTH
Type 1 diabetes without complications E4_DM1NOCOMP
Type 2 diabetes E4_DM2
Type 2 diabetes with ophthalmic complications E4_DM2OPTH
Type 2 diabetes with peripheral circulatory complications E4_DM2PERIPH
Type 2 diabetes without complications E4_DM2NOCOMP
Type milk consumed: cholesterol lowering milk 100920_2110
Type milk consumed: did not have milk 100920_0
Type milk consumed: goat/sheep milk 100920_2107
Type milk consumed: other type of milk 100920_2199
Type milk consumed: powdered milk 100920_2109
Type milk consumed: rice/oat/vegetable milk 100920_2108
Type milk consumed: skimmed 100920_2103
Type milk consumed: soya with calcium 100920_2105
Type milk consumed: soya without calcium 100920_2106
Type milk consumed: wholemilk 100920_2104
Type of accommodation lived in: A flat, maisonette or apartment 670_2
Type of accommodation lived in: A house or bungalow 670_1
Type of accommodation lived in: Mobile or temporary structure (i.e. caravan) 670_3
Type of accommodation lived in: Sheltered accommodation 670_4
Type of fat/oil used in cooking: Butter 20090_359
Type of fat/oil used in cooking: Cholesterol lowering olive spread 20090_369
Type of fat/oil used in cooking: Cholesterol lowering polyunsaturated margarine 20090_375
Type of fat/oil used in cooking: Dairy spread 20090_377
Type of fat/oil used in cooking: Hard margarine 20090_395
Type of fat/oil used in cooking: Lard 20090_364
Type of fat/oil used in cooking: Low fat butter 20090_361
Type of fat/oil used in cooking: Low fat dairy spread 20090_379
Type of fat/oil used in cooking: Low fat olive spread for 20090_367
Type of fat/oil used in cooking: Low fat polyunsaturated margarine 20090_373
Type of fat/oil used in cooking: Low fat soft margarine 20090_391
Type of fat/oil used in cooking: Low fat soya margarine 20090_385
Type of fat/oil used in cooking: Normal fat butter 20090_362
Type of fat/oil used in cooking: Normal fat dairy spread 20090_380
Type of fat/oil used in cooking: Normal fat olive spread 20090_368
Type of fat/oil used in cooking: Normal fat polyunsaturated margarine 20090_374
Type of fat/oil used in cooking: Normal fat soft margarine 20090_392
Type of fat/oil used in cooking: Normal fat soya margarine 20090_386
Type of fat/oil used in cooking: Olive spread 20090_365
Type of fat/oil used in cooking: Other oil 20090_357
Type of fat/oil used in cooking: Other type fat 20090_396
Type of fat/oil used in cooking: Polyunsaturated margarine 20090_371
Type of fat/oil used in cooking: Rapeseed oil 20090_356
Type of fat/oil used in cooking: Soya margarine 20090_383
Type of fat/oil used in cooking: Spreadable butter 20090_360
Type of fat/oil used in cooking: Sunflower oil 20090_354
Type of fat/oil used in cooking: Unknown fat butter 20090_363
Type of fat/oil used in cooking: Unknown olive spread 20090_370
Type of fat/oil used in cooking: Unknown polyunsaturated margarine 20090_376
Type of fat/oil used in cooking: Unknown soft margarine 20090_394
Type of fat/oil used in cooking: Unknown/other soft margarine 20090_389
Type of fat/oil used in cooking: Vegetable oil 20090_355
Type of fat/oil used in cooking: Very low fat olive spread 20090_366
Type of fat/oil used in cooking: Very low fat polyunsaturated margarine 20090_372
Type of meals eaten: Bought sandwiches 20089_463
Type of meals eaten: Home cooked meals 20089_465
Type of meals eaten: Ready meals 20089_464
Type of meals eaten: Restaurant meals 20089_462
Type of meals eaten: Takeaway meals 20089_461
Type of special diet followed: Gluten-free 20086_8
Type of special diet followed: Lactose-free 20086_9
Type of special diet followed: Low calorie 20086_10
Type of special diet followed: Other 20086_13
Type of special diet followed: Vegan 20086_12
Type of special diet followed: Vegetarian 20086_11
Type of tobacco currently smoked: Cigars or pipes 3446_3
Type of tobacco currently smoked: Hand-rolled cigarettes 3446_2
Type of tobacco currently smoked: Manufactured cigarettes 3446_1
Type of tobacco previously smoked: Cigars or pipes 2877_3
Type of tobacco previously smoked: Hand-rolled cigarettes 2877_2
Type of tobacco previously smoked: Manufactured cigarettes 2877_1
Types of physical activity in last 4 weeks: Heavy DIY (eg: weeding, lawn mowing, carpentry, digging) 6164_5
Types of physical activity in last 4 weeks: Light DIY (eg: pruning, watering the lawn) 6164_4
Types of physical activity in last 4 weeks: None of the above 6164_100
Types of physical activity in last 4 weeks: Other exercises (eg: swimming, cycling, keep fit, bowling) 6164_2
Types of physical activity in last 4 weeks: Strenuous sports 6164_3
Types of physical activity in last 4 weeks: Walking for pleasure (not as a means of transport) 6164_1
Types of transport used (excluding work): Car/motor vehicle 6162_1
Types of transport used (excluding work): Cycle 6162_4
Types of transport used (excluding work): None of the above 6162_100
Types of transport used (excluding work): Public transport 6162_3
Types of transport used (excluding work): Walk 6162_2
Ulcer of oesophagus K11_OESULC
Ulcerative colitis, NAS ULCERNAS
Ulcerative proctitis ULCERPROCT
Ulcerative rectosigmoiditis ULCERRECT
Unclassified diabetic retinopathy DM_RETINOPAT_NOS
Underlying (primary) cause of death: ICD10: C15.9 Oesophagus, unspecified 40001_C159
Underlying (primary) cause of death: ICD10: C16.9 Stomach, unspecified 40001_C169
Underlying (primary) cause of death: ICD10: C18.9 Colon, unspecified 40001_C189
Underlying (primary) cause of death: ICD10: C19 Malignant neoplasm of rectosigmoid junction 40001_C19
Underlying (primary) cause of death: ICD10: C20 Malignant neoplasm of rectum 40001_C20
Underlying (primary) cause of death: ICD10: C22.1 Intrahepatic bile duct carcinoma 40001_C221
Underlying (primary) cause of death: ICD10: C25.9 Pancreas, unspecified 40001_C259
Underlying (primary) cause of death: ICD10: C34.9 Bronchus or lung, unspecified 40001_C349
Underlying (primary) cause of death: ICD10: C43.9 Malignant melanoma of skin, unspecified 40001_C439
Underlying (primary) cause of death: ICD10: C45.9 Mesothelioma, unspecified 40001_C459
Underlying (primary) cause of death: ICD10: C50.9 Breast, unspecified 40001_C509
Underlying (primary) cause of death: ICD10: C56 Malignant neoplasm of ovary 40001_C56
Underlying (primary) cause of death: ICD10: C64 Malignant neoplasm of kidney, except renal pelvis 40001_C64
Underlying (primary) cause of death: ICD10: C67.9 Bladder, unspecified 40001_C679
Underlying (primary) cause of death: ICD10: C71.9 Brain, unspecified 40001_C719
Underlying (primary) cause of death: ICD10: C80 Malignant neoplasm without specification of site 40001_C80
Underlying (primary) cause of death: ICD10: C90.0 Multiple myeloma 40001_C900
Underlying (primary) cause of death: ICD10: C92.0 Acute myeloid leukaemia 40001_C920
Underlying (primary) cause of death: ICD10: G12.2 Motor neuron disease 40001_G122
Underlying (primary) cause of death: ICD10: I21.9 Acute myocardial infarction, unspecified 40001_I219
Underlying (primary) cause of death: ICD10: I25.1 Atherosclerotic heart disease 40001_I251
Underlying (primary) cause of death: ICD10: I25.9 Chronic ischaemic heart disease, unspecified 40001_I259
Underlying (primary) cause of death: ICD10: I64 Stroke, not specified as haemorrhage or infarction 40001_I64
Underlying (primary) cause of death: ICD10: J84.1 Other interstitial pulmonary diseases with fibrosis 40001_J841
Unsalted nuts intake 102440
Unsepcified/other endometriosis ENDOMETRIOSIS_NOS
Unspecified diabetes with ophthalmic complications E4_DMNASOPTH
Unstable angina pectoris I9_UAP
Urticaria L12_URTICARIA
Use of sun/uv protection 2267
Used an inhaler for chest within last hour 3090
Usual side of head for mobile phone use: Equally left and right 1150_3
Usual side of head for mobile phone use: Left 1150_1
Usual side of head for mobile phone use: Right 1150_2
Usual walking pace 924
Variation in diet 1548
Vascular diseases of the intestine I9_VASCINT
Vascular/heart problems diagnosed by doctor: Angina 6150_2
Vascular/heart problems diagnosed by doctor: Heart attack 6150_1
Vascular/heart problems diagnosed by doctor: High blood pressure 6150_4
Vascular/heart problems diagnosed by doctor: None of the above 6150_100
Vascular/heart problems diagnosed by doctor: Stroke 6150_3
Vegetable consumers 103990
Vegetarian alternatives intake 103250
Venous thromboembolism I9_VTE
Ventricular rate 12336_irnt
Victim of sexual assault 20531
Viral hepatitis AB1_VIRAL_HEPATITIS
Viral hepatitis, IBD co-morbidity IBD_VIRAL_HEPATITIS
Viral infections characterized by skin and mucous membrane lesions AB1_VIRAL_SKIN_MUCOUS_MEMBRANE
Viral infections of the central nervous system AB1_VIRAL_CNS
Visual disturbances H7_VISUDISTURB
Vitamin B12 100013_irnt
Vitamin B6 100012_irnt
Vitamin C 100015_irnt
Vitamin D 100021_irnt
Vitamin E 100025_irnt
Vitamin and mineral supplements: Folic acid or Folate (Vit B9) 6155_6
Vitamin and mineral supplements: Multivitamins +/- minerals 6155_7
Vitamin and mineral supplements: None of the above 6155_100
Vitamin and mineral supplements: Vitamin A 6155_1
Vitamin and mineral supplements: Vitamin B 6155_2
Vitamin and mineral supplements: Vitamin C 6155_3
Vitamin and mineral supplements: Vitamin D 6155_4
Vitamin and mineral supplements: Vitamin E 6155_5
Vitamin and/or mineral supplement use: Calcium 20084_485
Vitamin and/or mineral supplement use: Chromium 20084_482
Vitamin and/or mineral supplement use: Evening primrose 20084_474
Vitamin and/or mineral supplement use: Folic acid 20084_481
Vitamin and/or mineral supplement use: Glucosamine/chondroitin 20084_473
Vitamin and/or mineral supplement use: Iron 20084_486
Vitamin and/or mineral supplement use: Magnesium 20084_483
Vitamin and/or mineral supplement use: Multivitamin 20084_468
Vitamin and/or mineral supplement use: Multivitamin with calcium 20084_470
Vitamin and/or mineral supplement use: Multivitamin with iron 20084_469
Vitamin and/or mineral supplement use: Multivitamin with multimineral 20084_471
Vitamin and/or mineral supplement use: Other vitamin 20084_488
Vitamin and/or mineral supplement use: Selenium 20084_484
Vitamin and/or mineral supplement use: Vitamin A 20084_475
Vitamin and/or mineral supplement use: Vitamin B12 20084_477
Vitamin and/or mineral supplement use: Vitamin B6 20084_476
Vitamin and/or mineral supplement use: Vitamin C 20084_478
Vitamin and/or mineral supplement use: Vitamin D 20084_479
Vitamin and/or mineral supplement use: Vitamin E 20084_480
Vitamin and/or mineral supplement use: Zinc 20084_487
Vitamin deficiency VIT_DEF
Vitreous haemorrhage H7_VITRHAEMORR
Vocal cord dysfunction VOCALCORDDYS
Volume level set by participant (left) 4270
Volume level set by participant (right) 4277
Volvulus K11_VOLVU
Waist circumference 48_irnt
Water intake 1528
Wears glasses or contact lenses 2207
Weekly usage of mobile phone in last 3 months 1120
Weight SKIP_CT20220107
Weight change compared with 1 year ago 2306
Weight change during worst episode of depression: Both gained and lost some weight during the episode 20536_3
Weight change during worst episode of depression: Gained weight 20536_1
Weight change during worst episode of depression: Stayed about the same or was on a diet 20536_0
Weight, manual entry 3160_irnt
Wheeze or whistling in the chest in last year 2316
Which eye(s) affected by astigmatism: Left eye 5855_2
Which eye(s) affected by astigmatism: Right eye 5855_1
Which eye(s) affected by hypermetropia (long sight): Both eyes 5832_3
Which eye(s) affected by hypermetropia (long sight): Left eye 5832_2
Which eye(s) affected by hypermetropia (long sight): Right eye 5832_1
Which eye(s) affected by myopia (short sight): Both eyes 5843_3
Which eye(s) affected by myopia (short sight): Left eye 5843_2
Which eye(s) affected by myopia (short sight): Right eye 5843_1
Which eye(s) affected by presbyopia: Both eyes 5610_3
Which eye(s) affected by presbyopia: Left eye 5610_2
Which eye(s) affected by presbyopia: Right eye 5610_1
White blood cell (leukocyte) count 30000_irnt
White wine intake 100670
Whole body fat mass 23100_irnt
Whole body fat-free mass 23101_irnt
Whole body water mass 23102_irnt
Why reduced smoking: Doctor's advice 6158_2
Why reduced smoking: Financial reasons 6158_4
Why reduced smoking: Health precaution 6158_3
Why reduced smoking: Illness or ill health 6158_1
Why reduced smoking: None of the above 6158_100
Why stopped smoking: Doctor's advice 6157_2
Why stopped smoking: Health precaution 6157_3
Why stopped smoking: Illness or ill health 6157_1
Witnessed sudden violent death 20530
Work hours - lumped category: 15 to less-than-20 hours 22604_1
Work hours per week - exact value 22605_irnt
Worked with materials containing asbestos: Often 22612_2
Worked with materials containing asbestos: Rarely/never 22612_0
Worked with materials containing asbestos: Sometimes 22612_1
Worked with paints, thinners or glues: Often 22613_2
Worked with paints, thinners or glues: Rarely/never 22613_0
Worked with paints, thinners or glues: Sometimes 22613_1
Worked with pesticides: Often 22614_2
Worked with pesticides: Rarely/never 22614_0
Worked with pesticides: Sometimes 22614_1
Workplace full of chemical or other fumes: Often 22610_2
Workplace full of chemical or other fumes: Rarely/never 22610_0
Workplace had a lot of cigarette smoke from other people smoking: Often 22611_2
Workplace had a lot of cigarette smoke from other people smoking: Rarely/never 22611_0
Workplace had a lot of diesel exhaust: Often 22615_2
Workplace had a lot of diesel exhaust: Rarely/never 22615_0
Workplace had a lot of diesel exhaust: Sometimes 22615_1
Workplace very cold: Often 22607_2
Workplace very cold: Rarely/never 22607_0
Workplace very cold: Sometimes 22607_1
Workplace very dusty: Often 22609_2
Workplace very dusty: Rarely/never 22609_0
Workplace very hot: Often 22608_2
Workplace very hot: Rarely/never 22608_0
Workplace very noisy: Rarely/never 22606_0
Worried most days during period of worst anxiety 20538
Worrier / anxious feelings 1980
Worry too long after embarrassment 2000
Xanthelasma of eyelid H7_XANTHELASMA
Year ended full time education 22501_irnt
Years of cough on most days 22503_irnt
Years since last cervical smear test 2704
diab type1 SKIP_CT20220107
logMAR, final (left) 5208_irnt
logMAR, final (right) 5201_irnt
malignant neoplasm of female genital organs C3_FEMALE_GENITAL
malignant neoplasm of male genital organs C3_MALE_GENITAL
severe traumatic brain injury, does not include concussion TRAUMBRAIN_NONCONCUS