In [2]:
import numpy as np
import pandas as pd
import itertools
import matplotlib.pyplot as plt
from datetime import date
import re
from tqdm import tqdm
import time
from pybedtools import BedTool
import random
import math
import pickle
import seaborn as sns
from scipy.stats import percentileofscore, pearsonr
from scipy.spatial.distance import jaccard, euclidean, cosine
import functools
import operator
import gzip
from sklearn.feature_extraction.text import TfidfVectorizer

today = date.today()

**SNP**

**Transcription Factor**

**DHS**

**Chromatin State**

**Genes**

In [3]:
# 25kb bins
bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)
print(bins_25kb)


# SNP data
snp_cols = ['Chromosome', 'p1', 'p2', 'Reference SNP cluster ID', 'pvalue', 'phenotype']
snp_df = pd.read_csv('../data/UKBB_all_traits_all_sig_associations_CT20220207.bed', delimiter='\t', names=snp_cols)
print(snp_df)

# trait_codes = []
# with gzip.open('/home/nasi4/proj/GWAS/UKBB_201807/info/phenotypes.both_sexes.tsv.gz','r') as f:
#     for line in f:
#         trait_codes.append(line.decode("utf-8").strip('\n').split('\t'))

# trait_codes_df = pd.DataFrame(trait_codes[1:], columns=trait_codes[0])
# print(trait_codes_df)

# TF data 
# NOTE: THIS IS CURRENTLY HG38
tf_pd = pd.read_pickle('../data/TF-df-hg38.pkl')
print(tf_pd)

# DHS data
dhs_df = pd.read_pickle('../data/dhs_metadata.pkl')
print(dhs_df)

dhs_Mixture_df = pd.read_pickle('../data/dhs_mixture_df.pkl')
print(dhs_Mixture_df)

dhs_obs_over_exp = pd.read_pickle('../data/dhs_obs_over_exp_25kb.pkl')
print(dhs_obs_over_exp)

# Chromatin State Data
epilogos_833_df = pd.read_pickle('../data/epilogos_state_data_18.pkl')
print(epilogos_833_df)

epilogos_states_df = pd.read_pickle('../data/epilogos_states_df')
print(epilogos_states_df)

epilogos_metadata = pd.read_csv('../data/All_833_biosamples/metadata.tsv', delimiter='\t')
print(epilogos_metadata)


# Gene Data
string_assoc = pd.read_pickle('../data/hg19-protein-associations.pkl')
print(string_assoc)

gene_hg19_bed = pd.read_pickle('../data/hg19_gene_bed.pkl')
print(gene_hg19_bed)

protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
print(protein_assoc_hg19)

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]
         Chromosome         p1         p2 Reference SNP cluster ID  \
0             chr12  130300801  130300802               rs73150827
1              chr4   99318162   99318163                rs1229984
2              chr9    8303561    8303562              rs112120933
3              chr1   46941503   46941504              rs141586057
4             chr20   52932649   52932650              rs185961463
...             ...        ...        ...                      ...
11252644       chr5   32713221   32713222                rs3828589
11252645       chr5   32713730   32713731                rs3792765
11252646       chr5   32714164   32714165                rs1421811
11252647       chr5   32716368   32716369               rs34628434
11252648      chr11   34641544   34641545              rs182699973

                pvalue phenotype
0         3.555020e-08    100022
1         1.041850e-13    100022
2         3.689310e-09    100022
3         4.034800e-08      1001
4         1.629800e-08      1001
...                ...       ...
11252644  1.778290e-08   93_irnt
11252645  1.673070e-08   93_irnt
11252646  1.879810e-08   93_irnt
11252647  1.116850e-08   93_irnt
11252648  5.129920e-09   94_irnt

[11252649 rows x 6 columns]
                       chromosome  start    end TF motif cluster/group  \
0                            chr1  10005  10022               KLF/SP/2
1                            chr1  10011  10028               KLF/SP/2
2                            chr1  10017  10034               KLF/SP/2
3                            chr1  10023  10040               KLF/SP/2
4                            chr1  10029  10046               KLF/SP/2
...                           ...    ...    ...                    ...
764808786  chrY_KI270740v1_random  37190  37196                  SNAI2
764808787  chrY_KI270740v1_random  37190  37197            Ebox/CACCTG
764808788  chrY_KI270740v1_random  37191  37204                  NR/11
764808789  chrY_KI270740v1_random  37219  37233                 ZNF418
764808790  chrY_KI270740v1_random  37219  37233                  SOX/8

           match score strand               TF motif  ?
0               3.7536      -         RREB1_MA0073.1  1
1               3.7536      -         RREB1_MA0073.1  1
2               3.7536      -         RREB1_MA0073.1  1
3               3.7536      -         RREB1_MA0073.1  1
4               3.7536      -         RREB1_MA0073.1  1
...                ...    ...                    ... ..
764808786       7.7409      +           SNAI2_C2H2_1  2
764808787       6.6662      -  SNAI2_HUMAN.H11MO.0.A  2
764808788       6.7667      +  NR6A1_HUMAN.H11MO.0.B  1
764808789       6.6390      -  ZN418_HUMAN.H11MO.0.C  1
764808790       4.9806      +             SOX9_HMG_4  3

[764808791 rows x 8 columns]
           seqname     start       end  mean_signal  numsamples    summit  \
identifier
1.10011       chr1     16140     16200     0.129388           1     16170
1.10021       chr1     51868     52040     0.080034           1     51970
1.10025       chr1     57280     57354     0.273251           4     57350
1.10027       chr1     66370     66482     0.183716           8     66430
1.1003        chr1     79100     79231     0.113049           2     79150
...            ...       ...       ...          ...         ...       ...
Y.994281      chrY  56882540  56882719     0.038079           1  56882610
Y.994286      chrY  56882864  56882980     0.115489           1  56882930
Y.994292      chrY  56883733  56883960     0.491377           5  56883830
Y.994297      chrY  56884440  56884580     0.053759           1  56884510
Y.99435       chrY  56885400  56885520     0.062719           1  56885430

            core_start    core_end                component
identifier
1.10011        16170.0     16170.0         Tissue invariant
1.10021        51970.0     51970.0  Placental / trophoblast
1.10025        57350.0     57350.0                   Neural
1.10027        66410.0     66430.0    Primitive / embryonic
1.1003         79150.0     79150.0  Placental / trophoblast
...                ...         ...                      ...
Y.994281    56882610.0  56882610.0                 Lymphoid
Y.994286    56882930.0  56882930.0                 Lymphoid
Y.994292    56883742.0  56883870.0  Placental / trophoblast
Y.994297    56884510.0  56884510.0                 Lymphoid
Y.99435     56885430.0  56885430.0                 Lymphoid

[3591898 rows x 9 columns]
identifier   1.10011   1.10021   1.10025   1.10027    1.1003   1.10032  \
0           0.001439  0.000000  0.000000  0.001336  0.000000  0.000000
1           0.000000  0.000000  0.000000  0.001010  0.000000  0.000000
2           0.000000  0.000000  0.000000  0.011659  0.000893  0.000000
3           0.000000  0.000311  0.000000  0.008287  0.000000  0.000000
4           0.000204  0.000000  0.000000  0.004569  0.000134  0.001297
5           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
6           0.000040  0.011431  0.000000  0.002904  0.006965  0.000000
7           0.000000  0.000000  0.025745  0.001445  0.000000  0.000000
8           0.000000  0.000000  0.000000  0.000000  0.000208  0.000000
9           0.000000  0.000000  0.000000  0.000000  0.001768  0.000000
10          0.000000  0.000000  0.000000  0.000000  0.003912  0.000000
11          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
12          0.000000  0.000000  0.000000  0.003885  0.000000  0.008636
13          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
14          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
15          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000

identifier   1.10033  1.100343  1.100347  1.100351  ...  Y.994248  Y.994259  \
0           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
1           0.000000  0.000000  0.001740  0.000000  ...  0.000000  0.000000
2           0.000000  0.000000  0.001512  0.000213  ...  0.000896  0.000522
3           0.000000  0.000000  0.003215  0.000000  ...  0.000000  0.000310
4           0.000064  0.000064  0.005370  0.005270  ...  0.003657  0.003596
5           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.002632
6           0.007067  0.007067  0.004603  0.004874  ...  0.000000  0.000000
7           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
8           0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
9           0.000000  0.000000  0.001131  0.000022  ...  0.000000  0.000000
10          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000
11          0.000000  0.000000  0.001678  0.000000  ...  0.000000  0.000000
12          0.000000  0.000000  0.007200  0.000000  ...  0.000000  0.000000
13          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000517
14          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000018
15          0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.001571

identifier  Y.994264   Y.99427  Y.994275  Y.994281  Y.994286  Y.994292  \
0           0.000000  0.002974  0.000000  0.000000  0.000000  0.000000
1           0.000000  0.000507  0.000000  0.000000  0.000000  0.000000
2           0.001436  0.002266  0.000896  0.000896  0.000508  0.000737
3           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
4           0.006898  0.003707  0.003657  0.003657  0.003223  0.000000
5           0.000000  0.007015  0.000000  0.000000  0.000000  0.000000
6           0.000000  0.022471  0.000000  0.000000  0.000000  0.017065
7           0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
8           0.000055  0.000000  0.000000  0.000000  0.000249  0.000000
9           0.000000  0.000000  0.000000  0.000000  0.000000  0.000177
10          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
11          0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
12          0.000000  0.001180  0.000000  0.000000  0.000035  0.000000
13          0.000000  0.000574  0.000000  0.000000  0.000000  0.000000
14          0.000177  0.000000  0.000000  0.000000  0.000180  0.000000
15          0.000014  0.005264  0.000000  0.000000  0.000146  0.012509

identifier  Y.994297   Y.99435
0           0.000000  0.000000
1           0.000000  0.000000
2           0.000896  0.000896
3           0.000000  0.000000
4           0.003657  0.003657
5           0.000000  0.000000
6           0.000000  0.000000
7           0.000000  0.000000
8           0.000000  0.000000
9           0.000000  0.000000
10          0.000000  0.000000
11          0.000000  0.000000
12          0.000000  0.000000
13          0.000000  0.000000
14          0.000000  0.000000
15          0.000000  0.000000

[16 rows x 3591898 columns]
      seqname      start        end  Cancer_epithelial   Cardiac  Digestive  \
0        chr1       9000      34000           0.000000  0.000000   0.000000
1        chr1      34000      59000           0.000000  0.000000   0.000000
2        chr1      61000      86000           0.000000  0.000000   0.857702
3        chr1      86000     111000           0.000000  0.000000   0.857702
4        chr1     111000     136000           0.000000  0.000000   0.857702
...       ...        ...        ...                ...       ...        ...
99991    chrX  155042800  155067800           0.654274  0.000000   0.857702
99992    chrX  155067800  155092800           1.308548  2.086510   1.715403
99993    chrX  155092800  155117800           1.962823  1.043255   0.857702
99994    chrX  155117800  155142800           0.654274  0.000000   0.857702
99995    chrX  155142800  155167800           3.271371  1.043255   0.000000

       Lymphoid  Musculoskeletal  Myeloid_erythroid    Neural  \
0      0.000000         0.000000           0.000000  0.000000
1      0.000000         0.000000           0.000000  0.267417
2      0.000000         0.000000           0.000000  0.000000
3      0.441178         0.569736           0.000000  0.267417
4      0.441178         0.000000           0.000000  0.000000
...         ...              ...                ...       ...
99991  0.882355         1.139471           1.990049  0.802251
99992  0.882355         0.569736           2.653399  0.267417
99993  0.441178         0.569736           0.663350  0.267417
99994  0.000000         0.569736           2.653399  0.267417
99995  0.882355         0.569736           0.000000  0.267417

       Organdevel_renal  Placental_trophoblast  Primitive_embryonic  \
0              0.000000               0.000000             0.000000
1              0.000000               0.466319             0.000000
2              0.000000               0.932638             0.196991
3              0.000000               0.932638             0.000000
4              0.000000               0.000000             0.000000
...                 ...                    ...                  ...
99991          0.776777               0.000000             0.393982
99992          1.553553               0.932638             0.590973
99993          0.000000               0.000000             0.196991
99994          0.000000               0.466319             0.787964
99995          0.776777               0.466319             0.196991

       Pulmonarydevel  Renal_cancer  StromalA  StromalB  Tissueinvariant  \
0                 0.0      0.000000       0.0  0.000000         0.785656
1                 0.0      0.000000       0.0  0.000000         0.000000
2                 0.0      0.000000       0.0  0.000000         0.000000
3                 0.0      0.000000       0.0  0.000000         0.000000
4                 0.0      0.000000       0.0  0.306419         0.000000
...               ...           ...       ...       ...              ...
99991             0.0      6.868034       0.0  1.225678         1.571313
99992             0.0      0.000000       0.0  0.612839         0.785656
99993             0.0      1.717009       0.0  1.532097         1.571313
99994             0.0      1.717009       0.0  0.306419         0.000000
99995             0.0      0.000000       0.0  0.000000         0.000000

       Vascular_endothelial
0                  0.000000
1                  0.000000
2                  0.000000
3                  0.000000
4                  0.000000
...                     ...
99991              1.462828
99992              2.925656
99993              1.462828
99994              1.462828
99995              0.000000

[99996 rows x 19 columns]

         seqname      start        end   0   1   2   3   4   5   6  ...  823  \
0           chr1          0        200  18  18  18  18  18  18  18  ...   18
1           chr1        200        400  18  18  18  18  18  18  18  ...   18
2           chr1        400        600  18  18  18  18  18  18  18  ...   18
3           chr1        600        800  18  18  18  18  18  18  18  ...   18
4           chr1        800       1000  18  18  18  18  18  18  18  ...   18
...          ...        ...        ...  ..  ..  ..  ..  ..  ..  ..  ...  ...
15181503    chrX  155269400  155269600  18  18  18  18  18  18  18  ...   18
15181504    chrX  155269600  155269800  18  18  18  18  18  18  18  ...   18
15181505    chrX  155269800  155270000  18  18  18  18  18  18  18  ...   18
15181506    chrX  155270000  155270200  18  18  18  18  18  18  18  ...   18
15181507    chrX  155270200  155270400  18  18  18  18  18  18  18  ...   18

          824  825  826  827  828  829  830  831  832
0          18   18   18   18   18   18   18   18   18
1          18   18   18   18   18   18   18   18   18
2          18   18   18   18   18   18   18   18   18
3          18   18   18   18   18   18   18   18   18
4          18   18   18   18   18   18   18   18   18
...       ...  ...  ...  ...  ...  ...  ...  ...  ...
15181503   18   18   18   18   18   18   18   18   18
15181504   18   18   18   18   18   18   18   18   18
15181505   18   18   18   18   18   18   18   18   18
15181506   18   18   18   18   18   18   18   18   18
15181507   18   18   18   18   18   18   18   18   18

[15181508 rows x 836 columns]
         seqname      start        end    1    2    3    4    5    6    7  \
0           chr1          0        200  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1           chr1        200        400  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2           chr1        400        600  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3           chr1        600        800  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4           chr1        800       1000  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...          ...        ...        ...  ...  ...  ...  ...  ...  ...  ...
15181503    chrX  155269400  155269600  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181504    chrX  155269600  155269800  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181505    chrX  155269800  155270000  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181506    chrX  155270000  155270200  0.0  0.0  0.0  0.0  0.0  0.0  0.0
15181507    chrX  155270200  155270400  0.0  0.0  0.0  0.0  0.0  0.0  0.0

          ...    9   10   11   12   13   14   15   16   17    18
0         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
1         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
2         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
3         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
4         ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...
15181503  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181504  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181505  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181506  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41
15181507  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.41

[15181508 rows x 21 columns]
    zero_index  one_index short_name                long_name      hex  \
0            0          1       TssA               Active TSS  #ff0000
1            1          2    TssFlnk             Flanking TSS  #ff4500
2            2          3   TssFlnkU    Flanking TSS Upstream  #ff4500
3            3          4   TssFlnkD  Flanking TSS Downstream  #ff4500
4            4          5         Tx     Strong transcription  #008000
5            5          6       TxWk       Weak transcription  #006400
6            6          7      EnhG1         Genic Enhancer 1  #c2e105
7            7          8      EnhG2         Genic Enhancer 2  #c2e105
8            8          9      EnhA1        Active Enhancer 1  #ffc34d
9            9         10      EnhA2        Active Enhancer 2  #ffc34d
10          10         11      EnhWk            Weak Enhancer  #ffff00
11          11         12   ZNF/Rpts      ZNF genes + repeats  #66cdaa
12          12         13        Het          Heterochromatin  #8a91d0
13          13         14     TssBiv      Bivalent/Poised TSS  #cd5c5c
14          14         15     EnhBiv        Bivalent Enhancer  #bdb76b
15          15         16     ReprPC       Repressed PolyComb  #808080
16          16         17   ReprPCWk  Weak Repressed PolyComb  #c0c0c0
17          17         18      Quies            Quiescent/Low  #ffffff

                   rgba              color
0       rgba(255,0,0,1)                Red
1      rgba(255,69,0,1)         Orange Red
2      rgba(255,69,0,1)         Orange Red
3      rgba(255,69,0,1)         Orange Red
4       rgba(0,128,0,1)              Green
5       rgba(0,100,0,1)          DarkGreen
6     rgba(194,225,5,1)        GreenYellow
7     rgba(194,225,5,1)        GreenYellow
8    rgba(255,195,77,1)             Orange
9    rgba(255,195,77,1)             Orange
10    rgba(255,255,0,1)             Yellow
11  rgba(102,205,170,1)  Medium Aquamarine
12  rgba(138,145,208,1)      PaleTurquoise
13    rgba(205,92,92,1)          IndianRed
14  rgba(189,183,107,1)          DarkKhaki
15  rgba(128,128,128,1)             Silver
16  rgba(192,192,192,1)          Gainsboro
17  rgba(255,255,255,1)              White
                                  protein2  neighborhood  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496             0
9606.ENSP00000000233  9606.ENSP00000314067             0
9606.ENSP00000000233  9606.ENSP00000263116             0
9606.ENSP00000000233  9606.ENSP00000361263             0
9606.ENSP00000000233  9606.ENSP00000409666             0
...                                    ...           ...
9606.ENSP00000485678  9606.ENSP00000321447             0
9606.ENSP00000485678  9606.ENSP00000308270             0
9606.ENSP00000485678  9606.ENSP00000335660             0
9606.ENSP00000485678  9606.ENSP00000300127             0
9606.ENSP00000485678  9606.ENSP00000310488             0

                      neighborhood_transferred  fusion  cooccurence  homology  \
protein1
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
9606.ENSP00000000233                         0       0            0         0
...                                        ...     ...          ...       ...
9606.ENSP00000485678                         0       0            0       888
9606.ENSP00000485678                         0       0            0       899
9606.ENSP00000485678                         0       0            0         0
9606.ENSP00000485678                         0       0            0       843
9606.ENSP00000485678                         0       0            0       898

                      coexpression  coexpression_transferred  experiments  \
protein1
9606.ENSP00000000233             0                        54            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233             0                        62            0
9606.ENSP00000000233             0                         0            0
9606.ENSP00000000233            60                        63            0
...                            ...                       ...          ...
9606.ENSP00000485678           214                        49            0
9606.ENSP00000485678           152                         0            0
9606.ENSP00000485678           182                         0            0
9606.ENSP00000485678           155                         0            0
9606.ENSP00000485678           168                         0            0

                      experiments_transferred  database  database_transferred  \
protein1
9606.ENSP00000000233                        0         0                     0
9606.ENSP00000000233                      180         0                     0
9606.ENSP00000000233                      152         0                     0
9606.ENSP00000000233                      161         0                     0
9606.ENSP00000000233                      213         0                     0
...                                       ...       ...                   ...
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0
9606.ENSP00000485678                        0         0                     0

                      textmining  textmining_transferred  combined_score  \
protein1
9606.ENSP00000000233         103                      85             155
9606.ENSP00000000233           0                      61             197
9606.ENSP00000000233           0                     101             222
9606.ENSP00000000233          47                      58             181
9606.ENSP00000000233           0                      72             270
...                          ...                     ...             ...
9606.ENSP00000485678           0                       0             220
9606.ENSP00000485678           0                       0             151
9606.ENSP00000485678           0                       0             181
9606.ENSP00000485678           0                       0             154
9606.ENSP00000485678           0                       0             167

                     protein1_pref protein2_pref
protein1
9606.ENSP00000000233          ARF5         PDE1C
9606.ENSP00000000233          ARF5          PAK2
9606.ENSP00000000233          ARF5         RAB36
9606.ENSP00000000233          ARF5       RAPGEF1
9606.ENSP00000000233          ARF5         SUMO3
...                            ...           ...
9606.ENSP00000485678         OR6Q1         OR4S1
9606.ENSP00000485678         OR6Q1         OR5B3
9606.ENSP00000485678         OR6Q1     KRTAP19-2
9606.ENSP00000485678         OR6Q1         OR4D6
9606.ENSP00000485678         OR6Q1         OR7D4

[10919872 rows x 17 columns]
              chr      start        end   4 strand                6      7  \
gene_names
ARF5         chr7  127228398  127231759   6      +  ENST00000000233    658
M6PR        chr12    9068355    9094058  17      +  ENST00000536844   6752
FKBP4       chr12    2904118    2913124  46      +  ENST00000001008   3720
CYP26B1      chr2   72356366   72375167  26      -  ENST00000001146  20581
NDUFAF7      chr2   37458805   37476303   5      +  ENST00000474154  28816
...           ...        ...        ...  ..    ...              ...    ...
CERS1       chr19   18988719   19007536   8      -  ENST00000542296  14253
ZNF518A     chr10   97889828   97965044   0      +  ENST00000563195  29009
SPATA31A5    chr9   90529407   90538572   0      +  ENST00000437823  32005
EIF3L       chr22   38244874   38285414   1      +  ENST00000412331  18138
OR6Q1       chr11   57798401   57799403   0      +  ENST00000302622  15302

                         8                                         descriptor  \
gene_names
ARF5        protein-coding                          ADP ribosylation factor 5
M6PR        protein-coding     mannose-6-phosphate receptor, cation dependent
FKBP4       protein-coding                            FKBP prolyl isomerase 4
CYP26B1     protein-coding     cytochrome P450 family 26 subfamily B member 1
NDUFAF7     protein-coding  NADH:ubiquinone oxidoreductase complex assembl...
...                    ...                                                ...
CERS1       protein-coding                                ceramide synthase 1
ZNF518A     protein-coding                           zinc finger protein 518A
SPATA31A5   protein-coding                       SPATA31 subfamily A member 5
EIF3L       protein-coding  eukaryotic translation initiation factor 3 sub...
OR6Q1       protein-coding  olfactory receptor family 6 subfamily Q member...

                   10         11  \
gene_names
ARF5        127228552  127231353
M6PR          9083081    9092055
FKBP4         2904305    2912424
CYP26B1      72359355   72374963
NDUFAF7      37476303   37476303
...               ...        ...
CERS1        18989734   19004339
ZNF518A      97965044   97965044
SPATA31A5    90538572   90538572
EIF3L        38245456   38284471
OR6Q1        57798424   57799378

                                                           12  \
gene_names
ARF5                                   221,81,110,72,126,493,
M6PR        310,162,111,81,150,24,56,493,269,148,212,115,1...
FKBP4                  292,145,143,121,157,91,84,186,240,808,
CYP26B1                             3382,285,156,276,225,408,
NDUFAF7                   98,161,81,111,1116,63,144,174,1026,
...                                                       ...
CERS1                               1129,148,162,181,160,167,
ZNF518A                                        47,85,93,1369,
SPATA31A5                                     218,94,61,3406,
EIF3L          615,49,211,80,62,70,74,172,155,171,498,81,982,
OR6Q1                                                   1002,

                                                           13
gene_names
ARF5                               0,738,1140,1721,2618,2868,
M6PR        0,1870,3996,5225,5841,6873,6973,14675,16803,18...
FKBP4         0,2185,2776,3753,4135,4897,5086,5439,6164,8198,
CYP26B1                         0,3785,5523,5906,14751,18393,
NDUFAF7         0,443,4433,6094,9915,12248,14389,15793,16472,
...                                                       ...
CERS1                           0,1330,2363,6176,15505,18650,
ZNF518A                                    0,2514,3484,73847,
SPATA31A5                                   0,4762,5423,5759,
EIF3L       0,1147,2412,6697,9811,14101,14404,21308,25502,...
OR6Q1                                                      0,

[18094 rows x 13 columns]

                                  protein2  neighborhood  fusion  cooccurence  \
protein1
9606.ENSP00000000233  9606.ENSP00000379496           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000314067           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000263116           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000361263           0.0     0.0          0.0
9606.ENSP00000000233  9606.ENSP00000409666           0.0     0.0          0.0
...                                    ...           ...     ...          ...
9606.ENSP00000469413  9606.ENSP00000397459           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000222399           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000215659           0.0     0.0        144.0
9606.ENSP00000469413  9606.ENSP00000305918           0.0     0.0          0.0
9606.ENSP00000469413  9606.ENSP00000265431           0.0     0.0          0.0

                      coexpression  experimental  database  textmining  \
protein1
9606.ENSP00000000233          54.0           0.0       0.0       144.0
9606.ENSP00000000233           0.0         180.0       0.0        61.0
9606.ENSP00000000233          62.0         152.0       0.0       101.0
9606.ENSP00000000233           0.0         161.0       0.0        64.0
9606.ENSP00000000233          82.0         213.0       0.0        72.0
...                            ...           ...       ...         ...
9606.ENSP00000469413           0.0         150.0       0.0        49.0
9606.ENSP00000469413          53.0           0.0     900.0         0.0
9606.ENSP00000469413           0.0         228.0       0.0        83.0
9606.ENSP00000469413         132.0          62.0       0.0         0.0
9606.ENSP00000469413          62.0         146.0       0.0        48.0

                      combined_score protein1_pref protein2_pref
protein1
9606.ENSP00000000233           155.0          ARF5         PDE1C
9606.ENSP00000000233           197.0          ARF5          PAK2
9606.ENSP00000000233           222.0          ARF5         RAB36
9606.ENSP00000000233           181.0          ARF5       RAPGEF1
9606.ENSP00000000233           270.0          ARF5         SUMO3
...                              ...           ...           ...
9606.ENSP00000469413           157.0          PAK4        DUSP22
9606.ENSP00000469413           901.0          PAK4         LAMB1
9606.ENSP00000469413           340.0          PAK4        MAPK12
9606.ENSP00000469413           151.0          PAK4          BRD3
9606.ENSP00000469413           170.0          PAK4         CALB1

[10538486 rows x 11 columns]

# 1kb

In [83]:
bins_1kb = pd.DataFrame()
for i in bins_25kb.index:
    temp_bins = pd.DataFrame()
    seqname = bins_25kb.loc[i]['seqname']
    start = bins_25kb.loc[i]['start']
    for j in range(25):
        index = i*25 +j
        temp_bins[index] = ([seqname, start, start+1000])
        start = start + 1000
    bins_1kb = pd.concat([bins_1kb, temp_bins.T], axis=0)
#     print(bins_1kb)
    if i % 100 == 0:
        print(i)
bins_1kb

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500
16600
16700
16800
16900
17000
17100
17200
17300
17400
17500
17600
17700
17800
17900
18000
18100
18200
18300
18400
18500
18600
18700
18800
18900
19000
19100
19200
19300
19400
19500
19600
19700
19800
19900
20000
20100
20200
20300
20400
20500
20600
20700
20800
20900
21000
21100
21200
21300
21400
21500
21600
21700
21800
21900
22000
22100
22200
22300
22400
22500
22600
22700
22800
22900
23000
23100
23200
23300
23400
23500
23600
23700
23800
23900
24000
24100
24200
24300
24400
24500
24600
24700
24800
24900
25000
25100
25200
25300
25400
25500
25600
25700
25800
25900
26000
26100
26200
26300
26400
26500
26600
26700
26800
26900
27000
27100
27200
27300
27400
27500
27600
27700
27800
27900
28000
28100
28200
28300
28400
28500
28600
28700
28800
28900
29000
29100
29200
29300
29400
29500
29600
29700
29800
29900
30000
30100
30200
30300
30400
30500
30600
30700
30800
30900
31000
31100
31200
31300
31400
31500
31600
31700
31800
31900
32000
32100
32200
32300
32400
32500
32600
32700
32800
32900
33000
33100
33200
33300
33400
33500
33600
33700
33800
33900
34000
34100
34200
34300
34400
34500
34600
34700
34800
34900
35000
35100
35200
35300
35400
35500
35600
35700
35800
35900
36000
36100
36200
36300
36400
36500
36600
36700
36800
36900
37000
37100
37200
37300
37400
37500
37600
37700
37800
37900
38000
38100
38200

KeyboardInterrupt:

In [ ]:
bins_1kb

In [6]:
# Use Specific Gene's closest regions to their start and end
gene = 'GATA1'

gene_chr = gene_hg19_bed.loc[gene].chr
gene_start = gene_hg19_bed.loc[gene].start
gene_end = gene_hg19_bed.loc[gene].end

print(gene_hg19_bed.loc[gene])
print(gene_start)
print(gene_end)
# print(bins_25kb[bins_25kb['seqname']==gene_chr].loc[96548])

print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)] & (bins_25kb['end'] >= gene_end))
# print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1])
# print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0])

# region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1]
region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0]

chr                                  chrX
start                            48644961
end                              48652715
4                                     200
strand                                  +
6                         ENST00000376670
7                                    4170
8                          protein-coding
descriptor         GATA binding protein 1
10                               48649516
11                               48652571
12                92,239,378,146,126,516,
13            0,4536,5289,5768,6617,7238,
Name: GATA1, dtype: object
48644961
48652715

KeyboardInterrupt:

In [ ]:
### USING A RANDOM REGION ###
rand_row = random.randint(0, len(bins_25kb))
rand_row
region = bins_25kb.iloc[rand_row]
print(region)

# 25kb

In [4]:
# Use Specific Gene's closest regions
gene = 'GATA1'

gene_chr = gene_hg19_bed.loc[gene].chr
gene_start = gene_hg19_bed.loc[gene].start
gene_end = gene_hg19_bed.loc[gene].end

print(gene_hg19_bed.loc[gene])
print(gene_start)
print(gene_end)
# print(bins_25kb[bins_25kb['seqname']==gene_chr].loc[96548])

print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1])
print(bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0])

# region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['start'] <= gene_start)].iloc[-1]
region = bins_25kb.loc[(bins_25kb['seqname'] == gene_chr) & (bins_25kb['end'] >= gene_end)].iloc[0]

chr                                  chrX
start                            48644961
end                              48652715
4                                     200
strand                                  +
6                         ENST00000376670
7                                    4170
8                          protein-coding
descriptor         GATA binding protein 1
10                               48649516
11                               48652571
12                92,239,378,146,126,516,
13            0,4536,5289,5768,6617,7238,
Name: GATA1, dtype: object
48644961
48652715
seqname        chrX
start      48583800
end        48608800
?           7.49548
Name: 96547, dtype: object
seqname        chrX
start      48647800
end        48672800
?           7.49905
Name: 96548, dtype: object

In [56]:
### USING A RANDOM REGION ###
rand_row = random.randint(0, len(bins_25kb))
rand_row
region = bins_25kb.iloc[rand_row]
print(region)

seqname        chr8
start      65632200
end        65657200
?           5.15043
Name: 87637, dtype: object

In [7]:
region_index = region.name
region_chr = region.seqname
region_start = region.start
region_end = region.end

In [92]:
### SNP ###

snp_chr = snp_df.loc[snp_df['Chromosome'] == region_chr]
snp_in_region = snp_chr[(snp_chr['p1'] >= region_start) & (snp_chr['p2'] <= region_end)]

trait_codes_temp = trait_codes_df.set_index(trait_codes_df['phenotype'])

snp_in_region['description'] = snp_in_region['phenotype'].map(trait_codes_temp['description'])
snp_in_region.sort_values(by='pvalue')['description']

/tmp/ipykernel_147156/3853771718.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  snp_in_region['description'] = snp_in_region['phenotype'].map(trait_codes_temp['description'])

2566016                  Job coding: printer, master printer
2934073                             Job SOC coding: Printers
1739839    Treatment/medication code: isotard 25xl m/r ta...
8937313                   Mean platelet (thrombocyte) volume
1494527         Treatment/medication code: otomize ear spray
4017819        Diagnoses - main ICD10: C81 Hodgkin's disease
2442517    Job coding: personnel or industrial relations ...
2442518    Job coding: personnel or industrial relations ...
4241220    Diagnoses - main ICD10: G12 Spinal muscular at...
3954636                       Malignant neoplasm of pancreas
3861423                       Malignant neoplasm of pancreas
2223163    Job coding: financial services manager, charte...
2223162    Job coding: financial services manager, charte...
2705400    Job SOC coding: Financial managers and charter...
2705399    Job SOC coding: Financial managers and charter...
2374008    Job coding: medical radiographer, x-ray operat...
2814423                Job SOC coding: Medical radiographers
1364253     Treatment/medication code: epanutin 25mg capsule
4475727    Diagnoses - main ICD10: I27 Other pulmonary he...
4074615                  Idiopathic thrombocytopenic purpura
2518516    Job coding: tool maker, tool fitter, jig and t...
2909635    Job SOC coding: Tool makers, tool fitters and ...
2938658    Job SOC coding: Furniture makers, other craft ...
2283659    Job coding: electrical engineer, generating en...
9517958                               Eosinophill percentage
4264370                                 Motor neuron disease
Name: description, dtype: object

In [59]:
trait_codes_df

,phenotype,description,variable_type,source,n_non_missing,n_missing,n_controls,n_cases,PHESANT_transformation,notes
0,G54,Diagnoses - main ICD10: G54 Nerve root and ple...,categorical,icd10,361194,0,361051,143,NA,NA
1,C21,Diagnoses - main ICD10: C21 Malignant neoplasm...,categorical,icd10,361194,0,361055,139,NA,NA
2,F45,Diagnoses - main ICD10: F45 Somatoform disorders,categorical,icd10,361194,0,360953,241,NA,NA
3,I35,Diagnoses - main ICD10: I35 Nonrheumatic aorti...,categorical,icd10,361194,0,360293,901,NA,NA
4,D38,Diagnoses - main ICD10: D38 Neoplasm of uncert...,categorical,icd10,361194,0,361087,107,NA,NA
...,...,...,...,...,...,...,...,...,...,...
4354,100023_raw,Starch,continuous_raw,phesant,51453,309741,NA,NA,100023_0|| CONTINUOUS MAIN || CONTINUOUS || ||,"Starch. Estimated intake, based on food and be..."
4355,100024_raw,Calcium,continuous_raw,phesant,51453,309741,NA,NA,100024_0|| CONTINUOUS MAIN || CONTINUOUS || ||,"Calcium. Estimated intake, based on food and b..."
4356,100025_raw,Vitamin E,continuous_raw,phesant,51453,309741,NA,NA,100025_0|| CONTINUOUS MAIN || CONTINUOUS || ||,"Vitamin E. Estimated intake, based on food and..."
4357,is_female,"is_female, based on inferred genetic sex",categorical,covariate,361194,0,167020,194174,NA,NA
4358,age,Age at recruitment,continuous_raw,covariate,361194,0,NA,NA,NA,NA

In [5]:
### TF ###
motif_counts_df = pd.read_pickle('../data/motif_counts_df_25kb.pkl')
motif_counts_df.iloc[:, 3:] = motif_counts_df.iloc[:, 3:].astype(int)

bin_cols = ['seqname', 'start', 'end', '?']
bins_25kb = pd.read_csv('../data/Altius_100k_epilogos_hg19_WM20210518.bed', delimiter='\t', names=bin_cols)
print(bins_25kb)

# motif_counts_chr = motif_counts_df[motif_counts_df['seqname'] == region_chr]
# motif_sub = motif_counts_chr.loc[(motif_counts_chr['start'] >= region_start) & (motif_counts_chr['end'] <= region_end)] 
# print(motif_sub)


total_tf_cluster_counts_expected = motif_counts_df.iloc[:, 3:].sum(axis=0)/len(bins_25kb)
# print(motif_sub.iloc[:, 3:])

# (np.log2(motif_sub.iloc[:, 3:]/total_tf_cluster_counts_expected)).T

motif_enrichment = (np.log2(motif_counts_df.iloc[:, 3:]/total_tf_cluster_counts_expected))
print(motif_enrichment)
print(motif_counts_df.iloc[:, :3])

motif_enrichment = pd.concat([motif_counts_df.iloc[:, :3], motif_enrichment], axis=1)
print(motif_enrichment)

motif_enrichment.to_pickle('../data/motif_log2_enrichment.pkl')

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]
            AHR      AIRE     AP1_1     AP1_2     ARI5A     ARI5B      BATF  \
0      0.940513  0.782845 -0.316858  0.755815 -0.981118 -0.449452 -0.516992
1          -inf  0.782845  0.217478 -0.393048  0.018882 -0.449452  0.120438
2     -0.644449  0.782845 -0.419952 -0.524293 -0.396155 -0.034414 -1.101954
3      0.677479 -0.217155  0.410123  0.212673  0.018882  0.550548  0.120438
4          -inf -1.217155 -0.087376  0.509654  0.826237  0.772941 -0.101954
...         ...       ...       ...       ...       ...       ...       ...
99991  0.355551 -0.632193  0.348723  0.331317 -0.396155 -0.449452  0.120438
99992  1.162906  0.104773 -0.267949 -0.457179  1.018882 -0.034414  0.013523
99993 -0.059487  0.590200 -0.174839  0.170853  0.018882 -0.449452 -0.364989
99994  0.355551  0.104773 -0.267949 -0.594682  0.018882 -0.034414 -0.879562
99995  0.355551  0.367807 -1.087376 -0.668683 -0.396155 -0.034414 -0.879562

         BCL6_1    BCL6_2  CCAAT_CEBP  ...    ZNF652    ZNF667    ZNF680  \
0          -inf  0.726241   -0.499314  ... -0.332600  1.177511  0.602383
1          -inf  0.034363    0.178758  ... -0.332600 -0.922025 -0.204972
2          -inf  0.034363    0.841723  ... -0.332600 -0.729380  0.602383
3      0.098494  1.034363    0.638190  ...  0.667400 -0.559455  0.602383
4      1.098494  0.141278    0.053227  ... -0.917562  0.794182  0.495468
...         ...       ...         ...  ...       ...       ...       ...
99991  1.098494 -0.081114    0.237652  ...  0.889793  0.270620 -0.397617
99992  1.098494  0.240814    0.451776  ...  0.082438  0.358083  0.116957
99993  0.098494  0.141278    0.547992  ...  0.667400 -0.269948 -0.397617
99994      -inf  0.034363    0.117357  ...  0.082438  0.592548 -0.397617
99995  0.098494 -0.344149   -0.499314  ... -0.332600 -0.922025 -0.035047

         ZNF708    ZNF713    ZNF768    ZNF784     ZNF85    ZSCAN3    ZSCAN4
0      1.871040      -inf  1.339572  0.485744 -0.213453  1.370299  0.189086
1     -1.673281 -0.010709  0.252110 -0.099218 -0.097975 -0.025630  0.101624
2      0.063685 -0.010709 -0.162928 -0.514256  0.661016 -1.103632 -0.898376
3      0.063685      -inf  0.126579 -0.099218 -0.213453  0.118760  1.311077
4      0.201188  0.574254 -0.332853  0.222710 -0.097975  0.770837 -1.091021
...         ...       ...       ...       ...       ...       ...       ...
99991  0.201188 -1.010709  0.126579  0.900782 -0.628490 -0.186094 -0.576448
99992  0.201188  0.574254  0.837072 -0.514256 -0.338984  0.584424  0.008514
99993 -0.258243 -0.010709 -1.010925 -1.099218 -0.338984 -1.273557 -0.197937
99994 -0.450889  0.574254 -0.010925 -0.099218 -0.338984 -0.103632  0.493941
99995  0.326719      -inf -0.332853 -0.514256  0.201585 -0.366667 -1.091021

[99996 rows x 282 columns]
      seqname      start        end
0        chr1       9000      34000
1        chr1      34000      59000
2        chr1      61000      86000
3        chr1      86000     111000
4        chr1     111000     136000
...       ...        ...        ...
99991    chrX  155042800  155067800
99992    chrX  155067800  155092800
99993    chrX  155092800  155117800
99994    chrX  155117800  155142800
99995    chrX  155142800  155167800

[99996 rows x 3 columns]
      seqname      start        end       AHR      AIRE     AP1_1     AP1_2  \
0        chr1       9000      34000  0.940513  0.782845 -0.316858  0.755815
1        chr1      34000      59000      -inf  0.782845  0.217478 -0.393048
2        chr1      61000      86000 -0.644449  0.782845 -0.419952 -0.524293
3        chr1      86000     111000  0.677479 -0.217155  0.410123  0.212673
4        chr1     111000     136000      -inf -1.217155 -0.087376  0.509654
...       ...        ...        ...       ...       ...       ...       ...
99991    chrX  155042800  155067800  0.355551 -0.632193  0.348723  0.331317
99992    chrX  155067800  155092800  1.162906  0.104773 -0.267949 -0.457179
99993    chrX  155092800  155117800 -0.059487  0.590200 -0.174839  0.170853
99994    chrX  155117800  155142800  0.355551  0.104773 -0.267949 -0.594682
99995    chrX  155142800  155167800  0.355551  0.367807 -1.087376 -0.668683

          ARI5A     ARI5B      BATF  ...    ZNF652    ZNF667    ZNF680  \
0     -0.981118 -0.449452 -0.516992  ... -0.332600  1.177511  0.602383
1      0.018882 -0.449452  0.120438  ... -0.332600 -0.922025 -0.204972
2     -0.396155 -0.034414 -1.101954  ... -0.332600 -0.729380  0.602383
3      0.018882  0.550548  0.120438  ...  0.667400 -0.559455  0.602383
4      0.826237  0.772941 -0.101954  ... -0.917562  0.794182  0.495468
...         ...       ...       ...  ...       ...       ...       ...
99991 -0.396155 -0.449452  0.120438  ...  0.889793  0.270620 -0.397617
99992  1.018882 -0.034414  0.013523  ...  0.082438  0.358083  0.116957
99993  0.018882 -0.449452 -0.364989  ...  0.667400 -0.269948 -0.397617
99994  0.018882 -0.034414 -0.879562  ...  0.082438  0.592548 -0.397617
99995 -0.396155 -0.034414 -0.879562  ... -0.332600 -0.922025 -0.035047

         ZNF708    ZNF713    ZNF768    ZNF784     ZNF85    ZSCAN3    ZSCAN4
0      1.871040      -inf  1.339572  0.485744 -0.213453  1.370299  0.189086
1     -1.673281 -0.010709  0.252110 -0.099218 -0.097975 -0.025630  0.101624
2      0.063685 -0.010709 -0.162928 -0.514256  0.661016 -1.103632 -0.898376
3      0.063685      -inf  0.126579 -0.099218 -0.213453  0.118760  1.311077
4      0.201188  0.574254 -0.332853  0.222710 -0.097975  0.770837 -1.091021
...         ...       ...       ...       ...       ...       ...       ...
99991  0.201188 -1.010709  0.126579  0.900782 -0.628490 -0.186094 -0.576448
99992  0.201188  0.574254  0.837072 -0.514256 -0.338984  0.584424  0.008514
99993 -0.258243 -0.010709 -1.010925 -1.099218 -0.338984 -1.273557 -0.197937
99994 -0.450889  0.574254 -0.010925 -0.099218 -0.338984 -0.103632  0.493941
99995  0.326719      -inf -0.332853 -0.514256  0.201585 -0.366667 -1.091021

[99996 rows x 285 columns]

In [63]:
### DHS ###
# Which DHSs are in the region
dhs_metadata_chr = dhs_df[dhs_df['seqname'] == region_chr]
dhs_metadata_region = dhs_metadata_chr.loc[(dhs_metadata_chr['start'] >= region_start) & (dhs_metadata_chr['end'] <= region_end)] 
# print(dhs_metadata_region)

# Component Enrichments in the region (obs/exp) # NOT LOG2 - empty values filled with 0
print(dhs_obs_over_exp.loc[region_index].iloc[3:])

# Average mean signal of DHSs
average_mean_signal = dhs_metadata_region['mean_signal'].mean()
print(average_mean_signal)

# Number of DHSs
print(len(dhs_metadata_region))

Cancer / epithelial        0.530514
Cardiac                         0.0
Digestive                  1.382296
Lymphoid                   1.427535
Musculoskeletal            0.461036
Myeloid / erythroid        1.071677
Neural                     1.300118
Organ devel. / renal       1.256728
Placental / trophoblast    2.641603
Primitive / embryonic        0.4788
Pulmonary devel.                0.0
Renal / cancer             3.469987
Stromal A                       0.0
Stromal B                       0.0
Tissue invariant           6.976318
Vascular / endothelial          0.0
Name: 87637, dtype: object
1.1422072457644274
44

In [19]:
### EPILOGOS ###
epilogos_chr = epilogos_states_df[epilogos_states_df['seqname'] == region_chr]
epilogos_in_region = epilogos_chr[(epilogos_chr['start'] >= region_start) & (epilogos_chr['end'] <= region_end)]
print(epilogos_in_region)


epilogos_region = epilogos_in_region.loc[:,list(range(1,19))].mean(axis=0)
# epilogos_region

epilogos_metadata_sub = epilogos_metadata[['one_index', 'short_name', 'long_name']]
epilogos_metadata_sub.set_index(epilogos_metadata_sub['one_index'], inplace=True)

epilogos_metadata_sub['score'] = epilogos_region
epilogos_metadata_sub

         seqname     start       end         1         2        3         4  \
14648395    chrX  48647800  48648000 -0.002432  0.012880  0.02569  0.022570
14648396    chrX  48648000  48648200 -0.002416  0.005777  0.02170  0.017740
14648397    chrX  48648200  48648400 -0.002432 -0.000957  0.02170  0.013210
14648398    chrX  48648400  48648600 -0.000062  0.002838  0.01427  0.002109
14648399    chrX  48648600  48648800 -0.002432  0.030310  0.00000 -0.000146
...          ...       ...       ...       ...       ...      ...       ...
14648515    chrX  48671800  48672000  0.000000  0.000000  0.00000  0.000000
14648516    chrX  48672000  48672200  0.000000  0.000000  0.00000  0.000000
14648517    chrX  48672200  48672400  0.000000  0.000000  0.00000  0.000000
14648518    chrX  48672400  48672600  0.000000  0.000000  0.00000  0.000000
14648519    chrX  48672600  48672800  0.000000  0.000000  0.00000  0.000000

                 5        6         7  ...         9        10        11  \
14648395  0.000000 -0.02502  0.000000  ...  0.000000 -0.003642  0.067700
14648396  0.000000 -0.02243  0.000000  ...  0.000000 -0.003642  0.113000
14648397  0.000000 -0.02733  0.000000  ... -0.003248 -0.003642  0.095870
14648398  0.000000 -0.03681  0.000000  ... -0.003248  0.000000  0.014640
14648399  0.000000 -0.03955  0.000000  ... -0.003248  0.000000 -0.000732
...            ...      ...       ...  ...       ...       ...       ...
14648515 -0.007325  1.57400 -0.000316  ...  0.000000 -0.003642  0.000000
14648516  0.005795  1.50300 -0.000316  ...  0.000000 -0.001169  0.000000
14648517  0.026370  1.44800 -0.000316  ...  0.000000 -0.002481 -0.005373
14648518  0.039790  1.43800 -0.000316  ...  0.000000 -0.002481 -0.003887
14648519  0.057430  1.41300 -0.000316  ...  0.000000 -0.001169  0.000000

                12        13   14   15        16       17       18
14648395 -0.004631 -0.017890  0.0  0.0  0.010160  0.32740 -0.04731
14648396 -0.004631 -0.017890  0.0  0.0  0.010160  0.29940 -0.04400
14648397 -0.004631 -0.017890  0.0  0.0  0.007809  0.25680 -0.01709
14648398 -0.004631 -0.017890  0.0  0.0 -0.003291  0.25680  0.02815
14648399 -0.004631 -0.017890  0.0  0.0 -0.003291  0.22310  0.05873
...            ...       ...  ...  ...       ...      ...      ...
14648515 -0.003642 -0.009186  0.0  0.0  0.000000 -0.02225 -0.36550
14648516  0.004721  0.000000  0.0  0.0 -0.006448 -0.01745 -0.36550
14648517  0.007009  0.000000  0.0  0.0 -0.006448 -0.01745 -0.36550
14648518  0.007009  0.000000  0.0  0.0 -0.006330 -0.01551 -0.36550
14648519  0.002607 -0.005793  0.0  0.0 -0.006448 -0.01551 -0.36620

[125 rows x 21 columns]

/tmp/ipykernel_90792/3882697906.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  epilogos_metadata_sub['score'] = epilogos_region

           one_index short_name                long_name         score
one_index
1                  1       TssA               Active TSS  4.754877e-01
2                  2    TssFlnk             Flanking TSS  4.789110e-02
3                  3   TssFlnkU    Flanking TSS Upstream  1.477751e-01
4                  4   TssFlnkD  Flanking TSS Downstream  1.464048e-02
5                  5         Tx     Strong transcription  2.432579e-02
6                  6       TxWk       Weak transcription  6.841416e-01
7                  7      EnhG1         Genic Enhancer 1  9.729920e-04
8                  8      EnhG2         Genic Enhancer 2  2.963360e-04
9                  9      EnhA1        Active Enhancer 1  2.648324e-02
10                10      EnhA2        Active Enhancer 2  1.320237e-02
11                11      EnhWk            Weak Enhancer  2.691050e-02
12                12   ZNF/Rpts      ZNF genes + repeats -3.069479e-03
13                13        Het          Heterochromatin -1.324908e-02
14                14     TssBiv      Bivalent/Poised TSS -7.616160e-05
15                15     EnhBiv        Bivalent Enhancer  3.568000e-08
16                16     ReprPC       Repressed PolyComb -1.338466e-03
17                17   ReprPCWk  Weak Repressed PolyComb  2.526618e-02
18                18      Quies            Quiescent/Low -1.620592e-01

In [129]:
epilogos_metadata

,zero_index,one_index,short_name,long_name,hex,rgba,color
0,0,1,TssA,Active TSS,#ff0000,"rgba(255,0,0,1)",Red
1,1,2,TssFlnk,Flanking TSS,#ff4500,"rgba(255,69,0,1)",Orange Red
2,2,3,TssFlnkU,Flanking TSS Upstream,#ff4500,"rgba(255,69,0,1)",Orange Red
3,3,4,TssFlnkD,Flanking TSS Downstream,#ff4500,"rgba(255,69,0,1)",Orange Red
4,4,5,Tx,Strong transcription,#008000,"rgba(0,128,0,1)",Green
5,5,6,TxWk,Weak transcription,#006400,"rgba(0,100,0,1)",DarkGreen
6,6,7,EnhG1,Genic Enhancer 1,#c2e105,"rgba(194,225,5,1)",GreenYellow
7,7,8,EnhG2,Genic Enhancer 2,#c2e105,"rgba(194,225,5,1)",GreenYellow
8,8,9,EnhA1,Active Enhancer 1,#ffc34d,"rgba(255,195,77,1)",Orange
9,9,10,EnhA2,Active Enhancer 2,#ffc34d,"rgba(255,195,77,1)",Orange
10,10,11,EnhWk,Weak Enhancer,#ffff00,"rgba(255,255,0,1)",Yellow
11,11,12,ZNF/Rpts,ZNF genes + repeats,#66cdaa,"rgba(102,205,170,1)",Medium Aquamarine
12,12,13,Het,Heterochromatin,#8a91d0,"rgba(138,145,208,1)",PaleTurquoise
13,13,14,TssBiv,Bivalent/Poised TSS,#cd5c5c,"rgba(205,92,92,1)",IndianRed
14,14,15,EnhBiv,Bivalent Enhancer,#bdb76b,"rgba(189,183,107,1)",DarkKhaki
15,15,16,ReprPC,Repressed PolyComb,#808080,"rgba(128,128,128,1)",Silver
16,16,17,ReprPCWk,Weak Repressed PolyComb,#c0c0c0,"rgba(192,192,192,1)",Gainsboro
17,17,18,Quies,Quiescent/Low,#ffffff,"rgba(255,255,255,1)",White

In [37]:
### GENE ###
gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]
print(genes_in_region)

print(region_start, region_end)

             chr     start       end    4 strand                6      7  \
gene_names
HDAC6       chrX  48660401  48683386  212      +  ENST00000334136  14064
GATA1       chrX  48644961  48652715  200      +  ENST00000376670   4170

                         8              descriptor        10        11  \
gene_names
HDAC6       protein-coding   histone deacetylase 6  48661099  48683022
GATA1       protein-coding  GATA binding protein 1  48649516  48652571

                                                           12  \
gene_names
HDAC6       148,123,129,89,85,41,97,98,105,69,127,66,60,90...
GATA1                                 92,239,378,146,126,516,

                                                           13
gene_names
HDAC6       0,668,876,1133,3443,3636,4373,4614,6038,6263,1...
GATA1                             0,4536,5289,5768,6617,7238,
48647800 48672800

In [238]:
# Extra gene tester
gene2_start = gene_hg19_bed.loc['PPP1R3F'].start
gene2_end = gene_hg19_bed.loc['PPP1R3F'].end
dhs_metadata_chr = dhs_df[dhs_df['seqname'] == 'chrX']
dhs_metadata_region = dhs_metadata_chr.loc[(dhs_metadata_chr['start'] >= region_start) & (dhs_metadata_chr['end'] <= region_end)] 
print(dhs_metadata_region.component.sort_values(ascending=False))

identifier
X.380685    Vascular / endothelial
X.38053           Tissue invariant
X.380682                 Stromal B
X.380678            Renal / cancer
X.380691            Renal / cancer
X.38065      Primitive / embryonic
X.380662     Primitive / embryonic
X.38054      Primitive / embryonic
X.38059                     Neural
X.380675                    Neural
X.380695       Myeloid / erythroid
X.380688       Myeloid / erythroid
X.38064        Myeloid / erythroid
X.380668       Myeloid / erythroid
X.38056            Musculoskeletal
X.380698                  Lymphoid
X.380671                  Lymphoid
X.38062                   Lymphoid
X.38061                  Digestive
X.38058                  Digestive
X.38055                  Digestive
X.380665                 Digestive
Name: component, dtype: object

In [67]:
### STRING ###
protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
print(protein_assoc_hg19.shape)

protein_assoc_hg19.index = protein_assoc_hg19['protein1_pref']

columns = ['coexpression', 'experimental', 'database', 'textmining']
subscores = protein_assoc_hg19[columns]
print(subscores.shape)

subscores_600 = subscores.loc[subscores.max(axis=1) > 150]

(10538486, 11)
(10538486, 4)

In [68]:
genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
subscores_count = pd.DataFrame()
for col in genes_in_region_assoc.columns:
    column = genes_in_region_assoc[col]
    subscores_count[col] = [len(column[column > 150])]
print(subscores_count.T)

                 0
coexpression    54
experimental   947
database       177
textmining    2140

In [66]:
protein_assoc_hg19.combined_score.min()

150.0

In [85]:
def create_region_vector():
    region_vector = []
    tf_arr = np.array(tf_vector(region_chr, region_start, region_end).iloc[0, 3:])
    dhs_arr = dhs_vector(region_chr, region_start, region_end)
    epilogos_arr = np.array(epilogos_vector(region_chr, region_start, region_end))
    # print(gene_vector(region_chr, region_start, region_end).tolist())
    gene_arr = gene_vector(region_chr, region_start, region_end).tolist()
    region_vector = np.concatenate((tf_arr, dhs_arr, epilogos_arr, gene_arr))
    return region_vector

322

In [84]:
def tf_vector(region_chr, region_start, region_end):
    motif_enrichment_chr = motif_enrichment[motif_enrichment['seqname'] == region_chr]
    motif_enrichment_region = motif_enrichment_chr.loc[(motif_enrichment_chr['start'] >= region_start) & (motif_enrichment_chr['end'] <= region_end)] 
    
    return motif_enrichment_region

def dhs_vector(region_chr, region_start, region_end):
    # Which DHSs are in the region
    dhs_metadata_chr = dhs_df[dhs_df['seqname'] == region_chr]
    dhs_metadata_region = dhs_metadata_chr.loc[(dhs_metadata_chr['start'] >= region_start) & (dhs_metadata_chr['end'] <= region_end)] 

#     # Component Enrichments in the region (obs/exp) # NOT LOG2 - empty values filled with 0
#     dhs_obs_over_exp_chr = dhs_obs_over_exp[dhs_obs_over_exp['seqname'] == region_chr]
#     dhs_obs_over_exp_region = dhs_obs_over_exp_chr.loc[(dhs_obs_over_exp_chr['start'] >= region_start) & (dhs_obs_over_exp_chr['end'] <= region_end)] 


    # Average mean signal of DHSs
    average_mean_signal = dhs_metadata_region['mean_signal'].mean()

    # Number of DHSs
    num_dhs = len(dhs_metadata_region)

    dhs_vector = [average_mean_signal, num_dhs]
    dhs_vector.extend(dhs_obs_over_exp_region.iloc[:, 3:].T.iloc[:, 0].tolist())
    
    del dhs_metadata_chr, dhs_metadata_region, dhs_obs_over_exp_chr, dhs_obs_over_exp_region
    
    return dhs_vector

def epilogos_vector(region_chr, region_start, region_end):
    epilogos_chr = epilogos_states_df[epilogos_states_df['seqname'] == region_chr]
    epilogos_in_region = epilogos_chr[(epilogos_chr['start'] >= region_start) & (epilogos_chr['end'] <= region_end)]

    epilogos_region = epilogos_in_region.loc[:,list(range(1,19))].mean(axis=0)
    return epilogos_region

def gene_vector(region_chr, region_start, region_end):
    gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
    genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]

    protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
    protein_assoc_hg19.index = protein_assoc_hg19['protein1_pref']

    columns = ['coexpression', 'experimental', 'database', 'textmining']
    subscores = protein_assoc_hg19[columns]

    subscores_600 = subscores.loc[subscores.max(axis=1) > 150]

    genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
    # Get mean of the subscores of gene associations
    return genes_in_region_assoc.mean(axis=0)

In [73]:
genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
print(genes_in_region_assoc.mean(axis=0).tolist())

[31.261652542372882, 106.93538135593221, 44.38559322033898, 232.82909604519773]

In [89]:
# gene_chr = gene_hg19_bed.loc[gene_hg19_bed['chr'] == region_chr]
# genes_in_region = gene_chr[((gene_chr['start'] >= region_start) & (gene_chr['start'] <= region_end)) | ((gene_chr['end'] <= region_end) & (gene_chr['end'] >= region_start))]

protein_assoc_hg19 = pd.read_pickle('../data/hg19-protein-associations-detailed.pkl')
protein_assoc_hg19.index = protein_assoc_hg19['protein1_pref']

columns = ['coexpression', 'experimental', 'database', 'textmining']
subscores = protein_assoc_hg19[columns]

subscores_600 = subscores.loc[subscores.max(axis=1) > 150]

total = pd.DataFrame()

for gene in genes_in_region.index.tolist():
    if gene in subscores_600.index:
        genes_in_region_assoc = subscores_600.loc[genes_in_region.index]
        total = pd.concat([total, genes_in_region_assoc], axis=0)

# Get mean of the subscores of gene associations
print(total.mean(axis=0))

coexpression     31.261653
experimental    106.935381
database         44.385593
textmining      232.829096
dtype: float64

In [91]:
print(subscores_600.index)

Index(['ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5', 'ARF5',
       'ARF5',
       ...
       'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4', 'PAK4',
       'PAK4'],
      dtype='object', name='protein1_pref', length=8352353)

In [95]:
gene_hg19_bed_STRING = gene_hg19_bed.loc[protein_assoc_hg19.index]
gene_hg19_bed_STRING

,chr,start,end,4,strand,6,7,8,descriptor,10,11,12,13
protein1_pref,,,,,,,,,,,,,
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
ARF5,chr7,127228398,127231759,6,+,ENST00000000233,658,protein-coding,ADP ribosylation factor 5,127228552,127231353,"221,81,110,72,126,493,","0,738,1140,1721,2618,2868,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."
PAK4,chr19,39616473,39673456,92,+,ENST00000599386,16059,protein-coding,p21 (RAC1) activated kinase 4,39660193,39669219,"86,73,226,435,134,127,126,135,4393,","0,42396,43698,47742,49097,49478,50756,51841,52..."

In [96]:
## Get Cosine Similarity 
region_vectors_25kb_df = pd.read_pickle('../output/25kb_region_vectors.pkl')

for i in range(len(region_vectors_25kb_df)):

In [98]:
motif_enrichment = pd.read_pickle('../data/motif_log2_enrichment.pkl')
dhs_df = pd.read_pickle('../data/dhs_metadata.pkl')
epilogos_states_df = pd.read_pickle('../data/epilogos_states_df')

motif_enrichment_bed = BedTool.from_dataframe(motif_enrichment)
dhs_bed = BedTool.from_dataframe(dhs_df)
epilogos_states_bed = BedTool.from_dataframe(epilogos_states_df)

motif_enrichment_bed.saveas('../data/motif_enrichment_bed.bed')
dhs_bed.saveas('../data/dhs_bed.bed')
epilogos_states_bed.saveas('../data/epilogos_states_bed.bed')

In [99]:
motif_enrichment

,seqname,start,end,AHR,AIRE,AP1_1,AP1_2,ARI5A,ARI5B,BATF,...,ZNF652,ZNF667,ZNF680,ZNF708,ZNF713,ZNF768,ZNF784,ZNF85,ZSCAN3,ZSCAN4
0,chr1,9000,34000,0.940513,0.782845,-0.316858,0.755815,-0.981118,-0.449452,-0.516992,...,-0.332600,1.177511,0.602383,1.871040,-inf,1.339572,0.485744,-0.213453,1.370299,0.189086
1,chr1,34000,59000,-inf,0.782845,0.217478,-0.393048,0.018882,-0.449452,0.120438,...,-0.332600,-0.922025,-0.204972,-1.673281,-0.010709,0.252110,-0.099218,-0.097975,-0.025630,0.101624
2,chr1,61000,86000,-0.644449,0.782845,-0.419952,-0.524293,-0.396155,-0.034414,-1.101954,...,-0.332600,-0.729380,0.602383,0.063685,-0.010709,-0.162928,-0.514256,0.661016,-1.103632,-0.898376
3,chr1,86000,111000,0.677479,-0.217155,0.410123,0.212673,0.018882,0.550548,0.120438,...,0.667400,-0.559455,0.602383,0.063685,-inf,0.126579,-0.099218,-0.213453,0.118760,1.311077
4,chr1,111000,136000,-inf,-1.217155,-0.087376,0.509654,0.826237,0.772941,-0.101954,...,-0.917562,0.794182,0.495468,0.201188,0.574254,-0.332853,0.222710,-0.097975,0.770837,-1.091021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99991,chrX,155042800,155067800,0.355551,-0.632193,0.348723,0.331317,-0.396155,-0.449452,0.120438,...,0.889793,0.270620,-0.397617,0.201188,-1.010709,0.126579,0.900782,-0.628490,-0.186094,-0.576448
99992,chrX,155067800,155092800,1.162906,0.104773,-0.267949,-0.457179,1.018882,-0.034414,0.013523,...,0.082438,0.358083,0.116957,0.201188,0.574254,0.837072,-0.514256,-0.338984,0.584424,0.008514
99993,chrX,155092800,155117800,-0.059487,0.590200,-0.174839,0.170853,0.018882,-0.449452,-0.364989,...,0.667400,-0.269948,-0.397617,-0.258243,-0.010709,-1.010925,-1.099218,-0.338984,-1.273557,-0.197937
99994,chrX,155117800,155142800,0.355551,0.104773,-0.267949,-0.594682,0.018882,-0.034414,-0.879562,...,0.082438,0.592548,-0.397617,-0.450889,0.574254,-0.010925,-0.099218,-0.338984,-0.103632,0.493941
99995,chrX,155142800,155167800,0.355551,0.367807,-1.087376,-0.668683,-0.396155,-0.034414,-0.879562,...,-0.332600,-0.922025,-0.035047,0.326719,-inf,-0.332853,-0.514256,0.201585,-0.366667,-1.091021

In [119]:
dhs_ms_num = pd.DataFrame()
for i in tqdm(range(len(bins_25kb))):
    region_chr = bins_25kb.iloc[i, 0]
    region_start = bins_25kb.iloc[i, 1]
    region_end = bins_25kb.iloc[i, 2]
#     print(region_chr, region_start, region_end)

    new_vector = dhs_vector(region_chr, region_start, region_end)
    dhs_ms_num[i] = new_vector
dhs_ms_num

  0%|▏                                                                                                                                                                                                                  | 100/99996 [00:21<5:54:52,  4.69it/s]/tmp/ipykernel_10193/586572900.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  dhs_ms_num[i] = new_vector
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 99996/99996 [5:48:35<00:00,  4.78it/s]

,0,1,2,3,4,5,6,7,8,9,...,99986,99987,99988,99989,99990,99991,99992,99993,99994,99995
0,0.129388,0.176642,0.167473,0.148034,0.079265,0.203499,0.498372,0.176563,NaN,NaN,...,0.368483,0.202598,0.474190,0.445144,0.745700,0.616913,0.497687,0.320222,0.340393,0.360654
1,1.000000,2.000000,4.000000,6.000000,3.000000,1.000000,5.000000,7.000000,0.0,0.0,...,13.000000,13.000000,29.000000,19.000000,28.000000,30.000000,26.000000,20.000000,17.000000,13.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.654274,0.0,0.0,...,0.654274,1.308548,1.308548,0.000000,1.308548,0.654274,1.308548,1.962823,0.654274,3.271371
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,1.043255,5.216275,1.043255,0.000000,2.086510,1.043255,0.000000,1.043255
4,0.000000,0.000000,0.857702,0.857702,0.857702,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,1.715403,0.857702,1.715403,0.857702,0.857702,0.000000
5,0.000000,0.000000,0.000000,0.441178,0.441178,0.000000,0.882355,0.000000,0.0,0.0,...,0.000000,0.882355,3.529421,0.441178,0.882355,0.882355,0.882355,0.441178,0.000000,0.882355
6,0.000000,0.000000,0.000000,0.569736,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.569736,2.278942,0.569736,1.139471,0.569736,0.569736,0.569736,0.569736
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.663350,0.000000,0.663350,0.0,0.0,...,1.326700,0.663350,0.663350,1.326700,1.990049,1.990049,2.653399,0.663350,2.653399,0.000000
8,0.000000,0.267417,0.000000,0.267417,0.000000,0.000000,0.000000,0.534834,0.0,0.0,...,1.069668,1.069668,0.534834,0.534834,0.267417,0.802251,0.267417,0.267417,0.267417,0.267417
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.776777,1.553553,0.000000,0.000000,0.776777
10,0.000000,0.466319,0.932638,0.932638,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,0.466319,0.466319,1.398956,0.000000,0.932638,0.000000,0.466319,0.466319
11,0.000000,0.000000,0.196991,0.000000,0.000000,0.000000,0.196991,0.590973,0.0,0.0,...,0.590973,0.000000,0.393982,0.196991,0.787964,0.393982,0.590973,0.196991,0.787964,0.196991
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,1.281589,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,1.717009,2.575513,0.858504,0.000000,6.868034,0.000000,1.717009,1.717009,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,0.000000,2.202604,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.000000,0.306419,0.000000,0.306419,0.000000,0.0,0.0,...,0.000000,0.000000,1.225678,0.306419,0.612839,1.225678,0.612839,1.532097,0.306419,0.000000
16,0.785656,0.000000,0.000000,0.000000,0.000000,0.000000,0.785656,0.000000,0.0,0.0,...,2.356969,1.571313,2.356969,0.000000,4.713939,1.571313,0.785656,1.571313,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.000000,1.462828,0.000000,1.462828,1.462828,1.462828,2.925656,1.462828,1.462828,0.000000

In [123]:
dhs_ms_num.T.to_pickle('../data/dhs_vector_25kb.pkl')
dhs_ms_num.T.to_pickle('../../../tmp/data/dhs_vector_25kb.pkl')

In [ ]:
epilogos_states_df

In [100]:
bins_25kb

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]

In [112]:
bins_25kb_bed = BedTool.from_dataframe(bins_25kb)
bins_25kb_bed

In [115]:
dhs_overlap = bins_25kb_bed.intersect(dhs_bed, u=True)
print(dhs_overlap.to_dataframe())

      chrom      start        end  name
0      chr1       9000      34000  0.41
1      chr1      34000      59000  0.41
2      chr1      61000      86000  0.41
3      chr1      86000     111000  0.41
4      chr1     111000     136000  0.41
...     ...        ...        ...   ...
93128  chrX  155042800  155067800  0.41
93129  chrX  155067800  155092800  0.41
93130  chrX  155092800  155117800  0.41
93131  chrX  155117800  155142800  0.41
93132  chrX  155142800  155167800  0.41

[93133 rows x 4 columns]

In [117]:
bins_25kb

      seqname      start        end     ?
0        chr1       9000      34000  0.41
1        chr1      34000      59000  0.41
2        chr1      61000      86000  0.41
3        chr1      86000     111000  0.41
4        chr1     111000     136000  0.41
...       ...        ...        ...   ...
99991    chrX  155042800  155067800  0.41
99992    chrX  155067800  155092800  0.41
99993    chrX  155092800  155117800  0.41
99994    chrX  155117800  155142800  0.41
99995    chrX  155142800  155167800  0.41

[99996 rows x 4 columns]

In [120]:
bins_25kb_bed