In [23]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import h5py
import re

root = "/home/lwu/work/NarrativeGenomics/region_narration/code/pipeline/ARCHS4_LW/refining/data_slash_results/"
filename = root + 'archs4_gene_human_v2.1_normalized_LW20230126.h5'
with h5py.File(filename, 'r') as f:
    logOE_matrix = f['data/logOE_matrix'][:]
    gene_names = f['meta/genes/all_gene_names'][:]
    category_names = f['meta/biosamples/category'][:]

category_names = [x.decode('UTF-8') for x in category_names]
gene_names = [x.decode('UTF-8') for x in gene_names]


category_list  = {
    "Heart", "Atrium", "Cardiac Muscle Fiber", "Pericardium", "Valve", "Ventricle","HUVEC", 
    "Adipose", "Adipocyte", "Myofibroblast", "Osteoblast", "Stromal Cell", 
    "MG63", "K562", "Bone Marrow", "Chondrocyte", "HT1080", "NHDF",
    "HCT116", "HT29", "RKO", "Colon", "Colonic Muscosa", "Intestinal Epithelial Cell", 
    "Small Intestine", "Liver", "Hepatic Stellate Cell", "Hepatocyte", "Primary Liver Cell",
    "HEPG2", "Alpha Cell", "Beta Cell", "Pancreatic Islet", 
    "GSE81547", "PANC1", "Gastric Epithelial Cell", "Esophagus","Granulocyte", "Neutrophil", "Blymphocyte", 
    "Plasma Cell", "Plasmacytoid Dendritic Cell", 
    "Tlymphocyte", "GSM2679484", "JURKAT", "MT4", "NALM6", "REH", "RPMI8226", "Alveolar", 
    "Dendritic", "Kupffer", "Macrophage", "Macroglia",  "THP1", "U937", "JEG3", "Thymus", 
    "Thymocyte", "Spleen",
    "Skin", "Basal Cell", "Fibroblast", "Hair Follicle", "Keratinocyte", "Melanocyte",
    "A431", "HACAT", "HNSCC","Skeletal Muscle", "Myoblast", "Airway Smooth Muscle", "Respiratory Smooth Muscle", 
    "Vascular Smooth Muscle", "LHCNM2","Brain", "DAOY", "IMR32", "SKNSH", "Astrocyte", "Cerebellum", "Cerebral Cortex", 
    "Hypothalamus", "Medula", "Midbrain", "Neuron", "Oligodendrocyte", "Pons", "Spinal Cord", 
    "Thalamus", "Retina", "Motor Neuron", "Sensory Neuron","Lung", "Lung Epithelial", "A549", "H1299", "IMR90", "MRC5", "NCIH460", "NHBE", 
    "Trachea","Breast", "Mammary Gland", "MCF7", "MCF10", "MDAMB231", "MDAMB468", "SKBR3", "T47D", 
    "HELA", "Kidney", "Podocyte", "Renal Cortex", "293F", "FLPIN TREX 293", "HEK293", "C42", 
    "DU145", "LNCAP", "PC3", "Ovary", "Granulosa", "Oocyte", "ES2", "SKOV3", "Testis"
}
category_dict  = {
    "Cardiovascular System" : ["Heart", "Atrium", "Cardiac Muscle Fiber", 
                               "Pericardium", "Valve", "Ventricle",
                               "HUVEC"], 
    
    "Connective Tissue" : ["Adipose", "Adipocyte", "Myofibroblast", "Osteoblast", "Stromal Cell", 
                           "MG63", "K562", "Bone Marrow", "Chondrocyte", "HT1080", "NHDF"],

    "Digestive System": ["HCT116", "HT29", "RKO", "Colon", "Colonic Muscosa", "Intestinal Epithelial Cell", 
                         "Small Intestine", "Liver", "Hepatic Stellate Cell", "Hepatocyte", "Primary Liver Cell",
                         "HEPG2", "Alpha Cell", "Beta Cell", "Pancreatic Islet", 
                         "GSE81547", "PANC1", "Gastric Epithelial Cell", "Esophagus"],
    
    "Immune System" : ["Granulocyte", "Neutrophil", "Blymphocyte", "Plasma Cell", "Plasmacytoid Dendritic Cell", 
                       "Tlymphocyte", "GSM2679484", "JURKAT", "MT4", "NALM6", "REH", "RPMI8226", "Alveolar", 
                       "Dendritic", "Kupffer", "Macrophage", "Macroglia",  "THP1", "U937", "JEG3", "Thymus", 
                       "Thymocyte", "Spleen"],
    
    "Integumentary System" : ["Skin", "Basal Cell", "Fibroblast", "Hair Follicle", "Keratinocyte", "Melanocyte",
                              "A431", "HACAT", "HNSCC"], 
    
    "Muscular System" : ["Skeletal Muscle", "Myoblast", "Airway Smooth Muscle", "Respiratory Smooth Muscle", 
                         "Vascular Smooth Muscle", "LHCNM2"], 
    
    "Nervous System" : ["Brain", "DAOY", "IMR32", "SKNSH", "Astrocyte", "Cerebellum", "Cerebral Cortex", 
                        "Hypothalamus", "Medula", "Midbrain", "Neuron", "Oligodendrocyte", "Pons", "Spinal Cord", 
                        "Thalamus", "Retina", "Motor Neuron", "Sensory Neuron"], 
    
    "Respiratory System" : ["Lung", "Lung Epithelial", "A549", "H1299", "IMR90", "MRC5", "NCIH460", "NHBE", 
                            "Trachea"], 
    
    "Urogenital System" : ["Breast", "Mammary Gland", "MCF7", "MCF10", "MDAMB231", "MDAMB468", "SKBR3", "T47D", 
                           "HELA", "Kidney", "Podocyte", "Renal Cortex", "293F", "FLPIN TREX 293", "HEK293", "C42", 
                           "DU145", "LNCAP", "PC3", "Ovary", "Granulosa", "Oocyte", "ES2", "SKOV3", "Testis"]
}

# Convert category_dict value list elements to lowercase
for category, value_list in category_dict.items():
    for i in range(len(value_list)):
        value_list[i] = value_list[i].lower()

In [24]:
# Get category-sample indexes
all_cat_idxs = []
for element in category_list:
    indexes = []
    for i, name in enumerate(category_names):
        if element.lower() in name.lower():
            indexes.append(i)
    all_cat_idxs.append(indexes)

# Initialize the dictionaries to store the averages
gene_tier1cat_avgs = []

for gene_row in logOE_matrix:
    values = [[gene_row[i] for i in sub_list] for sub_list in all_cat_idxs]
    means = []
    for value in values:
        if len(value) == 0:
            means.append(np.nan)
        else:
            mean = sum(value)/len(value)
            means.append(mean)
    gene_tier1cat_avgs.append(means)

In [25]:
len(gene_tier1cat_avgs)

57447

In [26]:
len(gene_tier1cat_avgs[0])

127

In [27]:
from IPython.display import display

df = pd.DataFrame(gene_tier1cat_avgs, index=gene_names)
df.columns = category_list
display(df)

,Pancreatic Islet,Macrophage,Renal Cortex,SKNSH,Medula,MG63,Melanocyte,Motor Neuron,Retina,Liver,...,Breast,LNCAP,Airway Smooth Muscle,Bone Marrow,Testis,NHBE,293F,Skeletal Muscle,HUVEC,LHCNM2
A1BG,0.904145,0.958343,0.126199,0.896957,NaN,0.379963,0.903993,0.878593,0.399846,2.668668,...,0.509562,0.633759,0.657144,1.064748,0.165445,0.228951,0.423089,0.269254,0.312708,0.388097
A1BG-AS1,1.114086,1.530616,0.155662,1.162818,NaN,0.880483,1.674517,0.999136,0.633474,0.703795,...,0.906342,1.316072,1.439635,0.768679,0.195265,0.624976,1.027124,0.316963,0.696092,1.179094
A1CF,2.086442,0.060457,1.489218,0.071461,NaN,0.053629,0.070890,0.069592,0.059816,3.209776,...,0.079024,0.062288,0.039662,0.154721,0.022998,0.044014,0.053999,0.080976,0.045534,0.064632
A2M,0.546406,1.678592,2.061387,0.009902,NaN,0.008920,1.135664,0.277894,0.809409,1.997129,...,0.588174,0.009428,1.474954,0.170736,1.030224,0.081944,0.012005,1.276533,0.217915,0.030852
A2M-AS1,0.930792,1.285306,0.315589,0.141459,NaN,0.066793,0.664648,0.851478,0.796921,1.443540,...,0.502568,1.008432,0.811750,0.550690,0.494885,0.201894,0.327507,1.500945,0.628132,0.851293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11B,0.997061,0.867326,1.051246,0.954070,NaN,0.795737,0.829231,1.155680,1.087419,1.025150,...,0.747509,0.901631,1.126946,0.807482,1.095335,0.780870,1.123242,2.358598,0.958861,0.944999
ZYX,0.374880,1.380199,0.772848,1.392962,NaN,1.187411,0.889033,0.867725,0.618271,0.824058,...,0.911611,0.552858,1.576343,0.805454,0.729608,1.285870,0.593512,0.583755,1.452258,1.309560
ZYXP1,0.941739,0.773403,0.158562,0.680553,NaN,0.448242,0.577100,0.495699,0.453785,0.660689,...,0.708718,0.456105,0.517446,1.085080,0.195146,0.681558,0.298976,0.573350,0.714047,0.862428
ZZEF1,0.870000,1.234872,1.503008,0.714966,NaN,0.891057,1.186310,0.856583,1.065050,0.881304,...,0.910215,0.972171,1.001760,0.971259,0.879547,0.793562,0.978547,1.145550,1.085488,0.929565
ZZZ3,1.185074,0.750535,0.925242,0.826476,NaN,0.980143,0.927872,0.819549,0.961578,0.837954,...,0.964594,1.066654,0.944173,0.913356,0.761723,0.829619,1.351080,0.977090,1.024556,1.012672

In [28]:
# loop through each column and get the top 10 highest values and their indexes
for col in df.columns:
    top_10 = df[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    print('Indexes for Column "{}":'.format(col))
    print(top_10.index)
    print()

Top 10 values in Column "Pancreatic Islet":
INS        6.517171
GCG        6.380697
SLC30A8    6.187919
G6PC2      6.097876
PNLIP      5.982218
CELA3A     5.912454
KCNK16     5.862052
PPY        5.831182
CPA1       5.803547
PRSS1      5.755286
Name: Pancreatic Islet, dtype: float64
Indexes for Column "Pancreatic Islet":
Index(['INS', 'GCG', 'SLC30A8', 'G6PC2', 'PNLIP', 'CELA3A', 'KCNK16', 'PPY',
       'CPA1', 'PRSS1'],
      dtype='object')

Top 10 values in Column "Macrophage":
MMP9        3.524722
ADAMDEC1    3.430307
GPR84       3.401923
PLA2G7      3.388287
SLAMF8      3.332979
LILRB4      3.307894
CLEC5A      3.295825
CD300C      3.244722
SIGLEC9     3.232163
CCR1        3.224746
Name: Macrophage, dtype: float64
Indexes for Column "Macrophage":
Index(['MMP9', 'ADAMDEC1', 'GPR84', 'PLA2G7', 'SLAMF8', 'LILRB4', 'CLEC5A',
       'CD300C', 'SIGLEC9', 'CCR1'],
      dtype='object')

Top 10 values in Column "Renal Cortex":
UMOD               7.171689
SLC22A12           6.958868
SLC22A6            6.921418
AQP2               6.876418
SLC12A1            6.614430
CDH16              6.603258
PKHD1              6.558987
SLC34A1            6.534615
ENSG00000261489    6.502986
SLC13A1            6.399350
Name: Renal Cortex, dtype: float64
Indexes for Column "Renal Cortex":
Index(['UMOD', 'SLC22A12', 'SLC22A6', 'AQP2', 'SLC12A1', 'CDH16', 'PKHD1',
       'SLC34A1', 'ENSG00000261489', 'SLC13A1'],
      dtype='object')

Top 10 values in Column "SKNSH":
PHOX2A             6.845655
TLX2               5.447663
TGIF2LX            5.225495
ENSG00000286039    5.181040
HAND2              5.033493
PHOX2B             4.877861
FOXR2              4.740304
SLC6A2             4.646673
DBH                4.534031
MARCHF11           4.401484
Name: SKNSH, dtype: float64
Indexes for Column "SKNSH":
Index(['PHOX2A', 'TLX2', 'TGIF2LX', 'ENSG00000286039', 'HAND2', 'PHOX2B',
       'FOXR2', 'SLC6A2', 'DBH', 'MARCHF11'],
      dtype='object')

Top 10 values in Column "Medula":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Medula, dtype: float64
Indexes for Column "Medula":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "MG63":
CCKAR              5.525519
RPL23AP56          5.500916
OR7A3P             5.259714
ENSG00000253698    5.241036
ENSG00000266840    4.962077
MTCO1P49           4.770094
GLYATL3            4.617849
MTND2P7            4.607234
ALX3               4.542599
LINC01925          4.530428
Name: MG63, dtype: float64
Indexes for Column "MG63":
Index(['CCKAR', 'RPL23AP56', 'OR7A3P', 'ENSG00000253698', 'ENSG00000266840',
       'MTCO1P49', 'GLYATL3', 'MTND2P7', 'ALX3', 'LINC01925'],
      dtype='object')

Top 10 values in Column "Melanocyte":
TYR                5.531068
LINC00518          5.511904
OCA2               5.374334
MLANA              5.349799
SLC24A5            5.326437
ENSG00000267683    5.083782
SLC45A2            5.024741
ENSG00000205444    4.980697
TYRP1              4.915866
CBX3P7             4.780324
Name: Melanocyte, dtype: float64
Indexes for Column "Melanocyte":
Index(['TYR', 'LINC00518', 'OCA2', 'MLANA', 'SLC24A5', 'ENSG00000267683',
       'SLC45A2', 'ENSG00000205444', 'TYRP1', 'CBX3P7'],
      dtype='object')

Top 10 values in Column "Motor Neuron":
SLC5A7       5.553960
SLC18A3      5.223227
LINC01201    4.744176
CHAT         4.529950
P2RX3        4.437239
HOXB1        4.296427
GLRA2        4.190177
GDAP1L1      4.187817
DCX          4.181744
NELL1        4.100737
Name: Motor Neuron, dtype: float64
Indexes for Column "Motor Neuron":
Index(['SLC5A7', 'SLC18A3', 'LINC01201', 'CHAT', 'P2RX3', 'HOXB1', 'GLRA2',
       'GDAP1L1', 'DCX', 'NELL1'],
      dtype='object')

Top 10 values in Column "Retina":
OTX2         4.349610
RAX          4.153207
RLBP1        4.142008
SIX3-AS1     4.078442
LINC01833    3.973709
RCVRN        3.911579
CRX          3.905173
GNB3         3.887119
PDC          3.879068
VSX2         3.875427
Name: Retina, dtype: float64
Indexes for Column "Retina":
Index(['OTX2', 'RAX', 'RLBP1', 'SIX3-AS1', 'LINC01833', 'RCVRN', 'CRX', 'GNB3',
       'PDC', 'VSX2'],
      dtype='object')

Top 10 values in Column "Liver":
C8A         3.432773
SERPINC1    3.423823
APOC3       3.413202
GC          3.375552
ITIH1       3.365239
F2          3.364336
HPX         3.361005
AMBP        3.356114
SERPINA4    3.348099
APCS        3.345630
Name: Liver, dtype: float64
Indexes for Column "Liver":
Index(['C8A', 'SERPINC1', 'APOC3', 'GC', 'ITIH1', 'F2', 'HPX', 'AMBP',
       'SERPINA4', 'APCS'],
      dtype='object')

Top 10 values in Column "GSE81547":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: GSE81547, dtype: float64
Indexes for Column "GSE81547":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "SKOV3":
CTXND2             6.150746
LINC02167          6.003907
LINC02522          5.436976
ENSG00000224583    5.066232
ENSG00000223786    4.943096
ENSG00000286949    4.758189
RNA5SP413          4.675293
LINC02474          4.602728
ENSG00000223829    4.322378
VN2R19P            4.317119
Name: SKOV3, dtype: float64
Indexes for Column "SKOV3":
Index(['CTXND2', 'LINC02167', 'LINC02522', 'ENSG00000224583',
       'ENSG00000223786', 'ENSG00000286949', 'RNA5SP413', 'LINC02474',
       'ENSG00000223829', 'VN2R19P'],
      dtype='object')

Top 10 values in Column "Colon":
PHGR1     3.200245
KRT20     3.146381
CDX2      3.118201
CDH17     3.075295
CDX1      3.062378
GPA33     3.029615
EPS8L3    3.028145
TSPAN8    2.903230
MUC13     2.889876
USH1C     2.860072
Name: Colon, dtype: float64
Indexes for Column "Colon":
Index(['PHGR1', 'KRT20', 'CDX2', 'CDH17', 'CDX1', 'GPA33', 'EPS8L3', 'TSPAN8',
       'MUC13', 'USH1C'],
      dtype='object')

Top 10 values in Column "Trachea":
BPIFA1             4.596811
ADH7               4.554483
SERPINB3           4.439956
ENSG00000253339    4.274354
UPK1B              4.137250
CD200R1L-AS1       4.063400
SERPINB11          4.061192
ENSG00000236028    4.016540
TMPRSS11D          3.985085
BPIFB1             3.948036
Name: Trachea, dtype: float64
Indexes for Column "Trachea":
Index(['BPIFA1', 'ADH7', 'SERPINB3', 'ENSG00000253339', 'UPK1B',
       'CD200R1L-AS1', 'SERPINB11', 'ENSG00000236028', 'TMPRSS11D', 'BPIFB1'],
      dtype='object')

Top 10 values in Column "JEG3":
GPR32              8.634642
LGALS16            7.988753
XAGE2              7.281062
CGB5               6.921260
ERVH48-1           6.776870
ENSG00000261745    6.744323
ERVV-1             6.708341
MAGEA8             6.662239
CGB3               6.576288
CGB8               6.427406
Name: JEG3, dtype: float64
Indexes for Column "JEG3":
Index(['GPR32', 'LGALS16', 'XAGE2', 'CGB5', 'ERVH48-1', 'ENSG00000261745',
       'ERVV-1', 'MAGEA8', 'CGB3', 'CGB8'],
      dtype='object')

Top 10 values in Column "MCF10":
SYT8               3.992342
EPGN               3.740578
KRT81              3.697670
ROS1               3.668627
SCNN1G             3.644348
ENSG00000287902    3.628083
S100A2             3.609354
KRT6A              3.584352
PNLIPRP3           3.496859
MIR205HG           3.492252
Name: MCF10, dtype: float64
Indexes for Column "MCF10":
Index(['SYT8', 'EPGN', 'KRT81', 'ROS1', 'SCNN1G', 'ENSG00000287902', 'S100A2',
       'KRT6A', 'PNLIPRP3', 'MIR205HG'],
      dtype='object')

Top 10 values in Column "HT1080":
MIR4527HG          6.973042
NCOR1P4            6.465762
TUBA3C             6.265497
CTAG1A             6.261889
ENSG00000273388    6.084210
USP26              6.018375
FOXR2              5.837355
SSX3               5.536236
LINC01029          5.510316
PASD1              5.497824
Name: HT1080, dtype: float64
Indexes for Column "HT1080":
Index(['MIR4527HG', 'NCOR1P4', 'TUBA3C', 'CTAG1A', 'ENSG00000273388', 'USP26',
       'FOXR2', 'SSX3', 'LINC01029', 'PASD1'],
      dtype='object')

Top 10 values in Column "Plasma Cell":
TNFRSF17           5.597450
IRF4               4.633716
IFNG-AS1           4.627058
VDAC2P3            4.529487
TNFRSF13B          4.478150
DERL3              4.443618
LINC01480          4.442833
ENSG00000259772    4.394566
POU2AF1            4.331434
IGLJ1              4.323770
Name: Plasma Cell, dtype: float64
Indexes for Column "Plasma Cell":
Index(['TNFRSF17', 'IRF4', 'IFNG-AS1', 'VDAC2P3', 'TNFRSF13B', 'DERL3',
       'LINC01480', 'ENSG00000259772', 'POU2AF1', 'IGLJ1'],
      dtype='object')

Top 10 values in Column "JURKAT":
TRBV12-3           5.514528
LCT-AS1            5.018883
LINC02706          5.014226
TRAV8-4            5.003966
SIX6               4.820724
ENSG00000225632    4.767534
LINC01882          4.731162
MYO7B              4.658263
PSMA8              4.642348
LINC01222          4.596127
Name: JURKAT, dtype: float64
Indexes for Column "JURKAT":
Index(['TRBV12-3', 'LCT-AS1', 'LINC02706', 'TRAV8-4', 'SIX6',
       'ENSG00000225632', 'LINC01882', 'MYO7B', 'PSMA8', 'LINC01222'],
      dtype='object')

Top 10 values in Column "Mammary Gland":
GATA3-AS1          3.599313
KRT19P1            3.513250
DSCAM-AS1          3.401806
ENSG00000232638    3.358739
RPL10P6            3.180793
PRLR               3.072005
GATA3              3.013906
UPK2               3.011478
ENSG00000266869    2.917820
PGR                2.913441
Name: Mammary Gland, dtype: float64
Indexes for Column "Mammary Gland":
Index(['GATA3-AS1', 'KRT19P1', 'DSCAM-AS1', 'ENSG00000232638', 'RPL10P6',
       'PRLR', 'GATA3', 'UPK2', 'ENSG00000266869', 'PGR'],
      dtype='object')

Top 10 values in Column "MDAMB468":
VGLL1              5.598573
ENSG00000223829    5.474619
ENSG00000233028    5.379086
OAZ1P1             5.297246
ENSG00000253130    5.250489
WNT6               5.131678
RNF5P1             4.808019
CASP14             4.732146
ENSG00000253774    4.693045
FOXI1              4.617000
Name: MDAMB468, dtype: float64
Indexes for Column "MDAMB468":
Index(['VGLL1', 'ENSG00000223829', 'ENSG00000233028', 'OAZ1P1',
       'ENSG00000253130', 'WNT6', 'RNF5P1', 'CASP14', 'ENSG00000253774',
       'FOXI1'],
      dtype='object')

Top 10 values in Column "Brain":
PLP1      2.844363
GRIA2     2.830520
MT3       2.828468
GPM6A     2.787978
CAMK2A    2.746638
DLGAP1    2.739318
PMP2      2.706381
GFAP      2.682923
DPP6      2.675517
LGI1      2.653544
Name: Brain, dtype: float64
Indexes for Column "Brain":
Index(['PLP1', 'GRIA2', 'MT3', 'GPM6A', 'CAMK2A', 'DLGAP1', 'PMP2', 'GFAP',
       'DPP6', 'LGI1'],
      dtype='object')

Top 10 values in Column "MT4":
RPL23AP41          10.344786
TRBV10-2            8.993960
HNRNPA1P21          8.109953
LINC00184           7.980034
TUBA3C              7.700095
LIM2                7.588412
CCR8                7.485007
LINC02341           7.455715
ENSG00000287167     7.242168
SMIM38              7.136958
Name: MT4, dtype: float64
Indexes for Column "MT4":
Index(['RPL23AP41', 'TRBV10-2', 'HNRNPA1P21', 'LINC00184', 'TUBA3C', 'LIM2',
       'CCR8', 'LINC02341', 'ENSG00000287167', 'SMIM38'],
      dtype='object')

Top 10 values in Column "Hair Follicle":
KRT35        3.945831
KRTAP11-1    3.924180
KRT28        3.899528
KRT32        3.649964
KRT71        3.523681
MT4          3.517547
KRT85        3.513161
KRT25        3.483975
KRT82        3.475910
PRR9         3.439037
Name: Hair Follicle, dtype: float64
Indexes for Column "Hair Follicle":
Index(['KRT35', 'KRTAP11-1', 'KRT28', 'KRT32', 'KRT71', 'MT4', 'KRT85',
       'KRT25', 'KRT82', 'PRR9'],
      dtype='object')

Top 10 values in Column "Thalamus":
TCEAL6             5.104849
SNORD115-48        5.101444
NTSR2              5.098754
ENSG00000260878    5.013553
CARTPT             5.006885
PNMA6F             4.931387
PMCH               4.900046
CALY               4.892306
ENSG00000266844    4.748583
LINC01574          4.736939
Name: Thalamus, dtype: float64
Indexes for Column "Thalamus":
Index(['TCEAL6', 'SNORD115-48', 'NTSR2', 'ENSG00000260878', 'CARTPT', 'PNMA6F',
       'PMCH', 'CALY', 'ENSG00000266844', 'LINC01574'],
      dtype='object')

Top 10 values in Column "Spleen":
NCR3               3.951654
LTA                3.819477
PTPRCAP            3.648954
SLAMF6             3.643695
LTB                3.633785
CD69               3.610716
GVINP1             3.578049
ENSG00000286030    3.508416
STAP1              3.497109
PYHIN1             3.477920
Name: Spleen, dtype: float64
Indexes for Column "Spleen":
Index(['NCR3', 'LTA', 'PTPRCAP', 'SLAMF6', 'LTB', 'CD69', 'GVINP1',
       'ENSG00000286030', 'STAP1', 'PYHIN1'],
      dtype='object')

Top 10 values in Column "IMR90":
FOXF1       3.882637
LRRC17      3.766538
BDKRB1      3.644038
FOXL1       3.618647
FENDRR      3.557984
CHRM2       3.516486
TRPA1       3.468598
TBX5-AS1    3.376557
ACTG2       3.261522
MTCO2P22    3.203696
Name: IMR90, dtype: float64
Indexes for Column "IMR90":
Index(['FOXF1', 'LRRC17', 'BDKRB1', 'FOXL1', 'FENDRR', 'CHRM2', 'TRPA1',
       'TBX5-AS1', 'ACTG2', 'MTCO2P22'],
      dtype='object')

Top 10 values in Column "Kidney":
HOXD10             2.413705
HOXD11             2.286641
HOXD9              2.212565
EMX1               2.132206
HOXA6              1.993269
LINC01976          1.983813
PAX2               1.968171
NKX2-5             1.941686
LINC02381          1.902227
ENSG00000272801    1.898327
Name: Kidney, dtype: float64
Indexes for Column "Kidney":
Index(['HOXD10', 'HOXD11', 'HOXD9', 'EMX1', 'HOXA6', 'LINC01976', 'PAX2',
       'NKX2-5', 'LINC02381', 'ENSG00000272801'],
      dtype='object')

Top 10 values in Column "Neutrophil":
ADGRE3             5.628267
CXCR1              5.545394
ADGRG3             5.501996
CXCR2              5.494818
CEACAM3            5.455516
FCGR3B             5.439736
ENSG00000254789    5.341819
ENSG00000255801    5.300889
CMTM2              5.233845
CEACAM4            5.204238
Name: Neutrophil, dtype: float64
Indexes for Column "Neutrophil":
Index(['ADGRE3', 'CXCR1', 'ADGRG3', 'CXCR2', 'CEACAM3', 'FCGR3B',
       'ENSG00000254789', 'ENSG00000255801', 'CMTM2', 'CEACAM4'],
      dtype='object')

Top 10 values in Column "HELA":
GLP2R        3.727830
PRSS21       3.668304
MARCOL       3.568539
CASC19       3.539898
CT83         3.532662
PICSAR       3.440767
LINC00165    3.275833
LY6K         3.251933
LINC01693    3.146260
LINC00602    3.144553
Name: HELA, dtype: float64
Indexes for Column "HELA":
Index(['GLP2R', 'PRSS21', 'MARCOL', 'CASC19', 'CT83', 'PICSAR', 'LINC00165',
       'LY6K', 'LINC01693', 'LINC00602'],
      dtype='object')

Top 10 values in Column "HCT116":
ENSG00000248112    4.295867
ENSG00000250920    4.278737
ARL14EPL           4.254663
MAGEB2             4.164884
NTSR1              4.026991
OR51B2             3.874583
WNT16              3.873075
FGF19              3.819359
OR51B3P            3.809440
PTMAP5             3.775366
Name: HCT116, dtype: float64
Indexes for Column "HCT116":
Index(['ENSG00000248112', 'ENSG00000250920', 'ARL14EPL', 'MAGEB2', 'NTSR1',
       'OR51B2', 'WNT16', 'FGF19', 'OR51B3P', 'PTMAP5'],
      dtype='object')

Top 10 values in Column "Neuron":
DCX           3.982093
GDAP1L1       3.711406
ST8SIA2       3.586239
GAP43         3.570903
TRAPPC13P1    3.560838
MAP6          3.511766
STMN4         3.468878
CCDC184       3.438778
STMN2         3.436986
CELF3         3.390270
Name: Neuron, dtype: float64
Indexes for Column "Neuron":
Index(['DCX', 'GDAP1L1', 'ST8SIA2', 'GAP43', 'TRAPPC13P1', 'MAP6', 'STMN4',
       'CCDC184', 'STMN2', 'CELF3'],
      dtype='object')

Top 10 values in Column "Hepatic Stellate Cell":
ENSG00000284695    3.653837
COL6A2-DT          3.444173
NID2               3.387635
SULT1E1            3.380444
THBS2              3.296913
HGF                3.243382
ADAMTS12           3.236106
ADAMTS2            3.205616
MIR656             3.168929
PCDHGA12           3.112815
Name: Hepatic Stellate Cell, dtype: float64
Indexes for Column "Hepatic Stellate Cell":
Index(['ENSG00000284695', 'COL6A2-DT', 'NID2', 'SULT1E1', 'THBS2', 'HGF',
       'ADAMTS12', 'ADAMTS2', 'MIR656', 'PCDHGA12'],
      dtype='object')

Top 10 values in Column "Granulocyte":
LINC02218          6.419831
ENSG00000286236    6.335426
ENSG00000218809    6.329462
ENSG00000255801    6.277204
ADGRE3             6.217297
ENSG00000273644    6.150995
ENSG00000288700    6.143376
FCGR3B             6.121557
CXCR1              6.034089
ENSG00000287131    5.941038
Name: Granulocyte, dtype: float64
Indexes for Column "Granulocyte":
Index(['LINC02218', 'ENSG00000286236', 'ENSG00000218809', 'ENSG00000255801',
       'ADGRE3', 'ENSG00000273644', 'ENSG00000288700', 'FCGR3B', 'CXCR1',
       'ENSG00000287131'],
      dtype='object')

Top 10 values in Column "H1299":
TDRD12        5.937256
MAGEA4        5.879824
MAGEA4-AS1    5.704995
CTAG1B        5.615746
CTAG1A        5.509059
ELOBP2        5.187628
PASD1         5.020321
FAM9C         4.857989
H2AB2         4.570977
H2AB3         4.570977
Name: H1299, dtype: float64
Indexes for Column "H1299":
Index(['TDRD12', 'MAGEA4', 'MAGEA4-AS1', 'CTAG1B', 'CTAG1A', 'ELOBP2', 'PASD1',
       'FAM9C', 'H2AB2', 'H2AB3'],
      dtype='object')

Top 10 values in Column "Cerebellum":
MIR4705            6.325231
ENSG00000248627    6.313488
MTND1P19           6.198788
ZNF385D-AS2        6.176243
MIR2681            6.157362
FGF14-AS1          6.117515
GABRA6             6.088544
ENSG00000248766    6.068196
RPL39P29           6.005853
ENSG00000274242    5.949107
Name: Cerebellum, dtype: float64
Indexes for Column "Cerebellum":
Index(['MIR4705', 'ENSG00000248627', 'MTND1P19', 'ZNF385D-AS2', 'MIR2681',
       'FGF14-AS1', 'GABRA6', 'ENSG00000248766', 'RPL39P29',
       'ENSG00000274242'],
      dtype='object')

Top 10 values in Column "Ovary":
MIR202HG           2.669607
WT1-AS             2.471663
WT1                2.374440
PROK1              2.308375
KLHDC8A            2.280133
NRK                2.168470
SIGLEC11           2.148497
LINC02701          2.140292
FOXL2              2.130090
ENSG00000268560    2.099387
Name: Ovary, dtype: float64
Indexes for Column "Ovary":
Index(['MIR202HG', 'WT1-AS', 'WT1', 'PROK1', 'KLHDC8A', 'NRK', 'SIGLEC11',
       'LINC02701', 'FOXL2', 'ENSG00000268560'],
      dtype='object')

Top 10 values in Column "Beta Cell":
KCNK16     6.663440
INS        6.660449
CRYBA2     6.306251
RFX6       5.927327
GCG        5.907537
PAX4       5.702608
CFC1       5.573814
SLC30A8    5.372736
SCGN       5.196642
FEV        5.186344
Name: Beta Cell, dtype: float64
Indexes for Column "Beta Cell":
Index(['KCNK16', 'INS', 'CRYBA2', 'RFX6', 'GCG', 'PAX4', 'CFC1', 'SLC30A8',
       'SCGN', 'FEV'],
      dtype='object')

Top 10 values in Column "Hepatocyte":
HABP2    3.913011
FGB      3.883393
LBP      3.872450
HPX      3.821475
FGA      3.820289
FGG      3.719654
ALB      3.694288
APOC3    3.685470
VTN      3.628315
ORM1     3.611673
Name: Hepatocyte, dtype: float64
Indexes for Column "Hepatocyte":
Index(['HABP2', 'FGB', 'LBP', 'HPX', 'FGA', 'FGG', 'ALB', 'APOC3', 'VTN',
       'ORM1'],
      dtype='object')

Top 10 values in Column "PC3":
MSMP               4.825670
LINC02582          4.008823
ENSG00000228683    3.948398
SHISA3             3.630577
ENSG00000243635    3.490972
HAS3               3.485569
AVPR1B-DT          3.432665
PRAC1              3.418743
BRINP3-DT          3.348522
VSTM5              3.329370
Name: PC3, dtype: float64
Indexes for Column "PC3":
Index(['MSMP', 'LINC02582', 'ENSG00000228683', 'SHISA3', 'ENSG00000243635',
       'HAS3', 'AVPR1B-DT', 'PRAC1', 'BRINP3-DT', 'VSTM5'],
      dtype='object')

Top 10 values in Column "Chondrocyte":
ACAN      5.882402
CCN6      5.616623
HAPLN1    5.395976
ECRG4     4.887687
COL2A1    4.642653
COMP      4.622158
MMP3      4.412000
PENK      4.400435
ITGA10    4.379641
ITIH6     4.356096
Name: Chondrocyte, dtype: float64
Indexes for Column "Chondrocyte":
Index(['ACAN', 'CCN6', 'HAPLN1', 'ECRG4', 'COL2A1', 'COMP', 'MMP3', 'PENK',
       'ITGA10', 'ITIH6'],
      dtype='object')

Top 10 values in Column "HT29":
UGT1A10    4.879220
UGT1A8     4.793386
NMUR2      4.529324
KRT20      4.316394
TRIM31     4.114050
MYRFL      4.079474
HOTTIP     3.881980
KLK6       3.823488
NTSR1      3.806378
VSIG2      3.715420
Name: HT29, dtype: float64
Indexes for Column "HT29":
Index(['UGT1A10', 'UGT1A8', 'NMUR2', 'KRT20', 'TRIM31', 'MYRFL', 'HOTTIP',
       'KLK6', 'NTSR1', 'VSIG2'],
      dtype='object')

Top 10 values in Column "Esophagus":
KRT13              4.897480
SPRR3              4.418927
KRT4               4.248369
CRNN               3.861023
IL36A              3.542998
TMPRSS11A          3.523593
ENSG00000234262    3.509368
CAPN14             3.502536
GBP6               3.481227
PADI3              3.479946
Name: Esophagus, dtype: float64
Indexes for Column "Esophagus":
Index(['KRT13', 'SPRR3', 'KRT4', 'CRNN', 'IL36A', 'TMPRSS11A',
       'ENSG00000234262', 'CAPN14', 'GBP6', 'PADI3'],
      dtype='object')

Top 10 values in Column "Pericardium":
ENSG00000286508    4.710817
ITLN1              4.535585
MIR4524B           4.313699
C7                 4.267326
MIR4530            4.253850
THBS4              4.145558
LYVE1              4.091052
MIR3129            4.052575
MIR3194            4.038686
TNXB               3.983919
Name: Pericardium, dtype: float64
Indexes for Column "Pericardium":
Index(['ENSG00000286508', 'ITLN1', 'MIR4524B', 'C7', 'MIR4530', 'THBS4',
       'LYVE1', 'MIR3129', 'MIR3194', 'TNXB'],
      dtype='object')

Top 10 values in Column "Podocyte":
DCAF12L1       4.841097
LRRN4          4.461194
ACTBL2         4.029977
PAX8           3.947501
GDF5           3.725541
STEAP1B-AS1    3.601247
ADAMTS5        3.547426
LINC01111      3.507759
LINC00973      3.503350
NPFFR2         3.481060
Name: Podocyte, dtype: float64
Indexes for Column "Podocyte":
Index(['DCAF12L1', 'LRRN4', 'ACTBL2', 'PAX8', 'GDF5', 'STEAP1B-AS1', 'ADAMTS5',
       'LINC01111', 'LINC00973', 'NPFFR2'],
      dtype='object')

Top 10 values in Column "FLPIN TREX 293":
LINC02226          4.810352
ENSG00000283269    4.476258
TLX1               4.372111
IRS4               4.371393
ENSG00000225280    4.057810
ZNF711             4.005095
ENSG00000267260    3.859460
NKX2-4             3.840945
FBXL21P            3.514895
CEBPE              3.488940
Name: FLPIN TREX 293, dtype: float64
Indexes for Column "FLPIN TREX 293":
Index(['LINC02226', 'ENSG00000283269', 'TLX1', 'IRS4', 'ENSG00000225280',
       'ZNF711', 'ENSG00000267260', 'NKX2-4', 'FBXL21P', 'CEBPE'],
      dtype='object')

Top 10 values in Column "Adipose":
LINCADL    4.240488
ADIPOQ     4.197964
TRARG1     4.117466
PLIN1      4.085291
CIDEC      4.062695
MRAP       3.960534
PLAAT5     3.946845
LEP        3.924920
TNMD       3.766504
PLIN4      3.764112
Name: Adipose, dtype: float64
Indexes for Column "Adipose":
Index(['LINCADL', 'ADIPOQ', 'TRARG1', 'PLIN1', 'CIDEC', 'MRAP', 'PLAAT5',
       'LEP', 'TNMD', 'PLIN4'],
      dtype='object')

Top 10 values in Column "Alpha Cell":
CRYBA2             7.219788
UCN3               6.890233
ENSG00000287700    6.886083
GCG                6.859973
RFX6               6.857395
CFC1               6.490538
SLC30A8            6.479166
PPY                6.455971
INS                6.322933
KCNK16             6.318363
Name: Alpha Cell, dtype: float64
Indexes for Column "Alpha Cell":
Index(['CRYBA2', 'UCN3', 'ENSG00000287700', 'GCG', 'RFX6', 'CFC1', 'SLC30A8',
       'PPY', 'INS', 'KCNK16'],
      dtype='object')

Top 10 values in Column "Vascular Smooth Muscle":
TMEM200A    3.429814
HAND2       3.389153
HGF         3.100839
NID2        3.030188
SCARF2      2.959158
PCDH10      2.957630
GDF6        2.912998
RGS4        2.909060
CREB3L1     2.896119
PAPPA       2.860266
Name: Vascular Smooth Muscle, dtype: float64
Indexes for Column "Vascular Smooth Muscle":
Index(['TMEM200A', 'HAND2', 'HGF', 'NID2', 'SCARF2', 'PCDH10', 'GDF6', 'RGS4',
       'CREB3L1', 'PAPPA'],
      dtype='object')

Top 10 values in Column "Oocyte":
OOSP2        8.596316
H1-8         8.520012
NLRP13       8.509665
TUBB8P4      8.437092
NLRP4        8.434100
LINC02105    8.409327
TUBB7P       8.350382
OOSP4A       8.337334
WEE2         8.335062
NLRP9        8.314685
Name: Oocyte, dtype: float64
Indexes for Column "Oocyte":
Index(['OOSP2', 'H1-8', 'NLRP13', 'TUBB8P4', 'NLRP4', 'LINC02105', 'TUBB7P',
       'OOSP4A', 'WEE2', 'NLRP9'],
      dtype='object')

Top 10 values in Column "Intestinal Epithelial Cell":
CEACAM18           6.083115
MLN                5.775899
LCT                5.746992
TMPRSS15           5.736960
GIMD1              5.697102
ENSG00000258052    5.671192
SI                 5.556785
OTOP3              5.418298
APOBEC1            5.263507
MUC17              5.205238
Name: Intestinal Epithelial Cell, dtype: float64
Indexes for Column "Intestinal Epithelial Cell":
Index(['CEACAM18', 'MLN', 'LCT', 'TMPRSS15', 'GIMD1', 'ENSG00000258052', 'SI',
       'OTOP3', 'APOBEC1', 'MUC17'],
      dtype='object')

Top 10 values in Column "Blymphocyte":
MS4A1              4.970215
PRAMENP            4.928416
NAALADL2-AS2       4.758347
BLK                4.720726
FCRLA              4.692866
PAX5               4.643452
IGHV5-78           4.579879
OR13A1             4.551563
ENSG00000260303    4.509045
PSMA8              4.500898
Name: Blymphocyte, dtype: float64
Indexes for Column "Blymphocyte":
Index(['MS4A1', 'PRAMENP', 'NAALADL2-AS2', 'BLK', 'FCRLA', 'PAX5', 'IGHV5-78',
       'OR13A1', 'ENSG00000260303', 'PSMA8'],
      dtype='object')

Top 10 values in Column "HNSCC":
WNT10A       2.218011
LINC02999    2.164812
GPR87        2.157984
TP63         2.141937
KRT5         2.141306
SOX15        2.124981
S100A2       2.054234
KRT13        2.048759
ANXA8        2.028380
KRT6A        1.996857
Name: HNSCC, dtype: float64
Indexes for Column "HNSCC":
Index(['WNT10A', 'LINC02999', 'GPR87', 'TP63', 'KRT5', 'SOX15', 'S100A2',
       'KRT13', 'ANXA8', 'KRT6A'],
      dtype='object')

Top 10 values in Column "Spinal Cord":
ENSG00000228408    5.159935
HAPLN2             5.105916
MIR219A2HG         5.062407
MIR7158            5.035149
LINC00609          4.995782
OR5AO1P            4.859361
PMP2               4.766404
PIRT               4.751741
MOG                4.696380
APLNR              4.680390
Name: Spinal Cord, dtype: float64
Indexes for Column "Spinal Cord":
Index(['ENSG00000228408', 'HAPLN2', 'MIR219A2HG', 'MIR7158', 'LINC00609',
       'OR5AO1P', 'PMP2', 'PIRT', 'MOG', 'APLNR'],
      dtype='object')

Top 10 values in Column "Atrium":
ENSG00000287891    7.198705
MYH6               7.145009
MYBPHL             6.911220
MIR208A            6.830289
NPPA               6.824921
LINC02248          6.700781
LMAN1L             6.621794
ENSG00000261606    6.546465
MYL7               6.440202
DHRS7C             6.321729
Name: Atrium, dtype: float64
Indexes for Column "Atrium":
Index(['ENSG00000287891', 'MYH6', 'MYBPHL', 'MIR208A', 'NPPA', 'LINC02248',
       'LMAN1L', 'ENSG00000261606', 'MYL7', 'DHRS7C'],
      dtype='object')

Top 10 values in Column "SKBR3":
REXO1L3P           6.206321
ENSG00000286407    5.046075
OAZ1P1             4.965866
GPC1-AS1           4.911158
ENSG00000254180    4.893102
VGLL1              4.825040
OTOR               4.770793
REXO1L1P           4.651062
LINC02771          4.526797
MED15P1            4.388053
Name: SKBR3, dtype: float64
Indexes for Column "SKBR3":
Index(['REXO1L3P', 'ENSG00000286407', 'OAZ1P1', 'GPC1-AS1', 'ENSG00000254180',
       'VGLL1', 'OTOR', 'REXO1L1P', 'LINC02771', 'MED15P1'],
      dtype='object')

Top 10 values in Column "RPMI8226":
ENSG00000232001    8.585515
IGLV2-28           8.374619
CXADRP2            7.091195
CD8B2              6.882632
ENSG00000287046    6.713730
LINC01229          6.671345
ENSG00000242444    6.668427
LINC02009          6.490504
LINC01887          6.375803
ENSG00000259214    6.347157
Name: RPMI8226, dtype: float64
Indexes for Column "RPMI8226":
Index(['ENSG00000232001', 'IGLV2-28', 'CXADRP2', 'CD8B2', 'ENSG00000287046',
       'LINC01229', 'ENSG00000242444', 'LINC02009', 'LINC01887',
       'ENSG00000259214'],
      dtype='object')

Top 10 values in Column "Astrocyte":
ST8SIA2            2.818107
COL11A1            2.659229
PCDHGB6            2.645399
TSPAN11            2.630239
POU3F4             2.603278
TMEM200C           2.555062
POU3F2             2.552848
ENSG00000222000    2.536334
MEGF10             2.530814
NES                2.522737
Name: Astrocyte, dtype: float64
Indexes for Column "Astrocyte":
Index(['ST8SIA2', 'COL11A1', 'PCDHGB6', 'TSPAN11', 'POU3F4', 'TMEM200C',
       'POU3F2', 'ENSG00000222000', 'MEGF10', 'NES'],
      dtype='object')

Top 10 values in Column "Keratinocyte":
KRT16P6    4.198727
KRT16P4    4.110730
KRT6A      4.028323
DSG3       3.969699
KRT14      3.955011
FGFBP1     3.936648
ZBED2      3.918284
KRT16P5    3.886518
HEPHL1     3.852976
KRT5       3.837288
Name: Keratinocyte, dtype: float64
Indexes for Column "Keratinocyte":
Index(['KRT16P6', 'KRT16P4', 'KRT6A', 'DSG3', 'KRT14', 'FGFBP1', 'ZBED2',
       'KRT16P5', 'HEPHL1', 'KRT5'],
      dtype='object')

Top 10 values in Column "HEK293":
HOXD13      3.589860
IRS4        3.562319
HOXD10      3.176973
HOXD11      3.133279
IRS4-AS1    3.005443
NKX2-4      2.952589
RADX        2.880163
HMX1        2.854648
POU4F1      2.770085
EN2         2.761339
Name: HEK293, dtype: float64
Indexes for Column "HEK293":
Index(['HOXD13', 'IRS4', 'HOXD10', 'HOXD11', 'IRS4-AS1', 'NKX2-4', 'RADX',
       'HMX1', 'POU4F1', 'EN2'],
      dtype='object')

Top 10 values in Column "Oligodendrocyte":
COL20A1      5.452527
OLIG2        5.288788
LHFPL3       4.999388
NKX2-2       4.825269
GPR17        4.264122
BCAN         4.192767
SOX10        4.084537
PMP2         3.944030
LINC02283    3.877267
SCRG1        3.844035
Name: Oligodendrocyte, dtype: float64
Indexes for Column "Oligodendrocyte":
Index(['COL20A1', 'OLIG2', 'LHFPL3', 'NKX2-2', 'GPR17', 'BCAN', 'SOX10',
       'PMP2', 'LINC02283', 'SCRG1'],
      dtype='object')

Top 10 values in Column "Stromal Cell":
WNT5A              2.884443
PAMR1              2.547542
HTR2B              2.527088
SRPX2              2.497058
KRTAP1-5           2.494258
WNT2               2.427317
KRT34              2.390690
FOXL2NB            2.383372
LINC01391          2.363336
ENSG00000269289    2.358580
Name: Stromal Cell, dtype: float64
Indexes for Column "Stromal Cell":
Index(['WNT5A', 'PAMR1', 'HTR2B', 'SRPX2', 'KRTAP1-5', 'WNT2', 'KRT34',
       'FOXL2NB', 'LINC01391', 'ENSG00000269289'],
      dtype='object')

Top 10 values in Column "Granulosa":
HSD3B2             6.958261
HSD3BP2            5.998870
CYP11A1            5.927994
INHA               5.687557
CYP19A1            5.617174
CCKBR              5.259692
DCAF12L2           5.252764
DCAF8L2            5.247979
ENSG00000286410    5.129314
MRO                4.753188
Name: Granulosa, dtype: float64
Indexes for Column "Granulosa":
Index(['HSD3B2', 'HSD3BP2', 'CYP11A1', 'INHA', 'CYP19A1', 'CCKBR', 'DCAF12L2',
       'DCAF8L2', 'ENSG00000286410', 'MRO'],
      dtype='object')

Top 10 values in Column "Lung":
SFTPB      2.182751
SFTPA2     2.073239
SFTPA1     2.069774
CXCL17     2.057260
SFTA2      2.043883
SFTPC      2.017082
SLC34A2    1.957214
SFTA3      1.930213
SCGB1A1    1.885182
CEACAM6    1.852312
Name: Lung, dtype: float64
Indexes for Column "Lung":
Index(['SFTPB', 'SFTPA2', 'SFTPA1', 'CXCL17', 'SFTA2', 'SFTPC', 'SLC34A2',
       'SFTA3', 'SCGB1A1', 'CEACAM6'],
      dtype='object')

Top 10 values in Column "Kupffer":
ATP5PDP3           4.064778
ENSG00000288022    3.861606
ENSG00000285218    3.766749
EEF1A1P11          3.763194
COLEC10            3.577025
TSLP               3.540069
ENSG00000267328    3.418213
ENSG00000254278    3.410193
ACTA2-AS1          3.409227
RSU1P1             3.373480
Name: Kupffer, dtype: float64
Indexes for Column "Kupffer":
Index(['ATP5PDP3', 'ENSG00000288022', 'ENSG00000285218', 'EEF1A1P11',
       'COLEC10', 'TSLP', 'ENSG00000267328', 'ENSG00000254278', 'ACTA2-AS1',
       'RSU1P1'],
      dtype='object')

Top 10 values in Column "K562":
HBG1               4.866105
HBZ                4.803799
ABCB10P4           4.760568
RHOXF2B            4.752056
ENSG00000237311    4.688289
RHAG               4.686906
LINC01029          4.622030
ENSG00000266976    4.613299
GATA1              4.606162
B3GALT1-AS1        4.600043
Name: K562, dtype: float64
Indexes for Column "K562":
Index(['HBG1', 'HBZ', 'ABCB10P4', 'RHOXF2B', 'ENSG00000237311', 'RHAG',
       'LINC01029', 'ENSG00000266976', 'GATA1', 'B3GALT1-AS1'],
      dtype='object')

Top 10 values in Column "Gastric Epithelial Cell":
ENSG00000234442    5.627062
ENSG00000227297    5.428410
ENSG00000274879    5.317161
ENSG00000232765    5.160830
TCN1               4.933351
MYH16              4.884090
PRSS33             4.695743
MRGPRX4            4.641356
VCX3A              4.426756
LINC01019          4.348929
Name: Gastric Epithelial Cell, dtype: float64
Indexes for Column "Gastric Epithelial Cell":
Index(['ENSG00000234442', 'ENSG00000227297', 'ENSG00000274879',
       'ENSG00000232765', 'TCN1', 'MYH16', 'PRSS33', 'MRGPRX4', 'VCX3A',
       'LINC01019'],
      dtype='object')

Top 10 values in Column "NALM6":
IGLV4-3            8.116240
IGHVII-60-1        7.521030
VPREB1             6.976264
DUX4L25            6.918929
IGHV5-78           6.420471
RAG2               6.337911
IGLC7              6.245513
ENSG00000272733    6.045086
MARK2P11           6.013246
TCL1A              5.954598
Name: NALM6, dtype: float64
Indexes for Column "NALM6":
Index(['IGLV4-3', 'IGHVII-60-1', 'VPREB1', 'DUX4L25', 'IGHV5-78', 'RAG2',
       'IGLC7', 'ENSG00000272733', 'MARK2P11', 'TCL1A'],
      dtype='object')

Top 10 values in Column "Pons":
HSPE1P18     3.885106
SELL         3.882414
LINC02648    3.774567
CCR2         3.762597
GIMAP1       3.649773
LINC00402    3.620016
GVINP1       3.611683
LINC01891    3.578750
BET1P1       3.575361
TRBJ1-1      3.573922
Name: Pons, dtype: float64
Indexes for Column "Pons":
Index(['HSPE1P18', 'SELL', 'LINC02648', 'CCR2', 'GIMAP1', 'LINC00402',
       'GVINP1', 'LINC01891', 'BET1P1', 'TRBJ1-1'],
      dtype='object')

Top 10 values in Column "Cardiac Muscle Fiber":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Cardiac Muscle Fiber, dtype: float64
Indexes for Column "Cardiac Muscle Fiber":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "REH":
ENSG00000253134    6.514532
ENSG00000288008    5.581588
RAG2               5.572193
ENSG00000233064    5.289132
RAG1               5.174650
DNTT               5.060801
BLACE              5.045821
ENSG00000254350    5.029378
ENSG00000272733    4.961844
ENSG00000253792    4.824077
Name: REH, dtype: float64
Indexes for Column "REH":
Index(['ENSG00000253134', 'ENSG00000288008', 'RAG2', 'ENSG00000233064', 'RAG1',
       'DNTT', 'BLACE', 'ENSG00000254350', 'ENSG00000272733',
       'ENSG00000253792'],
      dtype='object')

Top 10 values in Column "MCF7":
DSCAM-AS1          3.897102
SPTSSB             3.798569
ENSG00000234967    3.666060
TFF1               3.584453
ENSG00000267131    3.468209
ADAMTS19           3.431254
ENSG00000223808    3.377113
ENSG00000228503    3.339339
GATA3-AS1          3.270728
ESR1               3.244717
Name: MCF7, dtype: float64
Indexes for Column "MCF7":
Index(['DSCAM-AS1', 'SPTSSB', 'ENSG00000234967', 'TFF1', 'ENSG00000267131',
       'ADAMTS19', 'ENSG00000223808', 'ENSG00000228503', 'GATA3-AS1', 'ESR1'],
      dtype='object')

Top 10 values in Column "ES2":
CLDN6              2.691451
NRK                2.189615
ENSG00000267313    2.098607
FBN3               2.095947
CAPN6              2.041370
BMS1P13            1.991826
ENSG00000281566    1.922622
APELA              1.891868
GRPR               1.886339
ZSCAN10            1.879737
Name: ES2, dtype: float64
Indexes for Column "ES2":
Index(['CLDN6', 'NRK', 'ENSG00000267313', 'FBN3', 'CAPN6', 'BMS1P13',
       'ENSG00000281566', 'APELA', 'GRPR', 'ZSCAN10'],
      dtype='object')

Top 10 values in Column "Small Intestine":
LINC01871    3.977108
LCT          3.921265
FABP2        3.814068
DEFA5        3.808085
GPR171       3.774262
GZMA         3.757643
SI           3.695591
GPR15        3.629053
LINC00892    3.622690
CCL25        3.612106
Name: Small Intestine, dtype: float64
Indexes for Column "Small Intestine":
Index(['LINC01871', 'LCT', 'FABP2', 'DEFA5', 'GPR171', 'GZMA', 'SI', 'GPR15',
       'LINC00892', 'CCL25'],
      dtype='object')

Top 10 values in Column "T47D":
ENSG00000255065    5.251592
CT45A3             4.892251
PGR                4.512228
PIP                4.479248
OTOR               4.468274
ELF5               4.456210
ENSG00000235939    4.385545
ABCC11             4.224117
ENSG00000250230    4.164346
PRLR               4.074147
Name: T47D, dtype: float64
Indexes for Column "T47D":
Index(['ENSG00000255065', 'CT45A3', 'PGR', 'PIP', 'OTOR', 'ELF5',
       'ENSG00000235939', 'ABCC11', 'ENSG00000250230', 'PRLR'],
      dtype='object')

Top 10 values in Column "MDAMB231":
ENSG00000260761    4.047877
ADGRD1-AS1         3.613995
LINC01444          3.591926
ENSG00000276759    3.582552
SPANXB1            3.537511
CST4               3.477170
LINC02085          3.435462
COL13A1            3.409775
MANCR              3.368695
LINC00705          3.364136
Name: MDAMB231, dtype: float64
Indexes for Column "MDAMB231":
Index(['ENSG00000260761', 'ADGRD1-AS1', 'LINC01444', 'ENSG00000276759',
       'SPANXB1', 'CST4', 'LINC02085', 'COL13A1', 'MANCR', 'LINC00705'],
      dtype='object')

Top 10 values in Column "PANC1":
KHSRPP1            4.816461
ENSG00000232111    4.494085
ENSG00000282222    4.331752
ENSG00000282306    4.321588
ENSG00000281955    4.279730
ENSG00000282697    4.039490
ENSG00000282299    4.005192
ENSG00000281941    3.916169
SF3B4P1            3.875654
GATA5              3.864026
Name: PANC1, dtype: float64
Indexes for Column "PANC1":
Index(['KHSRPP1', 'ENSG00000232111', 'ENSG00000282222', 'ENSG00000282306',
       'ENSG00000281955', 'ENSG00000282697', 'ENSG00000282299',
       'ENSG00000281941', 'SF3B4P1', 'GATA5'],
      dtype='object')

Top 10 values in Column "Myoblast":
MYF5       6.343185
MYOD1      6.144391
CHRNA1     6.131751
ASB5       5.476447
MUSK       5.462711
CDH15      5.307949
RAPSN      5.287487
LINCMD1    5.262525
SGCA       4.657888
CAV3       4.627460
Name: Myoblast, dtype: float64
Indexes for Column "Myoblast":
Index(['MYF5', 'MYOD1', 'CHRNA1', 'ASB5', 'MUSK', 'CDH15', 'RAPSN', 'LINCMD1',
       'SGCA', 'CAV3'],
      dtype='object')

Top 10 values in Column "Alveolar":
CCL18              3.613102
PARAL1             3.582679
MARCO              3.561660
ENSG00000256948    3.471297
ENSG00000259094    3.351769
MCEMP1             3.288246
OR6N1              3.218265
ITPR2-AS1          3.211193
MSR1               3.133664
DNASE2B            3.123822
Name: Alveolar, dtype: float64
Indexes for Column "Alveolar":
Index(['CCL18', 'PARAL1', 'MARCO', 'ENSG00000256948', 'ENSG00000259094',
       'MCEMP1', 'OR6N1', 'ITPR2-AS1', 'MSR1', 'DNASE2B'],
      dtype='object')

Top 10 values in Column "IMR32":
ENSG00000228505    9.408724
PHOX2B             7.770225
PHOX2B-AS1         7.348122
LINC00682          7.326411
TLX2               7.268431
ENSG00000236605    7.144491
LINC01797          7.111040
PLSCR5             7.070524
PHOX2A             6.904378
LINC01829          6.869003

Top 10 values in Column "HACAT":
KRT13              5.576353
SERPINB13          5.012746
ENSG00000225867    4.914731
WNT10A             4.544580
ENSG00000223829    4.400080
KRT4               4.264268
HOXC12             3.916244
ENSG00000271392    3.890521
ENSG00000273760    3.854859
UGT1A6             3.798411
Name: HACAT, dtype: float64
Indexes for Column "HACAT":
Index(['KRT13', 'SERPINB13', 'ENSG00000225867', 'WNT10A', 'ENSG00000223829',
       'KRT4', 'HOXC12', 'ENSG00000271392', 'ENSG00000273760', 'UGT1A6'],
      dtype='object')

Top 10 values in Column "HEPG2":
ENSG00000230952    5.047049
BPIFB2             4.844706
AFP                4.773207
ENSG00000254054    4.768602
NR5A1              4.664911
ENSG00000260573    4.474278
NOTUM              4.332697
SP5                4.321472
DGKK               4.234709
SSUH2              4.127343
Name: HEPG2, dtype: float64
Indexes for Column "HEPG2":
Index(['ENSG00000230952', 'BPIFB2', 'AFP', 'ENSG00000254054', 'NR5A1',
       'ENSG00000260573', 'NOTUM', 'SP5', 'DGKK', 'SSUH2'],
      dtype='object')

Top 10 values in Column "Heart":
MYL7      5.099338
MYBPC3    5.008067
MYH6      5.007923
TECRL     4.853008
CSRP3     4.750611
MYH7      4.708310
MYOZ2     4.689247
NPPA      4.635491
TNNI3K    4.624834
PLN       4.597906
Name: Heart, dtype: float64
Indexes for Column "Heart":
Index(['MYL7', 'MYBPC3', 'MYH6', 'TECRL', 'CSRP3', 'MYH7', 'MYOZ2', 'NPPA',
       'TNNI3K', 'PLN'],
      dtype='object')

Top 10 values in Column "NHDF":
UBL4B              4.202647
ALX3               3.745102
LINC01397          3.395828
PSG1               3.384102
ENSG00000261625    3.219965
PRRX2              3.206496
PSG5               3.161185
LINC01615          3.056908
ADAM33             3.047124
ENSG00000286023    3.023857
Name: NHDF, dtype: float64
Indexes for Column "NHDF":
Index(['UBL4B', 'ALX3', 'LINC01397', 'PSG1', 'ENSG00000261625', 'PRRX2',
       'PSG5', 'LINC01615', 'ADAM33', 'ENSG00000286023'],
      dtype='object')

Top 10 values in Column "GSM2679484":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: GSM2679484, dtype: float64
Indexes for Column "GSM2679484":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "Midbrain":
ENSG00000229533    5.484988
LMX1A              5.054862
FERD3L             4.999943
DBX1               4.262455
RFX4               4.062745
LMX1A-AS2          4.036166
LHX5-AS1           3.903823
EFNB3              3.796974
CFC1               3.768817
BTBD17             3.747543
Name: Midbrain, dtype: float64
Indexes for Column "Midbrain":
Index(['ENSG00000229533', 'LMX1A', 'FERD3L', 'DBX1', 'RFX4', 'LMX1A-AS2',
       'LHX5-AS1', 'EFNB3', 'CFC1', 'BTBD17'],
      dtype='object')

Top 10 values in Column "Adipocyte":
ADIPOQ       3.139245
LGALS12      3.108990
CIDEC        3.027274
SLC66A1L     2.984226
LINC01914    2.960125
ADAMTS2      2.911863
CD248        2.890287
MEDAG        2.878199
MRAP         2.834272
ADAM12       2.824712
Name: Adipocyte, dtype: float64
Indexes for Column "Adipocyte":
Index(['ADIPOQ', 'LGALS12', 'CIDEC', 'SLC66A1L', 'LINC01914', 'ADAMTS2',
       'CD248', 'MEDAG', 'MRAP', 'ADAM12'],
      dtype='object')

Top 10 values in Column "Basal Cell":
TMPRSS11D    4.354012
TP63         3.849989
KRT6A        3.808019
KRT5         3.700690
FGFBP1       3.663666
S100A2       3.552445
GBP6         3.534667
KRT17        3.528300
DSG3         3.494786
KRT17P1      3.456842
Name: Basal Cell, dtype: float64
Indexes for Column "Basal Cell":
Index(['TMPRSS11D', 'TP63', 'KRT6A', 'KRT5', 'FGFBP1', 'S100A2', 'GBP6',
       'KRT17', 'DSG3', 'KRT17P1'],
      dtype='object')

Top 10 values in Column "U937":
LINC02470          6.134406
ENSG00000225365    5.718102
COX8C              5.653217
SIGLEC12           5.333569
ENSG00000285254    5.277341
ENSG00000285722    5.232700
NXF3               5.191397
CLEC2A             4.789395
ENSG00000282925    4.735014
CLECL1             4.682496
Name: U937, dtype: float64
Indexes for Column "U937":
Index(['LINC02470', 'ENSG00000225365', 'COX8C', 'SIGLEC12', 'ENSG00000285254',
       'ENSG00000285722', 'NXF3', 'CLEC2A', 'ENSG00000282925', 'CLECL1'],
      dtype='object')

Top 10 values in Column "Hypothalamus":
SNORD115-48        5.979902
PMCH               5.608758
ENSG00000222185    5.507128
SNORD113-4         5.253778
TCEAL6             5.146134
ENSG00000260878    5.046423
PNMA6F             4.989943
MMEL1-AS1          4.873152
CARTPT             4.846410
ENSG00000285629    4.818934
Name: Hypothalamus, dtype: float64
Indexes for Column "Hypothalamus":
Index(['SNORD115-48', 'PMCH', 'ENSG00000222185', 'SNORD113-4', 'TCEAL6',
       'ENSG00000260878', 'PNMA6F', 'MMEL1-AS1', 'CARTPT', 'ENSG00000285629'],
      dtype='object')

Top 10 values in Column "Dendritic":
CD1C       4.400924
TIFAB      4.341964
CCL17      4.245047
CD1B       4.151313
CXCR2P1    4.084911
RUFY4      4.077310
CCL22      3.930491
WDFY4      3.926457
FCER2      3.920662
IRF4       3.822351
Name: Dendritic, dtype: float64
Indexes for Column "Dendritic":
Index(['CD1C', 'TIFAB', 'CCL17', 'CD1B', 'CXCR2P1', 'RUFY4', 'CCL22', 'WDFY4',
       'FCER2', 'IRF4'],
      dtype='object')

Top 10 values in Column "RKO":
ENSG00000255866    4.489390
ENSG00000233491    4.387892
MSRB3-AS1          4.091251
RPS26P4            4.039792
ENSG00000230033    3.999249
LINC01592          3.941643
PCNPP3             3.823095
ENSG00000249061    3.729660
ENSG00000288074    3.695943
MAGEB17            3.649876
Name: RKO, dtype: float64
Indexes for Column "RKO":
Index(['ENSG00000255866', 'ENSG00000233491', 'MSRB3-AS1', 'RPS26P4',
       'ENSG00000230033', 'LINC01592', 'PCNPP3', 'ENSG00000249061',
       'ENSG00000288074', 'MAGEB17'],
      dtype='object')

Top 10 values in Column "Tlymphocyte":
CD5         4.910783
TRBV29-1    4.854609
TRAV12-3    4.718836
TRBV5-1     4.713974
CD6         4.713510
ICOS        4.620267
TRAV12-1    4.611602
TRBV2       4.606642
TRAV13-1    4.602843
TRAT1       4.581824
Name: Tlymphocyte, dtype: float64
Indexes for Column "Tlymphocyte":
Index(['CD5', 'TRBV29-1', 'TRAV12-3', 'TRBV5-1', 'CD6', 'ICOS', 'TRAV12-1',
       'TRBV2', 'TRAV13-1', 'TRAT1'],
      dtype='object')

Top 10 values in Column "Valve":
PKHD1L1            4.500498
TBX20              4.317936
BMX                3.813857
CALCRL             3.696537
ART4               3.679530
EMCN               3.632567
HTR2B              3.608770
ENSG00000226063    3.519015
IL33               3.420653
GATA4              3.395424
Name: Valve, dtype: float64
Indexes for Column "Valve":
Index(['PKHD1L1', 'TBX20', 'BMX', 'CALCRL', 'ART4', 'EMCN', 'HTR2B',
       'ENSG00000226063', 'IL33', 'GATA4'],
      dtype='object')

Top 10 values in Column "Fibroblast":
PSG5        2.682727
GREM1       2.593337
CD248       2.433027
TWIST2      2.427102
MRGPRF      2.426499
PAMR1       2.417206
TBX5-AS1    2.414819
FGF5        2.402932
GPR176      2.401255
LAYN        2.395037
Name: Fibroblast, dtype: float64
Indexes for Column "Fibroblast":
Index(['PSG5', 'GREM1', 'CD248', 'TWIST2', 'MRGPRF', 'PAMR1', 'TBX5-AS1',
       'FGF5', 'GPR176', 'LAYN'],
      dtype='object')

Top 10 values in Column "Macroglia":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Macroglia, dtype: float64
Indexes for Column "Macroglia":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "Osteoblast":
LINC01614          3.742050
ITGA11             3.700036
HAPLN1             3.649525
GDF6               3.349642
COL11A1            3.288561
GDF5               3.283269
ITGBL1             3.191191
ADAMTS2            3.187915
POSTN              3.161967
ENSG00000225166    3.149826
Name: Osteoblast, dtype: float64
Indexes for Column "Osteoblast":
Index(['LINC01614', 'ITGA11', 'HAPLN1', 'GDF6', 'COL11A1', 'GDF5', 'ITGBL1',
       'ADAMTS2', 'POSTN', 'ENSG00000225166'],
      dtype='object')

Top 10 values in Column "Myofibroblast":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Myofibroblast, dtype: float64
Indexes for Column "Myofibroblast":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "Lung Epithelial":
AKR1B10P1          3.899164
CYP24A1            3.497381
INSL4              3.403668
PRYP1              3.339648
ENSG00000286587    3.198228
GACAT2             3.133247
ENSG00000236921    3.044028
ALDH3A1            3.039775
RPL7AP75           3.035411
LINP1              3.004245
Name: Lung Epithelial, dtype: float64
Indexes for Column "Lung Epithelial":
Index(['AKR1B10P1', 'CYP24A1', 'INSL4', 'PRYP1', 'ENSG00000286587', 'GACAT2',
       'ENSG00000236921', 'ALDH3A1', 'RPL7AP75', 'LINP1'],
      dtype='object')

Top 10 values in Column "Thymus":
LINC02295          5.060169
LDC1P              4.703920
TRBV28             4.622644
ENSG00000259097    4.543115
ANTXRLP1           4.348281
LCT-AS1            4.289542
ENSG00000236656    4.288792
TTC24              4.262441
RAG2               4.222367
PTCRA              4.090876
Name: Thymus, dtype: float64
Indexes for Column "Thymus":
Index(['LINC02295', 'LDC1P', 'TRBV28', 'ENSG00000259097', 'ANTXRLP1',
       'LCT-AS1', 'ENSG00000236656', 'TTC24', 'RAG2', 'PTCRA'],
      dtype='object')

Top 10 values in Column "NCIH460":
ENSG00000238054    8.434591
TBXT               8.304244
LINC01035          7.507717
SERPINB11          6.941797
LNCDAT             6.439623
LINC00824          6.413081
ENSG00000287792    6.278063
LINC02539          6.092946
SPANXN4            5.831687
LCN1               5.829348
Name: NCIH460, dtype: float64
Indexes for Column "NCIH460":
Index(['ENSG00000238054', 'TBXT', 'LINC01035', 'SERPINB11', 'LNCDAT',
       'LINC00824', 'ENSG00000287792', 'LINC02539', 'SPANXN4', 'LCN1'],
      dtype='object')

Top 10 values in Column "Thymocyte":
LINC02536          8.727447
OR10R2             7.971841
ELOCP2             7.938331
LINC02295          7.674679
ENSG00000236656    7.446016
ENSG00000232208    7.371354
LINC02312          7.315631
ENSG00000287785    7.260024
OR10T1P            7.160929
LINC00226          7.107348
Name: Thymocyte, dtype: float64
Indexes for Column "Thymocyte":
Index(['LINC02536', 'OR10R2', 'ELOCP2', 'LINC02295', 'ENSG00000236656',
       'ENSG00000232208', 'LINC02312', 'ENSG00000287785', 'OR10T1P',
       'LINC00226'],
      dtype='object')

Top 10 values in Column "A431":
MAGEA4             5.371866
MAGEA4-AS1         4.994707
KRT13              4.945425
LINC02434          4.032628
ENSG00000234442    4.007621
LINC02999          4.000178
ENSG00000283178    3.957351
LINC01983          3.587930
LY6D               3.488978
LINC01843          3.437964
Name: A431, dtype: float64
Indexes for Column "A431":
Index(['MAGEA4', 'MAGEA4-AS1', 'KRT13', 'LINC02434', 'ENSG00000234442',
       'LINC02999', 'ENSG00000283178', 'LINC01983', 'LY6D', 'LINC01843'],
      dtype='object')

Top 10 values in Column "Ventricle":
LINC02502          6.104289
MYBPC3             5.945862
MYL2               5.898874
TECRL              5.878081
ENSG00000236958    5.870434
MYOZ2              5.857004
LMOD2              5.791645
NPY6R              5.727259
CSRP3              5.722918
CASQ2              5.709239
Name: Ventricle, dtype: float64
Indexes for Column "Ventricle":
Index(['LINC02502', 'MYBPC3', 'MYL2', 'TECRL', 'ENSG00000236958', 'MYOZ2',
       'LMOD2', 'NPY6R', 'CSRP3', 'CASQ2'],
      dtype='object')

Top 10 values in Column "Primary Liver Cell":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Primary Liver Cell, dtype: float64
Indexes for Column "Primary Liver Cell":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "MRC5":
MTCO2P22           4.005664
MTND4LP30          3.699037
PAFAH1B1P1         3.669095
ENSG00000285703    3.557326
ENSG00000225655    3.521963
ZNF45-AS1          3.478167
ENSG00000255496    3.413797
ENSG00000259932    3.402053
ENSG00000256098    3.379292
BDNF               3.375219
Name: MRC5, dtype: float64
Indexes for Column "MRC5":
Index(['MTCO2P22', 'MTND4LP30', 'PAFAH1B1P1', 'ENSG00000285703',
       'ENSG00000225655', 'ZNF45-AS1', 'ENSG00000255496', 'ENSG00000259932',
       'ENSG00000256098', 'BDNF'],
      dtype='object')

Top 10 values in Column "DAOY":
DAZ4               8.437283
DAZ1               7.189585
DAZ3               7.063948
CT47A1             7.007442
CT47A6             6.767748
FMR1NB             6.460924
CT47A11            6.437127
TEX13C             6.277382
ENSG00000233887    6.238684
ENSG00000258763    6.237722
Name: DAOY, dtype: float64
Indexes for Column "DAOY":
Index(['DAZ4', 'DAZ1', 'DAZ3', 'CT47A1', 'CT47A6', 'FMR1NB', 'CT47A11',
       'TEX13C', 'ENSG00000233887', 'ENSG00000258763'],
      dtype='object')

Top 10 values in Column "THP1":
LINC02169          4.965235
ENSG00000253821    4.909509
FAM205C            4.853761
ENSG00000232197    4.829150
ENSG00000257883    4.653099
LINC01388          4.565710
ENSG00000257654    4.548378
PRTN3              4.433150
AZU1               4.382027
ELANE              4.281159
Name: THP1, dtype: float64
Indexes for Column "THP1":
Index(['LINC02169', 'ENSG00000253821', 'FAM205C', 'ENSG00000232197',
       'ENSG00000257883', 'LINC01388', 'ENSG00000257654', 'PRTN3', 'AZU1',
       'ELANE'],
      dtype='object')

Top 10 values in Column "Colonic Muscosa":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Colonic Muscosa, dtype: float64
Indexes for Column "Colonic Muscosa":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "C42":
KLK3               5.274761
KLK2               5.112705
PAGE1              4.845054
FOLH1              4.495594
NXF2               4.385410
KLK15              4.319146
KLKP1              4.279610
KLK4               4.266319
NXF2B              4.180099
ENSG00000280881    4.089929
Name: C42, dtype: float64
Indexes for Column "C42":
Index(['KLK3', 'KLK2', 'PAGE1', 'FOLH1', 'NXF2', 'KLK15', 'KLKP1', 'KLK4',
       'NXF2B', 'ENSG00000280881'],
      dtype='object')

Top 10 values in Column "Respiratory Smooth Muscle":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Respiratory Smooth Muscle, dtype: float64
Indexes for Column "Respiratory Smooth Muscle":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "Sensory Neuron":
DRGX               7.632382
PIRT               7.183790
ENSG00000232529    6.553804
MARCHF11           6.511579
PRPH               6.407381
LINC02735          6.186399
SV2C-AS1           6.023585
CHRNB3             5.823249
SKOR2              5.812487
KCNA6              5.542489
Name: Sensory Neuron, dtype: float64
Indexes for Column "Sensory Neuron":
Index(['DRGX', 'PIRT', 'ENSG00000232529', 'MARCHF11', 'PRPH', 'LINC02735',
       'SV2C-AS1', 'CHRNB3', 'SKOR2', 'KCNA6'],
      dtype='object')

Top 10 values in Column "Skin":
KRTDAP      3.467030
KRT1        3.421810
SBSN        3.330560
DSG1        3.314727
WFDC5       3.308701
KRT2        3.264861
LGALS7B     3.251074
LCE1C       3.245738
LORICRIN    3.229053
CERS3       3.228231
Name: Skin, dtype: float64
Indexes for Column "Skin":
Index(['KRTDAP', 'KRT1', 'SBSN', 'DSG1', 'WFDC5', 'KRT2', 'LGALS7B', 'LCE1C',
       'LORICRIN', 'CERS3'],
      dtype='object')

Top 10 values in Column "A549":
CYP24A1            4.168494
ALDH3A1            3.979215
NPY4R              3.902308
ENSG00000236921    3.881292
NPY4R2             3.873475
ENSG00000250271    3.822402
HAVCR1             3.803898
GABRA5             3.790861
NR0B1              3.704673
KRT81              3.690222
Name: A549, dtype: float64
Indexes for Column "A549":
Index(['CYP24A1', 'ALDH3A1', 'NPY4R', 'ENSG00000236921', 'NPY4R2',
       'ENSG00000250271', 'HAVCR1', 'GABRA5', 'NR0B1', 'KRT81'],
      dtype='object')

Top 10 values in Column "Cerebral Cortex":
PCDHGC4            4.985519
NR2E1              4.911959
SLCO1C1            4.834757
ENSG00000227157    4.746316
NCAN               4.726748
LHX2               4.629133
LINC01114          4.501380
MIR9-1HG           4.375985
KCNIP1             4.300151
PTPRZ1             4.295025
Name: Cerebral Cortex, dtype: float64
Indexes for Column "Cerebral Cortex":
Index(['PCDHGC4', 'NR2E1', 'SLCO1C1', 'ENSG00000227157', 'NCAN', 'LHX2',
       'LINC01114', 'MIR9-1HG', 'KCNIP1', 'PTPRZ1'],
      dtype='object')

Top 10 values in Column "Plasmacytoid Dendritic Cell":
A1BG        NaN
A1BG-AS1    NaN
A1CF        NaN
A2M         NaN
A2M-AS1     NaN
A2ML1       NaN
A2ML1-AS1   NaN
A2ML1-AS2   NaN
A2MP1       NaN
A3GALT2     NaN
Name: Plasmacytoid Dendritic Cell, dtype: float64
Indexes for Column "Plasmacytoid Dendritic Cell":
Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2'],
      dtype='object')

Top 10 values in Column "Breast":
GATA3      1.756471
SPDEF      1.752214
PRLR       1.734990
VTCN1      1.724950
TDRD5      1.673567
IRX5       1.656830
ELAPOR1    1.641152
TRPS1      1.640208
TACSTD2    1.625255
MLPH       1.624713
Name: Breast, dtype: float64
Indexes for Column "Breast":
Index(['GATA3', 'SPDEF', 'PRLR', 'VTCN1', 'TDRD5', 'IRX5', 'ELAPOR1', 'TRPS1',
       'TACSTD2', 'MLPH'],
      dtype='object')

Top 10 values in Column "LNCAP":
FOLH1              4.942462
PRAC1              4.877179
KLK3               4.789568
ENSG00000280881    4.633794
ENSG00000261554    4.591790
HOXB13             4.507208
ENSG00000242407    4.477605
ENSG00000261048    4.448330
PRAC2              4.417411
ANK3-DT            4.412093
Name: LNCAP, dtype: float64
Indexes for Column "LNCAP":
Index(['FOLH1', 'PRAC1', 'KLK3', 'ENSG00000280881', 'ENSG00000261554',
       'HOXB13', 'ENSG00000242407', 'ENSG00000261048', 'PRAC2', 'ANK3-DT'],
      dtype='object')

Top 10 values in Column "Airway Smooth Muscle":
CCKAR        4.914166
TCF21        4.493769
LINC00578    4.401701
ADAMTS8      4.360377
LINC01394    4.341252
LINC01081    4.291816
CHRM2        4.228848
CCL11        4.171539
SVEP1        4.084192
LINC00968    4.082879
Name: Airway Smooth Muscle, dtype: float64
Indexes for Column "Airway Smooth Muscle":
Index(['CCKAR', 'TCF21', 'LINC00578', 'ADAMTS8', 'LINC01394', 'LINC01081',
       'CHRM2', 'CCL11', 'SVEP1', 'LINC00968'],
      dtype='object')

Top 10 values in Column "Bone Marrow":
FAM30A      2.796082
PRSS57      2.616795
MPO         2.585790
HBD         2.469281
IGLL1       2.428346
ARHGAP15    2.408295
SPINK2      2.385361
P2RX1       2.384224
CD69        2.379513
HSH2D       2.338052
Name: Bone Marrow, dtype: float64
Indexes for Column "Bone Marrow":
Index(['FAM30A', 'PRSS57', 'MPO', 'HBD', 'IGLL1', 'ARHGAP15', 'SPINK2',
       'P2RX1', 'CD69', 'HSH2D'],
      dtype='object')

Top 10 values in Column "Testis":
FATE1       7.082574
MIR202HG    5.962683
DMRT1       5.616609
ZPBP        5.605816
FAM236A     5.590475
H2AC1       5.576320
TRPC5OS     5.568839
PRM2        5.529816
H2BC1       5.529142
PRM1        5.513444

Top 10 values in Column "NHBE":
TMPRSS11D          4.771653
PTHLH              4.525721
CXCL17             4.517544
BPIFA1             4.491991
UPK1B              4.429559
SPRR3              4.297878
KRT13              4.206479
ATP12A             4.196498
ENSG00000253339    4.191707
BPIFA2             4.021317
Name: NHBE, dtype: float64
Indexes for Column "NHBE":
Index(['TMPRSS11D', 'PTHLH', 'CXCL17', 'BPIFA1', 'UPK1B', 'SPRR3', 'KRT13',
       'ATP12A', 'ENSG00000253339', 'BPIFA2'],
      dtype='object')

Top 10 values in Column "293F":
IRS4         4.366126
IRS4-AS1     3.840856
HOXD13       3.810112
HOXD10       3.397886
HOXD11       3.397428
CALCB        3.317992
FOXCUT       3.302458
SLIT2-IT1    3.271360
RADX         3.248082
HMX1         3.107774
Name: 293F, dtype: float64
Indexes for Column "293F":
Index(['IRS4', 'IRS4-AS1', 'HOXD13', 'HOXD10', 'HOXD11', 'CALCB', 'FOXCUT',
       'SLIT2-IT1', 'RADX', 'HMX1'],
      dtype='object')

Top 10 values in Column "Skeletal Muscle":
MYH2               6.518207
MYL1               6.483218
MYH1               6.395650
CACNA1S            6.326000
MYF6               6.280370
MYBPC2             6.237751
KLHL40             6.175703
ENSG00000265751    6.083115
VGLL2              6.041567
MYOT               6.008206
Name: Skeletal Muscle, dtype: float64
Indexes for Column "Skeletal Muscle":
Index(['MYH2', 'MYL1', 'MYH1', 'CACNA1S', 'MYF6', 'MYBPC2', 'KLHL40',
       'ENSG00000265751', 'VGLL2', 'MYOT'],
      dtype='object')

Top 10 values in Column "HUVEC":
BMX                4.900746
MMRN1              4.798237
HHIP               4.610408
LINC02915          4.554240
HTR1B              4.527708
ESM1               4.500996
LINC01013          4.453465
ECSCR              4.358997
ENSG00000259072    4.333798
FAM124B            4.323573
Name: HUVEC, dtype: float64
Indexes for Column "HUVEC":
Index(['BMX', 'MMRN1', 'HHIP', 'LINC02915', 'HTR1B', 'ESM1', 'LINC01013',
       'ECSCR', 'ENSG00000259072', 'FAM124B'],
      dtype='object')

Top 10 values in Column "LHCNM2":
ENSG00000258073    5.886246
ASB5               5.640876
FDCSP              5.391537
TECTB              4.558092
LINC00475          4.466091
NKX2-6             4.396290
ZNF736P9Y          4.319229
CTAGE1             4.252988
SMILR              4.234759
GAPDHP36           4.169649
Name: LHCNM2, dtype: float64
Indexes for Column "LHCNM2":
Index(['ENSG00000258073', 'ASB5', 'FDCSP', 'TECTB', 'LINC00475', 'NKX2-6',
       'ZNF736P9Y', 'CTAGE1', 'SMILR', 'GAPDHP36'],
      dtype='object')

---

In [37]:
# Convert category_dict value list elements to lowercase
for category, value_list in category_dict.items():
    for i in range(len(value_list)):
        value_list[i] = value_list[i].lower()
# print(category_dict)

gene_system_idx = {}
for category, keywords in category_dict.items():
    category_indexes = []
    for i, sample_name in enumerate(category_names):
        for keyword in keywords:
            if keyword.lower() in sample_name.lower():
                category_indexes.append(i)
                break
    gene_system_idx[category] = category_indexes
    
gene_cat_avgs = []
for gene_row in logOE_matrix:
    cat_avg = []

    for system, indexes in gene_system_idx.items():
        values = [gene_row[index] for index in indexes]
        mean = sum(values)/len(values)
        cat_avg.append(mean)
    gene_cat_avgs.append(cat_avg)
    
print(len(gene_cat_avgs))

57447

In [38]:
len(gene_cat_avgs[1])

9

In [39]:
from IPython.display import display
system_list = ["Cardiovascular System",  "Connective Tissue", "Digestive System", 
"Immune System", "Integumentary System", "Muscular System", "Nervous System", 
"Respiratory System", "Urogenital System"]

df2 = pd.DataFrame(gene_cat_avgs, index=gene_names)
df2.columns = system_list
display(df2)

,Cardiovascular System,Connective Tissue,Digestive System,Immune System,Integumentary System,Muscular System,Nervous System,Respiratory System,Urogenital System
A1BG,0.305966,0.708426,1.248448,0.844066,0.640211,0.561007,0.546976,0.528425,0.503570
A1BG-AS1,0.558774,0.756588,0.537718,1.305408,1.010191,0.933012,0.777112,0.842564,0.932369
A1CF,0.045954,0.100313,1.982509,0.059649,0.068101,0.064614,0.054311,0.174963,0.141632
A2M,1.107140,0.493541,1.325945,0.972785,0.528030,0.857117,0.778685,0.546899,0.273653
A2M-AS1,1.317304,0.652329,0.977607,0.832580,0.435369,0.994019,0.732597,0.696619,0.524775
...,...,...,...,...,...,...,...,...,...
ZYG11B,1.238867,0.934100,0.870405,0.858955,0.933131,1.711243,1.271286,0.784692,0.822411
ZYX,1.093685,0.881272,0.861870,1.192684,1.124079,0.925389,0.747380,1.042486,0.818319
ZYXP1,0.545229,0.757613,0.596743,0.695417,0.611088,0.549441,0.408711,0.596826,0.694336
ZZEF1,1.049889,0.898072,0.922819,1.183043,0.920057,1.004202,0.939314,0.919760,0.896280
ZZZ3,0.928215,0.921268,0.903930,0.818418,0.964310,1.052989,0.961266,0.828013,1.060767

In [41]:
# loop through each column and get the top 10 highest values and their indexes
for col in df2.columns:
    top_10 = df2[col].nlargest(10)
    print('Top 10 values in Column "{}":'.format(col))
    print(top_10)
    print('Indexes for Column "{}":'.format(col))
    print(top_10.index)
    print()

Top 10 values in Column "Cardiovascular System":
CLEC14A     3.260261
ANKRD1      3.248686
CDH5        3.216833
ECSCR       3.185909
VWF         3.139767
MYCT1       3.089548
ARHGEF15    3.089133
BMX         3.039261
MMRN2       2.997747
SCN5A       2.984509
Name: Cardiovascular System, dtype: float64
Indexes for Column "Cardiovascular System":
Index(['CLEC14A', 'ANKRD1', 'CDH5', 'ECSCR', 'VWF', 'MYCT1', 'ARHGEF15', 'BMX',
       'MMRN2', 'SCN5A'],
      dtype='object')

Top 10 values in Column "Connective Tissue":
HEMGN     1.842342
NFE2      1.839974
SPTA1     1.810053
GYPE      1.785223
STAT5A    1.781637
GFI1B     1.771943
RHAG      1.766371
GYPA      1.765118
GATA1     1.758689
GYPC      1.756836
Name: Connective Tissue, dtype: float64
Indexes for Column "Connective Tissue":
Index(['HEMGN', 'NFE2', 'SPTA1', 'GYPE', 'STAT5A', 'GFI1B', 'RHAG', 'GYPA',
       'GATA1', 'GYPC'],
      dtype='object')

Top 10 values in Column "Digestive System":
HNF4A     2.146045
FOXA3     2.128221
TRIM15    2.080486
FABP1     2.064360
RNF128    1.985633
GJB1      1.984265
A1CF      1.982509
TM4SF5    1.943513
ANKS4B    1.927086
VIL1      1.921176
Name: Digestive System, dtype: float64
Indexes for Column "Digestive System":
Index(['HNF4A', 'FOXA3', 'TRIM15', 'FABP1', 'RNF128', 'GJB1', 'A1CF', 'TM4SF5',
       'ANKS4B', 'VIL1'],
      dtype='object')

Top 10 values in Column "Immune System":
NCKAP1L     2.547739
ARHGAP30    2.470130
PLEK        2.448690
VAV1        2.438844
SASH3       2.419160
PIK3R5      2.417736
ITGB2       2.413698
WDFY4       2.410036
PARVG       2.401529
DOCK2       2.386670
Name: Immune System, dtype: float64
Indexes for Column "Immune System":
Index(['NCKAP1L', 'ARHGAP30', 'PLEK', 'VAV1', 'SASH3', 'PIK3R5', 'ITGB2',
       'WDFY4', 'PARVG', 'DOCK2'],
      dtype='object')

Top 10 values in Column "Integumentary System":
SERPINB7    2.020617
XG          1.893249
THBS2       1.856432
SNAI2       1.843916
TWIST2      1.824281
PRRX2       1.799265
FRMD6       1.797588
COL16A1     1.794146
COL1A2      1.756876
PAMR1       1.752138
Name: Integumentary System, dtype: float64
Indexes for Column "Integumentary System":
Index(['SERPINB7', 'XG', 'THBS2', 'SNAI2', 'TWIST2', 'PRRX2', 'FRMD6',
       'COL16A1', 'COL1A2', 'PAMR1'],
      dtype='object')

Top 10 values in Column "Muscular System":
ASB5       4.728098
MYF6       4.446353
KLHL41     4.201847
MYOD1      4.151494
CAV3       4.102902
LINCMD1    4.080190
MYL1       4.029192
MYLPF      4.010265
RAPSN      3.982247
SGCA       3.930879
Name: Muscular System, dtype: float64
Indexes for Column "Muscular System":
Index(['ASB5', 'MYF6', 'KLHL41', 'MYOD1', 'CAV3', 'LINCMD1', 'MYL1', 'MYLPF',
       'RAPSN', 'SGCA'],
      dtype='object')

Top 10 values in Column "Nervous System":
GPM6A     2.451693
STMN4     2.400744
GAP43     2.390769
ATCAY     2.389609
ASTN1     2.381879
TAGLN3    2.371391
MAP2      2.361668
KIF5C     2.360534
SYT11     2.359097
GPM6B     2.356494
Name: Nervous System, dtype: float64
Indexes for Column "Nervous System":
Index(['GPM6A', 'STMN4', 'GAP43', 'ATCAY', 'ASTN1', 'TAGLN3', 'MAP2', 'KIF5C',
       'SYT11', 'GPM6B'],
      dtype='object')

Top 10 values in Column "Respiratory System":
ALDH3A1            1.816616
ENSG00000218048    1.725483
CYP24A1            1.678967
PCED1B             1.658985
KRT7               1.658668
ENSG00000187185    1.654656
ENSG00000256802    1.640662
NR0B1              1.634653
AMIGO2             1.630907
ALDH3B1            1.608880
Name: Respiratory System, dtype: float64
Indexes for Column "Respiratory System":
Index(['ALDH3A1', 'ENSG00000218048', 'CYP24A1', 'PCED1B', 'KRT7',
       'ENSG00000187185', 'ENSG00000256802', 'NR0B1', 'AMIGO2', 'ALDH3B1'],
      dtype='object')

Top 10 values in Column "Urogenital System":
HOXC13      1.403953
RASEF       1.363527
ZYG11A      1.341482
ZNF239      1.330119
DUXAP8      1.327798
MNX1-AS1    1.323786
PRMT6       1.321352
MAP3K21     1.321058
ARHGAP8     1.319212
CBX2        1.313398
Name: Urogenital System, dtype: float64
Indexes for Column "Urogenital System":
Index(['HOXC13', 'RASEF', 'ZYG11A', 'ZNF239', 'DUXAP8', 'MNX1-AS1', 'PRMT6',
       'MAP3K21', 'ARHGAP8', 'CBX2'],
      dtype='object')